#+TITLE: Sistemas Trifásicos
#+DATE: 
#+SETUPFILE: config.org
#+OPTIONS: H:2

* Introducción

** 
   :PROPERTIES:
   :beamer_opt: plain
   :END:
file:figs/EstrellaEquilibrado.pdf

** Motivación de los sistemas trifásicos

-  En un sistema trifásico la potencia instantánea es constante, evitando vibraciones y esfuerzos en las máquinas. (/La potencia instantánea de un sistema monofásico es pulsante./)

- La masa de conductor necesaria en un sistema trifásico es un 25% inferior que en un monofásico para transportar la misma potencia.

** Ondas Trifásicas

 [[file:figs/TensionesTrifasica.pdf]]

 #+begin_export latex
 \begin{align*}
   u_1(t) &= U_0 \cos(\omega t)\\
   u_2(t) &= U_0 \cos(\omega t + 2\pi/3)\\
   u_3(t) &= U_0 \cos(\omega t - 2\pi/3)
 \end{align*}
 #+end_export

** Fasores de un sistema trifásico
#+ATTR_LATEX: :height 0.5\textheight
[[file:figs/FasoresTrifasica.pdf]]

 #+begin_export latex
 \begin{align*}
   \overline{U}_1 &= U\phase{0}\\
   \overline{U}_2 &= U\phase{2\pi/3}\\
   \overline{U}_3 &= U\phase{-2\pi/3}
 \end{align*}
 #+end_export

* Generadores
** Conexión
#+ATTR_LATEX: :height 0.5\textheight
[[file:figs/GeneradoresTrifasica.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

#+begin_export latex
\begin{align*}
  u_1(t) &= U_0 \cos(\omega t)\\
  u_2(t) &= U_0 \cos(\omega t + 2\pi/3)\\
  u_3(t) &= U_0 \cos(\omega t - 2\pi/3)
\end{align*}
#+end_export

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 #+begin_export latex
 \begin{align*}
   \overline{U}_1 &= U\phase{0}\\
   \overline{U}_2 &= U\phase{2\pi/3}\\
   \overline{U}_3 &= U\phase{-2\pi/3}
 \end{align*}
 #+end_export

** Las tensiones suman 0
#+ATTR_LATEX: :height 0.6\textheight
[[file:figs/FasoresSumaCero.pdf]]

#+begin_export latex
\[
\boxed{\overline{U}_1 + \overline{U}_2 + \overline{U}_3 = 0}
\]
#+end_export

** Las tensiones suman 0
[[file:figs/TensionesTrifasica.pdf]]

#+begin_export latex
\[
\boxed{u_1(t) + u_2(t) + u_3(t) = 0}
\]
#+end_export


** Tensiones de Fase y Línea

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
 #+ATTR_LATEX: :height 0.4\textheight
 [[file:figs/FasoresTrifasica_ABC.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.6
    :END:
Tensiones de *Fase*: $U_A$, $U_B$, $U_C$

Tensiones de *Línea*: $U_{AB}$, $U_{BC}$, $U_{CA}$

***                                                         :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
     #+begin_export latex
     \begin{align*}
       \overline{U}_{AB} &= \overline{U}_A - \overline{U}_B\\
       \overline{U}_{BC} &= \overline{U}_B - \overline{U}_C\\
       \overline{U}_{CA} &= \overline{U}_C - \overline{U}_A\\
\cline{1-2}
       \overline{U}_{AB} + \overline{U}_{BC} + \overline{U}_{CA} &= 0     \end{align*}
     #+end_export

** Tensiones de Fase y Línea


***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

   #+begin_export latex
   \begin{align*}
     \overline{U}_A &= U_f\phase{\theta_f}\\
     \overline{U}_B &= U_f\phase{\theta_f - \ang{120}}
   \end{align*}
   #+end_export

    #+begin_export latex
    \begin{align*}
    \overline{U}_{AB} &= \overline{U}_A - \overline{U}_B = \\
		      &= U_f\phase{\theta_f} - U_f\phase{\theta_f - \ang{120}} = \\
		      &= U_f\phase{\theta_f} + U_f\phase{\theta_f + \ang{60}}\\
		      &= 2 \cdot U_f \cdot \cos(30) \phase{\theta_f + \ang{30}} = \\
      &= \sqrt{3} U_f \phase{\theta_f + \ang{30}}
    \end{align*}
    #+end_export

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 [[file:figs/FasoresFaseLinea.pdf]]

    #+begin_export latex
    \[
      \boxed{
	\begin{array}{l}
	  U = \sqrt{3}\cdot U_f\\
	  \theta_l = \theta_f + \ang{30}\\
	\end{array}
      }
    \]
    #+end_export
** Secuencia de Fases

- Sentido en el que ocurren los máximos de cada fase.
- Secuencia de Fases Directa (*SFD*): ABC
#+ATTR_LATEX: :height 0.3\textheight
[[file:figs/TensionesTrifasica_ABC.pdf]]
- Secuencia de Fases Inversa (*SFI*): ACB
#+ATTR_LATEX: :height 0.3\textheight
[[file:figs/TensionesTrifasica_ACB.pdf]]

** Secuencia de Fases Directa (SFD)
#+ATTR_LATEX: :height 0.45\textheight
[[file:figs/FasoresTrifasica_ABC.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
  #+begin_export latex
  \begin{align*}
    \overline{U}_A &= \frac{U}{\sqrt{3}}\phase{{\color{blue}\ang{90}}}\\
    \overline{U}_B &= \frac{U}{\sqrt{3}}\phase{\ang{-30}}\\
    \overline{U}_C &= \frac{U}{\sqrt{3}}\phase{\ang{-150}}
  \end{align*}
  #+end_export
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.2
    :END:
[[file:figs/ReglaSFD.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
  #+begin_export latex
  \begin{align*}
    \overline{U}_{AB} &= U\phase{\ang{120}}\\
    \overline{U}_{BC} &= U\phase{{\color{blue}\ang{0}}}\\
    \overline{U}_{CA} &= U\phase{\ang{-120}}
  \end{align*}
  #+end_export


** Secuencia de Fases Inversa (SFI)
#+ATTR_LATEX: :height 0.45\textheight
[[file:figs/FasoresTrifasica_ACB.pdf]]
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
#+begin_export latex
\begin{align*}
  \overline{U}_A &= \frac{U}{\sqrt{3}}\phase{{\color{blue}\ang{-90}}}\\
  \overline{U}_B &= \frac{U}{\sqrt{3}}\phase{\ang{30}}\\
  \overline{U}_C &= \frac{U}{\sqrt{3}}\phase{\ang{150}}
\end{align*}
#+end_export

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.2
    :END:
[[file:figs/ReglaSFI.pdf]]
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
 #+begin_export latex
 \begin{align*}
   \overline{U}_{AB} &= U\phase{\ang{-120}}\\
   \overline{U}_{BC} &= U\phase{{\color{blue}\ang{0}}}\\
   \overline{U}_{CA} &= U\phase{\ang{120}}
 \end{align*}
 #+end_export
* Receptores
** Tipos de Receptores
*** Conexión
    - *Estrella* (punto común) Y
    - *Triángulo* $\triangle$

*** Impedancias
    - *Equilibrado* (las tres impedancias son idénticas en módulo *y* fase).
    - *Desequilibrado*


** Receptor en Estrella Equilibrado
[[file:figs/EstrellaEquilibrado.pdf]]

** Receptor en Estrella Equilibrado

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    
[[file:figs/EstrellaEquilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

 #+begin_export latex
 \begin{align*}
   \overline{I}_A &= \frac{\overline{U}_A}{\overline{Z}} = \frac{U_f}{Z}\phase{\ang{\pm 90} - \theta} \\
   \overline{I}_B &= \frac{\overline{U}_B}{\overline{Z}} = \frac{U_f}{Z}\phase{\ang{\mp 30} - \theta}\\
   \overline{I}_C &= \frac{\overline{U}_C}{\overline{Z}} = \frac{U_f}{Z}\phase{\ang{\mp 150} - \theta}
 \end{align*}
 #+end_export


 #+begin_export latex
 \[
   \boxed{|\overline{I}_A| = |\overline{I}_B| = |\overline{I}_C| = \frac{U_f}{Z}}
 \]
 #+end_export

 #+begin_export latex
 \[
   \overline{I}_A  + \overline{I}_B + \overline{I}_C + \overline{I}_N = 0
 \]
 #+end_export
 #+begin_export latex
\[
   \overline{I}_A  + \overline{I}_B + \overline{I}_C  = 0 \rightarrow \boxed{\overline{I}_N = 0}
\]
 #+end_export
** Receptor en Estrella Equilibrado
[[file:figs/EstrellaEquilibrado_SinNeutro.pdf]]

** Receptor en Triángulo Equilibrado
[[file:figs/TrianguloEquilibrado.pdf]]

** Receptor en Triángulo Equilibrado

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 [[file:figs/TrianguloEquilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

 #+begin_export latex
 \begin{align*}
   \overline{I}_{AB} &= \frac{\overline{U}_{AB}}{\overline{Z}} = \frac{U}{Z}\phase{\ang{\pm 120} - \theta} \\
   \overline{I}_{BC} &= \frac{\overline{U}_{BC}}{\overline{Z}} = \frac{U}{Z}\phase{0 - \theta}\\
   \overline{I}_{CA} &= \frac{\overline{U}_{CA}}{\overline{Z}} = \frac{U}{Z}\phase{\ang{\mp 120} - \theta}
 \end{align*}
 #+end_export

 #+begin_export latex
\[
   \overline{I}_{AB}  + \overline{I}_{BC} + \overline{I}_{CA}  = 0 
\]
 #+end_export

Corriente de Fase:
 #+begin_export latex
 \[
   \boxed{I_f = |\overline{I}_{AB}| = |\overline{I}_{BC}| = |\overline{I}_{CA}| = \frac{U}{Z}}
 \]
 #+end_export


** Receptor en Triángulo Equilibrado

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 [[file:figs/TrianguloEquilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

 #+begin_export latex
 \begin{align*}
   \overline{I}_A &= \overline{I}_{AB} - \overline{I}_{CA} = \sqrt{3} \cdot \frac{U}{Z}\phase{\ang{\pm 90} - \theta}\\
   \overline{I}_B &= \overline{I}_{BC} - \overline{I}_{AB} = \sqrt{3} \cdot \frac{U}{Z}\phase{\ang{\mp 30} - \theta}\\
   \overline{I}_C &= \overline{I}_{CA} - \overline{I}_{BC} = \sqrt{3} \cdot \frac{U}{Z}\phase{\ang{\mp 150} - \theta}\\
 \end{align*}
 #+end_export

Corriente de Línea:
 #+begin_export latex
 \[
   \boxed{I = |\overline{I}_A| = |\overline{I}_B| = |\overline{I}_C| = \sqrt{3} \cdot \frac{U}{Z}}
 \]
 #+end_export

 #+begin_export latex
 \[
   \boxed{I = \sqrt{3} \cdot I_f}
 \]
 #+end_export

** Receptor en Estrella Desequilibrado con Neutro

[[file:figs/EstrellaDesequilibrado.pdf]]

** Receptor en Estrella Desequilibrado con Neutro
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    
[[file:figs/EstrellaDesequilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

 #+begin_export latex
 \begin{align*}
   \overline{I}_A &= \frac{\overline{U}_A}{\overline{Z}_A}\\
   \overline{I}_B &= \frac{\overline{U}_B}{\overline{Z}_B}\\
   \overline{I}_C &= \frac{\overline{U}_C}{\overline{Z}_C}
 \end{align*}
 #+end_export

 #+begin_export latex
 \[
   \overline{I}_A  + \overline{I}_B + \overline{I}_C + \overline{I}_N = 0
 \]
 #+end_export
 #+begin_export latex
\[
   \overline{I}_A  + \overline{I}_B + \overline{I}_C  \neq 0 \rightarrow \boxed{\overline{I}_N \neq 0}
\]
 #+end_export

** Receptor en Estrella Desequilibrado sin Neutro
[[file:figs/EstrellaDesequilibrado_SinNeutro.pdf]]

#+begin_export latex
\[
\overline{U}_N \neq \overline{U}_{N'}
\]
#+end_export
** Receptor en Estrella con Carga Monofásica
#+ATTR_LATEX: :height 0.9\textheight
[[file:figs/Estrella_CargaMonofasica.pdf]]
** Receptor en Triángulo Desequilibrado
   #+ATTR_LATEX: :height 0.9\textheight
 file:figs/TrianguloDesequilibrado.pdf

** Receptor en Triángulo Desequilibrado
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.6
    :END:
    
[[file:figs/TrianguloDesequilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:

 #+begin_export latex
 \begin{align*}
   \overline{I}_{AB} &= \frac{\overline{U}_{AB}}{\overline{Z}_{AB}}\\
   \overline{I}_{BC} &= \frac{\overline{U}_{BC}}{\overline{Z}_{BC}}\\
   \overline{I}_{CA} &= \frac{\overline{U}_{CA}}{\overline{Z}_{CA}}
 \end{align*}
 #+end_export

 #+begin_export latex
 \begin{align*}
   \overline{I}_A &= \overline{I}_{AB} - \overline{I}_{CA}\\
   \overline{I}_B &= \overline{I}_{BC} - \overline{I}_{AB}\\
   \overline{I}_C &= \overline{I}_{CA} - \overline{I}_{BC}\\
 \end{align*}
 #+end_export

* Potencia en Sistemas Trifásicos

** Potencia Instantánea en Sistemas Equilibrados

   Supongamos un receptor equilibrado en estrella con SFD:

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    #+begin_export latex
  \begin{align*}
    u_A(t) &= \sqrt{2} U_f \cos(\omega t + \ang{90})\\
    u_B(t) &= \sqrt{2} U_f \cos(\omega t - \ang{30})\\
    u_C(t) &= \sqrt{2} U_f \cos(\omega t - \ang{150})
  \end{align*}
    #+end_export

    #+begin_export latex
  \begin{align*}
    i_A(t) &= \sqrt{2} I \cos(\omega t + \ang{90} - \theta)\\
    i_B(t) &= \sqrt{2} I \cos(\omega t - \ang{30} - \theta)\\
    i_C(t) &= \sqrt{2} I \cos(\omega t - \ang{150} - \theta)
  \end{align*}
    #+end_export

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
  #+begin_export latex
  \begin{align*}
    p_A(t) &= u_A(t) \cdot i_A(t)\\
    p_B(t) &= u_C(t) \cdot i_B(t)\\
    p_C(t) &= u_C(t) \cdot i_C(t)\\
    \\
    p(t) &= p_A(t) + p_B(t) + p_C(t)
  \end{align*}
    #+end_export

** Potencia Instantánea en Sistemas Equilibrados
   #+begin_export latex
   \begin{align*}
     p(t) &= \sqrt{2}U_f  \cos(\omega t + \ang{90}) \cdot \sqrt{2}I\cos(\omega t + \ang{90} - \theta) +\\
	  &+ \sqrt{2}U_f \cos(\omega t - \ang{30}) \cdot \sqrt{2}I \cos(\omega t - \ang{30} - \theta) +\\
	  &+ \sqrt{2}U_f \cos(\omega t - \ang{150}) \cdot \sqrt{2}I \cos(\omega t - \ang{150} - \theta)
   \end{align*}
   #+end_export
   #+begin_export latex
   \[
     \cos(\alpha) \cdot \cos(\beta) = \frac{1}{2} \cdot (\cos(\alpha + \beta) + \cos(\alpha - \beta))
   \]
   #+end_export
   #+begin_export latex
   \begin{align*}
     p(t) &= U_f I [{\color{gray}\cos(2 \omega t + \ang{180} -\theta)} + \cos(\theta)] +\\
	  &+ U_f I [{\color{gray}\cos(2 \omega t - \ang{60} - \theta)} + \cos(\theta)] +\\
	  &+ U_f I [{\color{gray}\cos(2 \omega t - \ang{300} - \theta)} + \cos(\theta)]
   \end{align*}
   #+end_export
   #+begin_export latex
   \[
     \boxed{p(t) = 3 \cdot U_f \cdot I \cdot \cos (\theta) = \sqrt{3} \cdot U \cdot I \cdot \cos (\theta)} 
   \]
   #+end_export

** Receptor en Estrella Equilibrado

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    
[[file:figs/EstrellaEquilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

 #+begin_export latex
 \begin{align*}
   P = 3 \cdot P_Z &= 3 \cdot U_Z I_Z \cos(\theta)\\
   Q = 3 \cdot Q_Z &= 3 \cdot U_Z I_Z \sin(\theta)
 \end{align*}

 \begin{align*}
   I_Z &= I\\
   U_Z &= U_F
 \end{align*}


 \begin{align*}
   P &= 3 U_F I \cos(\theta) = \sqrt{3} U I \cos(\theta)\\
   Q &= 3 U_F I \sin(\theta) = \sqrt{3} U I \sin(\theta)\\
   S &= \sqrt{P^2 + Q^2} =  \sqrt{3} U I
 \end{align*}
 #+end_export


** Receptor en Triángulo Equilibrado

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 [[file:figs/TrianguloEquilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

 #+begin_export latex
 \begin{align*}
   P = 3 \cdot P_Z &= 3 \cdot U_Z I_Z \cos(\theta)\\
   Q = 3 \cdot Q_Z &= 3 \cdot U_Z I_Z \sin(\theta)
 \end{align*}

 \begin{align*}
   I_Z &= I_F\\
   U_Z &= U
 \end{align*}


 \begin{align*}
   P &= 3 U I_F \cos(\theta) = \sqrt{3} U I \cos(\theta)\\
   Q &= 3 U I_F \sin(\theta) = \sqrt{3} U I \sin(\theta)\\
   S &= \sqrt{P^2 + Q^2} =  \sqrt{3} U I
 \end{align*}
 #+end_export

** Receptor en Estrella Desequilibrado
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    
[[file:figs/EstrellaDesequilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 #+begin_export latex
 \begin{align*}
   P &= P_A + P_B + P_C\\
   Q &= Q_A + Q_B + Q_C\\
   \overline{S} &= P + jQ
 \end{align*}
 #+end_export

** Receptor en Triángulo Desequilibrado
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.6
    :END:
    
[[file:figs/TrianguloDesequilibrado_Receptor.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
 #+begin_export latex
 \begin{align*}
   P &= P_{AB} + P_{BC} + P_{CA}\\
   Q &= Q_{AB} + Q_{BC} + Q_{CA}\\
   \overline{S} &= P + jQ
 \end{align*}
 #+end_export

** Comparativa Monofásica-Trifásica
Comparemos un sistema monofásico y un sistema trifásico (3H) que transmiten la *misma potencia activa* y funcionan a la *misma tensión entre líneas*.
#+begin_export latex
\[
U I_1 \cos\theta = P_1 = P_3 = \sqrt{3}U I_3 \cos\theta \rightarrow \boxed{I_1 = \sqrt{3} I_3}
\]
#+end_export
Las *pérdidas en la línea* deben ser *iguales* para salvar la *misma distancia*:
#+begin_export latex
\[
  2R_1I_1^2 = P_{1l} = P_{3l} = 3R_3I_3^2
\]
#+end_export
Sustituyendo la relación de corrientes y teniendo en cuenta la relación entre resistencia y sección:
#+begin_export latex
\[
  2\cdot R_1 \cdot 3I_3^2 = 3\cdot R_3 I_3^2 \rightarrow R_1 = \frac{1}{2} R_3 \rightarrow \boxed{S_1 = 2 \cdot S_3}
\]
#+end_export

Finalmente, la relación entre masas de conductor es:

#+begin_export latex
\[
  \frac{m_3}{m_1} = \frac{3 \cdot S_3}{2 \cdot S_1} = \boxed{\frac{3}{4}}
\]
#+end_export

* Compensación de Reactiva

** Objetivo 

- Sea un receptor *equilibrado* *inductivo* del que conocemos $P$, $Q$ y, por tanto, su factor de potencia $\cos \theta$.

- Para reducir la potencia reactiva del sistema debemos instalar un *banco de condensadores* que suministrarán una potencia reactiva $Q_c$.

- Como *resultado*, la potencia reactiva y el factor de potencia del sistema serán $Q' = Q - Q_c$ y $\cos\theta' > \cos \theta$.

- En trifásica existen dos posibilidades:
  - Conexión en triángulo: $C_\triangle$
  - Conexión en estrella: $C_Y$.

** Conexión en Triángulo

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 [[file:figs/CircuitoTrifasica_CompensacionReactiva.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
  #+BEGIN_EXPORT latex
  \begin{align*}
    Q &= P\tan\theta\\
    Q' &= P\tan\theta' =\\
      &= Q - Q_c\\
    Q_c &= 3 \cdot \omega C_\triangle \cdot U^2
  \end{align*}
  #+END_EXPORT
#+BEGIN_EXPORT latex
\[
  \boxed{C_\triangle = \frac{P(\tan \theta - \tan \theta')}{3\omega U^2}}
\]
#+END_EXPORT

** Conexión en Estrella
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
 [[file:figs/CircuitoTrifasicaY_CompensacionReactiva.pdf]]
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
  #+BEGIN_EXPORT latex
  \begin{align*}
    Q &= P\tan\theta\\
    Q' &= P\tan\theta' =\\
      &= Q - Q_c\\
    Q_c &= 3 \cdot \omega C_Y \cdot U_f^2
  \end{align*}
  #+END_EXPORT
#+BEGIN_EXPORT latex
\[
  \boxed{C_Y = \frac{P(\tan \theta - \tan \theta')}{\omega U^2}}
\]
#+END_EXPORT
** Comparación Estrella-Triángulo
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.55\textheight
 [[file:figs/CircuitoTrifasica_CompensacionReactiva.pdf]]
#+BEGIN_EXPORT latex
\[
  \boxed{C_\triangle = \frac{P(\tan \theta - \tan \theta')}{3 \omega U^2}}
\]
#+END_EXPORT

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.55\textheight
 [[file:figs/CircuitoTrifasicaY_CompensacionReactiva.pdf]]
#+BEGIN_EXPORT latex
\[
  \boxed{C_Y = \frac{P(\tan \theta - \tan \theta')}{\omega U^2}}
\]
#+END_EXPORT

\medskip

*** :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:

Dado que $C_Y = 3 \cdot C_\triangle$ la *configuración recomendada* es *triángulo*.
* Medida de Potencia en Sistemas Trifásicos
** Recordatorio: vatímetro
#+ATTR_LATEX: :height 0.6\textheight
 [[file:figs/vatimetro.pdf]]

*Vatímetro*: equipo de medida de 4 terminales (1 par para tensión, 1 par para corriente)

#+begin_export latex
\[
  \boxed{W = \Re(\overline{U} \cdot \overline{I}^*)}
\]
#+end_export
** Sistema de 4 Hilos

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.7
    :END:
    #+ATTR_LATEX: :height 0.85\textheight
    [[file:figs/Potencia4H.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.3
    :END:
    #+begin_export latex
    \begin{align*}
      W_1 &= \Re(\overline{U}_A \cdot \overline{I}_A^*) = P_A\\
      W_2 &= \Re(\overline{U}_B \cdot \overline{I}_B^*) = P_B\\
      W_3 &= \Re(\overline{U}_C \cdot \overline{I}_C^*) = P_C\\
    \end{align*}

    \[
      \boxed{P = W_1 + W_2 + W_3}
    \]
    #+end_export


** Sistema de 4 Hilos Equilibrado

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.6
    :END:
    #+ATTR_LATEX: :height 0.85\textheight
    [[file:figs/Potencia4H_Equilibrado.pdf]]
 
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :END:
    #+begin_export latex
    \[
      P_A = P_B = P_C
    \]
    
    \[
    \boxed{P = 3 \cdot W_1}
    \]
    #+end_export


** Sistema de 3 Hilos

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.7
    :END:
 [[file:figs/Potencia3H.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.3
    :END:
    Montaje de Aron
    #+begin_export latex
    \begin{align*}
      W_1 &= \Re(\overline{U}_{AC} \cdot \overline{I}^*_A)\\
      W_2 &= \Re(\overline{U}_{BC} \cdot \overline{I}^*_B)\\
      W_1 + W_2 &= ?
    \end{align*}
    #+end_export


** Sistema de 3 Hilos
Desarrollamos las dos expresiones usando corrientes de fase y obviando el operador $\Re$:
    #+begin_export latex
    \begin{align*}
      \overline{U}_{AC} \cdot \overline{I}^*_A &=   \overline{U}_{AC} \cdot (\overline{I}^*_{AB} - \overline{I}^*_{CA})\\
      \overline{U}_{BC} \cdot \overline{I}^*_B &=   \overline{U}_{BC} \cdot (\overline{I}^*_{BC} - \overline{I}^*_{AB})
    \end{align*}
    #+end_export
Sumamos las dos expresiones:
    #+begin_export latex
    \[
      \overline{U}_{AC} \cdot \overline{I}^*_A + \overline{U}_{BC} \cdot \overline{I}^*_B =   \overline{U}_{AC} \cdot \overline{I}^*_{AB} - \overline{U}_{AC} \cdot \overline{I}^*_{CA} + \overline{U}_{BC} \cdot \overline{I}^*_{BC} - \overline{U}_{BC} \cdot \overline{I}^*_{AB}
\]
    #+end_export
Y agrupamos, teniendo en cuenta que $\overline{U}_{AB} +\overline{U}_{BC} + \overline{U}_{CA} = 0$:
  #+begin_export latex
  \[
    \overline{U}_{CA} \cdot \overline{I}^*_{CA} + \overline{U}_{BC} \cdot \overline{I}^*_{BC} + (\overline{U}_{AC} \cdot \overline{I}^*_{AB}  - \overline{U}_{BC} \cdot \overline{I}^*_{AB}) = \overline{S}_{CA} + \overline{S}_{BC} + \overline{S}_{AB}
  \]
      #+end_export
Extrayendo la parte real de este resultado obtenemos:
  #+begin_export latex
  \[
    \Re(\overline{S}_{AB} + \overline{S}_{BC} + \overline{S}_{CA}) = P \rightarrow \boxed{W_1 + W_2 = P}
  \]
  #+end_export

** Sistema de 3 Hilos Equilibrado
Cuando el sistema es equilibrado, las lecturas individuales de los vatímetros tienen significado.


***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.7
    :END:
 [[file:figs/Potencia3H_Equilibrado_AB.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.3
    :END:

    #+begin_export latex
    \begin{align*}
      W_1 &= \Re(\overline{U}_{AC} \cdot \overline{I}^*_A) = ?\\
      W_2 &= \Re(\overline{U}_{BC} \cdot \overline{I}^*_B) = ?\\
    \end{align*}
    #+end_export


** Sistema de 3 Hilos Equilibrado

Supongamos SFD:

#+begin_export latex
\begin{align*}
  \overline{U}_{AC} &= - \overline{U}_{CA} = U\phase{\ang{-120} + \ang{180}} = U\phase{\ang{60}}\\
  \overline{I}_A &= I\phase{\ang{90} - \theta}\\
  \overline{U}_{AC} \cdot \overline{I}^*_A &= UI\phase{\theta - \ang{30}} \rightarrow   \boxed{W_1 = UI\cos(\theta - \ang{30})}
\end{align*}
#+end_export

#+begin_export latex
\begin{align*}
  \overline{U}_{BC} &=  U\phase{0}\\
  \overline{I}_B &= I\phase{\ang{-30} - \theta}\\
  \overline{U}_{BC} \cdot \overline{I}^*_B &= UI\phase{\theta + \ang{30}} \rightarrow   \boxed{W_2 = UI\cos(\theta + \ang{30})}
\end{align*}
#+end_export

** Sistema de 3 Hilos Equilibrado

Desarrollamos los dos cosenos:
#+begin_export latex
\begin{align*}
  \cos(\ang{30} - \theta) &= \cos\ang{30}\cos\theta + \sin\ang{30}\sin\theta\\
  \cos(\ang{30} + \theta) &= \cos\ang{30}\cos\theta - \sin\ang{30}\sin\theta
\end{align*}
#+end_export

Si sumamos obtenemos la potencia activa:
#+begin_export latex
\[
  \boxed{W_1 + W_2 = \sqrt{3} U I \cos\theta = P}
\]
#+end_export

Si restamos obtenemos la potencia reactiva (salvo un factor):
#+begin_export latex
\[
  \boxed{W_1 - W_2 = U I \sin\theta = \frac{Q}{\sqrt{3}}}
\]
#+end_export

Por tanto, también podemos calcular el ángulo del receptor:
#+begin_export latex
\[
  \boxed{\tan\theta = \sqrt{3} \frac{W_1 - W_2}{W_1 + W_2}}
\]
#+end_export

** Sistema de 3 Hilos Equilibrado
Repetimos el desarrollo con SFI:

#+begin_export latex
\begin{align*}
  \overline{U}_{AC} &= - \overline{U}_{CA} = U\phase{\ang{120} + \ang{180}} = U\phase{\ang{-60}}\\
  \overline{I}_A &= I\phase{\ang{-90} - \theta}\\
  \overline{U}_{AC} \cdot \overline{I}^*_A &= UI\phase{\theta + \ang{30}} \rightarrow   \boxed{W_1 = UI\cos(\theta {\color{red}+} \ang{30})}
\end{align*}

#+end_export
#+begin_export latex
\begin{align*}
  \overline{U}_{BC} &=  U\phase{0}\\
  \overline{I}_B &= I\phase{\ang{30} - \theta}\\
  \overline{U}_{BC} \cdot \overline{I}^*_B &= UI\phase{\theta - \ang{30}} \rightarrow \boxed{W_2 = UI\cos(\theta {\color{red}-} \ang{30})}
\end{align*}
#+end_export
#+begin_export latex
\[
  \boxed{W_1 + W_2 = \sqrt{3} U I \cos\theta = P}
\]
#+end_export
#+begin_export latex
\[
  \boxed{W_1 - W_2 = {\color{red}-} U I \sin\theta = {\color{red}-} \frac{Q}{\sqrt{3}}}
\]
#+end_export



** Sistema de 3 Hilos Equilibrado

#+ATTR_LATEX: :height 0.3\textheight
 [[file:figs/Potencia3H_Equilibrado_AB.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
SFD
    #+begin_export latex
    \begin{align*}
      W_1 &= UI\cos(\theta {\color{red}-} \ang{30})\\
      W_2 &= UI\cos(\theta {\color{red}+} \ang{30})
    \end{align*}
    \begin{align*}
      P &= W_1 + W_2\\
      Q &= \sqrt{3}({\color{red}W_1 - W_2}) \\
      \tan\theta &= \sqrt{3} \frac{{\color{red}W_1 - W_2}}{W_1 + W_2}
    \end{align*}
    #+end_export
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
SFI
    #+begin_export latex
    \begin{align*}
      W_1 &= UI\cos(\theta {\color{red}+} \ang{30})\\
      W_2 &= UI\cos(\theta {\color{red}-} \ang{30})
    \end{align*}
    \begin{align*}
      P &= W_1 + W_2\\
      Q &= \sqrt{3}({\color{red}W_2 - W_1}) \\
      \tan\theta &= \sqrt{3} \frac{{\color{red}W_2 - W_1}}{W_1 + W_2}
    \end{align*}
#+end_export
** Otras conexiones: 3H SFD
   :PROPERTIES:
   :beamer_opt: plain
   :END:

   #+begin_export latex
   \[
     \boxed{(ABC) :: A \triangleright B \triangleright C \Longrightarrow \{AB, BC, CA\}}
   \]
   #+end_export
    #+begin_export latex
    \begin{align*}
      W_1 &= UI\cos(\theta - \ang{30}) & P &= W_1 + W_2\\
      W_2 &= UI\cos(\theta + \ang{30}) & Q &= \sqrt{3}(W_1 - W_2)
    \end{align*}
    #+end_export
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
  [[file:figs/Potencia3H_Equilibrado_AB.pdf]]
  #+begin_export latex
  \begin{align*}
    W_1&: AC \notin SFD\\
    W_2&: BC \in SFD\\
  \end{align*}
  #+end_export
*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
  [[file:figs/Potencia3H_Equilibrado_BC.pdf]]
  #+begin_export latex
  \begin{align*}
    W_1&: BA \notin SFD\\
    W_2&: CA \in SFD\\
  \end{align*}
  #+end_export

*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
  [[file:figs/Potencia3H_Equilibrado_CA.pdf]]
  #+begin_export latex
  \begin{align*}
    W_1&: CB \notin SFD\\
    W_2&: AB \in SFD\\
  \end{align*}
  #+end_export

** Otras conexiones: 3H SFI
   :PROPERTIES:
   :beamer_opt: plain
   :END:

   #+begin_export latex
   \[
     \boxed{(ACB) :: A \triangleright C \triangleright B \Longrightarrow \{AC, CB, BA\}}
   \]
   #+end_export
    #+begin_export latex
    \begin{align*}
      W_1 &= UI\cos(\theta - \ang{30}) & P &= W_1 + W_2\\
      W_2 &= UI\cos(\theta + \ang{30}) & Q &= \sqrt{3}(W_1 - W_2)
    \end{align*}
    #+end_export
***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
  [[file:figs/Potencia3H_Equilibrado_AB_SFI.pdf]]
  #+begin_export latex
  \begin{align*}
    W_1&: BC \notin SFI\\
    W_2&: AC \in SFI\\
  \end{align*}
  #+end_export
*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
  [[file:figs/Potencia3H_Equilibrado_BC_SFI.pdf]]
  #+begin_export latex
  \begin{align*}
    W_1&: CA \notin SFI\\
    W_2&: BA \in SFI\\
  \end{align*}
  #+end_export

*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
  [[file:figs/Potencia3H_Equilibrado_CA_SFI.pdf]]
  #+begin_export latex
  \begin{align*}
    W_1&: AB \notin SFI\\
    W_2&: CB \in SFI\\
  \end{align*}
  #+end_export


** Medida de Reactiva con un Vatímetro
Cuando el sistema está equilibrado, es posible medir la potencia reactiva con un único vatímetro. 

Supongamos *SFD*:

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
[[file:figs/Reactiva3H_A-BC.pdf]]

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    #+begin_export latex
    \[
      W = \Re(\overline{U}_{BC} \cdot \overline{I}_A^*)
    \]
    #+end_export
    #+begin_export latex
    \begin{align*}
      \overline{U}_{BC} &= U\phase{0}\\
      \overline{I}_A &= I\phase{\ang{90} - \theta}
    \end{align*}
    #+end_export
    #+begin_export latex
    \begin{align*}
      W &= \Re(U I \phase{\theta - \ang{90}}) = \\
	&= U I \sin(\theta)
    \end{align*}
    #+end_export
    #+begin_export latex
    \[
      \boxed{W = \frac{Q}{\sqrt{3}}}
    \]
    #+end_export

** Conexiones para medida de reactiva

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
    #+ATTR_LATEX: :height 0.25\textheight
    [[file:figs/Reactiva3H_A-BC.pdf]]
    #+begin_export latex
    \[
      W = \Re(\overline{U}_{BC} \cdot \overline{I}_A^*)
    \]
    \begin{align*}
      BC &\in SFD\\
      BC &\notin SFI
    \end{align*}
    #+end_export
*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
    #+ATTR_LATEX: :height 0.25\textheight
    [[file:figs/Reactiva3H_B-CA.pdf]]
    #+begin_export latex
    \[
      W = \Re(\overline{U}_{CA} \cdot \overline{I}_B^*)
    \]
    \begin{align*}
      CA &\in SFD\\
      CA &\notin SFI
    \end{align*}
    #+end_export
*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
    #+ATTR_LATEX: :height 0.25\textheight
    [[file:figs/Reactiva3H_C-AB.pdf]]
    #+begin_export latex
    \[
      W = \Re(\overline{U}_{AB} \cdot \overline{I}_C^*)
    \]
    \begin{align*}
      AB &\in SFD\\
      AB &\notin SFI
    \end{align*}
    #+end_export
***                                                         :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
    #+begin_export latex
    \begin{align*}
    SFD &\rightarrow \boxed{W = \frac{Q}{\sqrt{3}}}\\
    SFI &\rightarrow \boxed{W =  - \frac{Q}{\sqrt{3}}}
    \end{align*}
    #+end_export

** Conexiones para medida de reactiva

***                                                                   :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
    #+ATTR_LATEX: :height 0.25\textheight
    [[file:figs/Reactiva3H_A-CB.pdf]]
    #+begin_export latex
    \[
      W = \Re(\overline{U}_{CB} \cdot \overline{I}_A^*)
    \]
    \begin{align*}
      CB &\notin SFD\\
      CB &\in SFI
    \end{align*}
    #+end_export
*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
    #+ATTR_LATEX: :height 0.25\textheight
    [[file:figs/Reactiva3H_B-AC.pdf]]
    #+begin_export latex
    \[
      W = \Re(\overline{U}_{AC} \cdot \overline{I}_B^*)
    \]
    \begin{align*}
      AC &\notin SFD\\
      AC &\in SFI
    \end{align*}
    #+end_export
*** 
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
    #+ATTR_LATEX: :height 0.25\textheight
    [[file:figs/Reactiva3H_C-BA.pdf]]
    #+begin_export latex
    \[
      W = \Re(\overline{U}_{BA} \cdot \overline{I}_C^*)
    \]
    \begin{align*}
      BA &\notin SFD\\
      BA &\in SFI
    \end{align*}
    #+end_export
***                                                         :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:
    #+begin_export latex
    \begin{align*}
    SFD &\rightarrow \boxed{W = - \frac{Q}{\sqrt{3}}}\\
    SFI &\rightarrow \boxed{W = \frac{Q}{\sqrt{3}}}
    \end{align*}
    #+end_export


