#+TITLE: Fundamentos. Circuitos de Corriente Continua.
#+SUBTITLE: Teoría de Circuitos
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: 
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:3

* Conceptos Fundamentales
** Teoría de Circuitos
*** 
Este curso está dedicado al *análisis* de *circuitos eléctricos* *lineales* de *parámetros concentrados*.
*** Circuito Eléctrico

Un *circuito eléctrico* es un conjunto de componentes eléctricos interconectados mediante conductores que crean un camino cerrado por el que puede circular corriente eléctrica. 

Un circuito eléctrico puede incluir:
- *elementos activos* (generadores), que entregan potencia al circuito
- *elementos pasivos* (receptores), que consumen o almacenan la potencia que circula.

*** Análisis y Diseño
 El *análisis* (o resolución) de un circuito eléctrico existente persigue determinar sus condiciones de funcionamiento:
 1. Definir las ecuaciones correspondientes al circuito,
 2. Obtener los valores de determinadas variables importantes a partir de dichas ecuaciones. 

 El *diseño* (o síntesis) de un circuito eléctrico tiene como objetivo definir el circuito eléctrico, es decir, determinar los componentes necesarios y su interconexión, para obtener unas condiciones de funcionamiento.
*** Sistemas lineales

Todos los circuitos eléctricos que se estudian en este curso se comportan como *sistemas lineales*: 

  - $f(x + y) = f(x) + f(y)$
    
    La respuesta $f$ a la suma de dos entradas $x$ e $y$ es igual a la suma de la respuesta individual a cada una de las entradas
  - $f(k \cdot x) = k \cdot f(x)$
    
    La respuesta a una entrada que está multiplicada por un factor de escala $k$ es igual a multiplicar por este factor a la respuesta a la entrada.

*** La linealidad es una aproximación de la realidad

  - Estas propiedades simplifican el tratamiento de los circuitos, y *permiten aplicar técnicas de resolución de ecuaciones lineales*.
  - La linealidad es una *aproximación de la realidad* que no puede aplicarse de manera indiscriminada a cualquier componente y en cualquier condición.
  - En particular, los *dispositivos electrónicos* como diodos o transistores tienen un *comportamiento* marcadamente *no lineal*, de forma que los circuitos que los contienen no pueden analizarse directamente con las técnicas que aquí se exponen sin realizar previamente aproximaciones de su funcionamiento.

*** Parámetros concentrados
- Los circuitos eléctricos reales ocupan espacio, las máquinas generadoras y los receptores tienen grandes dimensiones, y los cables conductores se extienden a lo largo de longitudes variopintas.
- Sin embargo, el análisis de circuitos no toma en consideración las propiedades espaciales de los circuitos ni de sus componentes, sino que los confina a elementos puntuales con un modelo de *parámetros concentrados*.
- Por ejemplo, un conductor real de $\SI{100}{\meter}$ se representará habitualmente como un conductor ideal con una resistencia en su punto medio.
*** Simplificación de las ecuaciones de Maxwell

- Este tratamiento es una simplificación de las ecuaciones del electromagnetismo de Maxwell
- Es aplicable únicamente cuando las dimensiones del circuito real son inferiores a la longitud de onda de la señal que circula por el circuito.
- Por ejemplo:
  - A la frecuencia de $\SI{50}{\hertz}$, habitual en sistemas eléctricos industriales, la longitud de onda de la señal es de $\SI{6000}{\kilo\meter}$.
  - A la frecuencia de $\SI{2.6}{\giga\hertz}$, característica de la telefonía 4G, la longitud de onda se reduce a $\SI{11.5}{\centi\meter}$. 


** Variables
*** Tensión Eléctrica
El *potencial eléctrico en un punto*, $v(t)$,  es la energía potencial que tiene una carga unitaria en ese punto debida al campo eléctrico. 

#+ATTR_LATEX: :height 0.3\textheight
[[file:figs/tension_puntos.pdf]]

La *tensión o diferencia de potencial entre dos puntos* A y B, $u_{AB}(t)$, es el trabajo realizado por el campo eléctrico al desplazar una carga unitaria entre esos puntos. 

\begin{equation*}
  u_{AB}(t) = v_A(t) - v_B(t) = \frac{dW_{e}}{dq}
\end{equation*}

La *unidad* de la tensión eléctrica es el *voltio* (V).

*** La trayectoria no importa

Dado que el campo eléctrico es *conservativo*, la diferencia de potencial entre A y B *no depende de la trayectoria* seguida para realizar el desplazamiento, sino únicamente del potencial existente en cada uno de los puntos. 

#+ATTR_LATEX: :height 0.6\textheight
[[file:figs/diagrama_tension.pdf]]

*** El signo depende del sentido

Aunque la trayectoria no sea relevante para el cálculo de la tensión, siempre hay que tener en cuenta el *sentido del desplazamiento*. 

#+ATTR_LATEX: :height 0.4\textheight
[[file:figs/sentido_tension.pdf]]

Así, si el movimiento se produce desde B hasta A obtenemos el signo contrario al anterior resultado:

\begin{equation*}
  u_{BA} = v_B - v_A = - u_{AB} 
\end{equation*}

*** Corriente Eléctrica

Se define la *intensidad de la corriente eléctrica* como la variación de la carga $q(t)$ que atraviesa la sección transversal de un conductor por unidad de tiempo:

\begin{equation*}
  i(t)=\frac{dq(t)}{dt}
\end{equation*}

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/seccion_conductor.pdf]]

La corriente eléctrica se produce por el *movimiento de los electrones libres* que fluyen por el conductor. Sin embargo, por razones históricas, el *convenio* que se se emplea considera como sentido de la corriente el debido al *movimiento de las cargas positivas*.

La *unidad* de la corriente es el *amperio* (A).

*** Potencia Eléctrica

La *potencia eléctrica* es la variación del trabajo del campo eléctrico por unidad de tiempo:

\begin{equation*}
  p(t)=\frac{dW_{e}}{dt}
\end{equation*}

Esta definición genérica puede relacionarse con las anteriores variables:

\begin{align*}
  p(t) &= \frac{dW_e}{dq} \cdot \frac{dq(t)}{dt}\\
       &= v(t)\cdot i(t)
\end{align*}

La *unidad* de la potencia eléctrica es el *vatio* (W).

*** Signo de la potencia eléctrica

Para determinar el *signo de la potencia eléctrica* hay que tener en consideración los signos de las variables de las que depende, la tensión y la corriente. 
- Cuando las flechas de ambas variables tienen el *mismo sentido* la potencia eléctrica es *positiva*
- Cuando las flechas tienen *sentidos opuestos* la potencia eléctrica es *negativa*. 

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/signo_potencia.pdf]]

*** Receptores y Generadores
Es habitual *interpretar* este resultado en términos de potencia absorbida o potencia entregada. 
- Un *circuito receptor absorbe potencia* y la corriente /entra/ por el terminal de mayor potencial,
- Un *circuito generador entrega potencia* y la corriente /sale/ por el terminal de mayor potencial.

#+ATTR_LATEX: :height 0.5\textheight
[[file:figs/receptor_generador.pdf]]

*** Potencia y Energía

-  Energía :: es la capacidad para realizar un trabajo.

   Unidades Wh, kWh

   1 kWh = 3.6 MJ

-  Potencia :: es la cantidad de trabajo efectuado /por unidad de
   tiempo/.

   Unidades W, kW

*** Corriente Continua y Corriente Alterna

- Corriente Continua ($\frac{d}{dt} = 0$)
#+ATTR_LATEX: :width \textwidth
[[file:figs/continua.pdf]]

- Corriente Alterna ($\frac{d}{dt} \neq 0$)
#+ATTR_LATEX: :width \textwidth
[[file:figs/sin.pdf]]

* Elementos circuitales

** Elementos Pasivos
*** Resistencia

-  *Ley de Ohm*: una resistencia provoca una *diferencia de potencial* entre sus terminales *directamente proporcional* a su corriente: *resistencia* (Ohmios, [\Omega])
#+BEGIN_EXPORT latex
\[
u(t) = R \cdot i(t)
\]
#+END_EXPORT   
- *Criterio de Signos*: la tensión es positiva en el terminal por el que entra la corriente (las flechas de tensión y corriente tienen el mismo sentido).
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Resistencia.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Resistencia_Flecha.pdf]]

*** Resistividad
-  El valor de la resistencia depende de la *resistividad del material* (\rho), de la *sección* ($S$), y de la
   longitud ($l$):
#+begin_export latex
\begin{equation*}
  R = \rho \cdot \frac{l}{S}
\end{equation*}
#+end_export

- La *sección* se expresa en $\si{\milli\meter\squared}$.

- La *resistividad* depende del material conductor y de la temperatura ambiente:

  - Cobre a 20ºC: $\SI{17.24}{\ohm\milli\meter\squared\per\meter}$.

*** Cortocircuito y Circuito Abierto
- Cortocircuito: resistencia nula (tensión nula)

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Cortocircuito.pdf]]

- Circuito abierto: resistencia infinita (corriente nula).

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/CircuitoAbierto.pdf]]

*** Ley de Joule

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Resistencia.pdf]]

- *Ley de Joule*: una resistencia disipa energía eléctrica produciendo *calor*.
#+BEGIN_EXPORT latex
\[
p(t)=R\cdot i^{2}(t)
\]
#+END_EXPORT


*** Bobina o inductancia

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Bobina.pdf]]

-  Cuando una corriente oscilante atraviesa un conductor arrollado alrededor de un núcleo, se produce una *tensión inducida que se opone a esta corriente* (ley de Faraday y Lenz)

-  La tensión en sus terminales es directamente proporcional al cambio de la corriente: coeficiente de autoinducción o *inductancia* (Henrios [H]).
   
#+BEGIN_EXPORT latex
\[
u_L(t)=L\cdot\frac{di(t)}{dt}
\]
#+END_EXPORT

*** Bobina o inductancia

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Bobina.pdf]]

-  Almacena *energía magnética*.

#+begin_export latex
\[
  E_L(t) = \int_{-\infty}^t u(\tau) \cdot i(\tau) d\tau = \frac{1}{2} \cdot L \cdot i^2(t)
\]
#+end_export
-  En circuitos de corriente continua es un cortocircuito.

#+begin_export latex
\begin{equation*}
  \frac{di(t)}{dt} = 0 \Rightarrow U_L = 0
\end{equation*}
#+end_export

*** Condensador

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Condensador.pdf]]

- Un *condensador* está formado por dos placas metálicas separadas por una capa dieléctrica. Al aplicar tensión se produce una *separación de cargas opuestas* que se *acumulan* en cada placa.

- La *carga acumulada* en un instante es *proporcional* a la *diferencia de potencial* en ese instante: *capacidad* (Faradios [F]).

#+BEGIN_EXPORT latex
\[
q(t) = C \cdot u(t)
\]
#+END_EXPORT

-  En el proceso de carga se produce una corriente eléctrica entre las dos placas.
#+BEGIN_EXPORT latex
\[
i_C(t)=\frac{dq(t)}{d(t)}=C\frac{du(t)}{dt}
\]
#+END_EXPORT


*** Condensador

#+ATTR_LATEX: :height 0.2\textheight
[[file:figs/Condensador.pdf]]

- Un condensador almacena *energía eléctrica*

#+begin_export latex
\[
  E_c(t) = \int_{-\infty}^t u(\tau) \cdot i(\tau) d\tau = \frac{1}{2} \cdot C \cdot u^2(t)
\]
#+end_export

-  En un circuito de corriente continua se comporta como un circuito abierto.

\begin{equation*}
  \frac{du(t)}{dt} = 0 \Rightarrow I_c = 0
\end{equation*}

** Elementos Activos

*** Generadores de Tensión y Corriente

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.6\textheight
 [[file:figs/FuenteTensionIdealDC.pdf]]
 Un *generador de tensión ideal* impone la tensión a la salida (/la corriente depende del circuito/)

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.6\textheight
 [[file:figs/FuenteCorrienteIdeal.pdf]]
 Un *generador de corriente ideal* impone la corriente a la salida (/la tensión depende del circuito/)

*** Generador Real
Los generadores reales tienen pérdidas que se modelan con una resistencia en *serie* (generador de tensión) o en *paralelo* (generador de corriente)

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.7\textheight
 file:figs/FuenteTensionRealDC.pdf
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.7\textheight
 file:figs/FuenteCorrienteRealDC.pdf


* Leyes de Kirchhoff

** Definiciones
*** Nudo, rama, malla
  - Nudo :: unión de *3* o más conductores.
  - Rama :: elementos conectados entre dos nudos consecutivos.
  - Lazo :: conjunto de ramas que forman un camino cerrado.
  - Malla :: lazo que no contiene ningún otro en su interior.

#+ATTR_LATEX: :height 0.5\textheight
file:figs/mallas.pdf

*** Ley de Kirchhoff de las Corrientes (LKC)
- La *LKC* es el principio de conservación de la carga aplicado a los circuitos eléctricos.

- *LKC*: la suma de las corrientes que llegan a un nudo es igual a la suma de las que salen.

  - Las lineas de corriente son cerradas (o solenoidales).

#+ATTR_LATEX: :height 0.4\textheight
[[file:figs/LKC_FM.pdf]]
#+BEGIN_EXPORT latex
\[
i_1(t) - i_2(t) + i_3(t) - i_4(t) + i_5(t) = 0
\]
#+END_EXPORT

*** Ley de Kirchhoff de los Voltajes (LKV)
- La *LKV* es el principio de conservación de la energía aplicado a los circuitos eléctricos.

- *LKV*: la suma (con signo) de las tensiones a lo largo de un camino cerrado (circuito) es cero.

  - La energía producida por un generador es consumida por los receptores del circuito para producir trabajo (mecánico, químico, etc.) o calor.

#+ATTR_LATEX: :height 0.4\textheight
[[file:figs/LKV_FM.pdf]]
#+BEGIN_EXPORT latex
\[
u_3(t) + u_4 (t) - u_5 (t) - u_1 (t) - u_2 (t)  = 0
\]
#+END_EXPORT

** Asociación de Elementos

*** Conexión en serie

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:figs/AsociacionSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

Un conjunto de elementos están asociados en serie cuando circula la misma corriente por todos ellos.
#+begin_export latex
\begin{align*}
  u_1(t) &= R_1 \cdot i(t)\\
  u_2(t) &= R_2 \cdot i(t)\\
  u_3(t) &= R_3 \cdot i(t)
\end{align*}
#+end_export
*** Conexión en serie
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:figs/AsociacionSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

Aplicando LKV:
#+begin_export latex
\begin{equation*}
  u(t) = u_1(t) + u_2(t) + u_3(t)
\end{equation*}
#+end_export

Sacando $i(t)$ como factor común:
#+begin_export latex
\begin{equation*}
  u(t) = i(t) \cdot (R_1 + R_2 + R_3)
\end{equation*}
#+end_export

Definimos la resistencia equivalente de la conexión serie:
#+begin_export latex
\begin{align*}
  \Aboxed{R_s &= \sum_{i = 1}^n R_i}\\
  u(t) &= R_s \cdot i(t)
\end{align*}
#+end_export

*** Divisor de Tensión
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:figs/AsociacionSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

De las ecuaciones anteriores tenemos:
#+begin_export latex
\begin{align*}
  i(t) &= \frac{u(t)}{R_1 + R_2 + R_3}\\
  u_3(t) &= R_3 \cdot i(t)\\
\end{align*}
#+end_export

Por tanto, la tensión parcial $u_3(t)$ se puede expresar en función de la tensión total $u(t)$: 
#+begin_export latex
\begin{equation*}
  u_3(t) = u(t) \cdot \frac{R_3}{R_1 + R_2 + R_3}  
\end{equation*}
#+end_export

En general:
#+begin_export latex
\begin{equation*}
  \boxed{u_o(t) = u(t) \cdot \frac{R_o}{R_s}}
\end{equation*}
#+end_export
*** Conexión en serie de inductancias
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:figs/BobinasSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

#+begin_export latex
\begin{align*}
  u_1(t) &= L_1 \cdot \frac{di(t)}{dt}\\
  u_2(t) &= L_2 \cdot \frac{di(t)}{dt}\\
  u_3(t) &= L_3 \cdot \frac{di(t)}{dt}\\
\end{align*}
#+end_export

#+begin_export latex
\begin{align*}
  \Aboxed{L_s &= \sum_{i = 1}^n L_i}\\
  u(t) &= L_s \cdot \frac{di(t)}{dt}
\end{align*}
#+end_export

*** Conexión en serie de condensadores
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:figs/CondensadoresSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

#+begin_export latex
\begin{align*}
  i_1(t) &= C_1 \cdot \frac{du(t)}{dt}\\
  i_2(t) &= C_2 \cdot \frac{du(t)}{dt}\\
  i_3(t) &= C_3 \cdot \frac{du(t)}{dt}\\
\end{align*}
#+end_export

#+begin_export latex
\begin{align*}
  \Aboxed{\frac{1}{C_s} &= \sum_{i = 1}^n \frac{1}{C_i}}\\
  i(t) &= C_s \cdot \frac{du(t)}{dt}
\end{align*}
#+end_export

*** Conexión en paralelo

Un conjunto de elementos están asociados en paralelo cuando están sometidos a la misma diferencia de potencial.
#+ATTR_LATEX: :height 0.45\textheight
[[file:figs/AsociacionParalelo.pdf]]

#+begin_export latex
\begin{align*}
  i_1(t) &= u(t)/R_1\\
  i_2(t) &= u(t)/R_2\\
  i_3(t) &= u(t)/R_3
\end{align*}
#+end_export
*** Conexión en paralelo
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
[[file:figs/AsociacionParalelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:

Aplicando LKC:
#+begin_export latex
\begin{equation*}
  i(t) = i_1(t) + i_2(t) + i_3(t)
\end{equation*}
#+end_export

Sacando $u(t)$ como factor común:
#+begin_export latex
\begin{equation*}
  i(t) = u(t) \cdot (\frac{1}{R_1} + \frac{1}{R_2} + \frac{1}{R_3})
\end{equation*}
#+end_export

Definimos la resistencia equivalente de la conexión paralelo:
#+begin_export latex
\begin{align*}
  \Aboxed{\frac{1}{R_p} &= \sum_{i = 1}^n \frac{1}{R_i}}\\
  u(t) &= R_p \cdot i(t)
\end{align*}
#+end_export
*** Dos resistencias en paralelo

En el caso concreto de *dos* resistencias en paralelo ...
#+begin_export latex
\begin{equation*}
  \frac{1}{R_p} = \frac{1}{R_1} + \frac{1}{R_2}
\end{equation*}
#+end_export
... la expresión es:
#+begin_export latex
\begin{equation*}
  \boxed{R_p = \frac{R_1 \cdot R_2}{R_1 + R_2}}
\end{equation*}
#+end_export

*** Conductancia

Para facilitar las operaciones es conveniente utilizar el inverso de la resistencia:

#+begin_export latex
\begin{equation*}
  G = \frac{1}{R}
\end{equation*}
#+end_export

Así, en lugar de...
#+begin_export latex
\begin{align*}
  \frac{1}{R_p} &= \sum_{i = 1}^n \frac{1}{R_i}\\
  u(t) &= R_p \cdot i(t)
\end{align*}
#+end_export

... podemos escribir:
#+begin_export latex
\begin{align*}
  \Aboxed{G_p &= \sum_{i = 1}^n G_i}\\
  i(t) &= G_p \cdot u(t)
\end{align*}
#+end_export

*** Divisor de corriente
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
[[file:figs/AsociacionParalelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:

De las ecuaciones anteriores tenemos (usando conductancia):
#+begin_export latex
\begin{align*}
  u(t) &= \frac{i(t)}{G_1 + G_2 + G_3}\\
  i_3(t) &= G_3 \cdot u(t)\\
\end{align*}
#+end_export

Por tanto, la corriente parcial $i_3(t)$ se puede expresar en función de la corriente total $i(t)$: 
#+begin_export latex
\begin{equation*}
  i_3(t) = i(t) \cdot \frac{G_3}{G_1 + G_2 + G_3}  
\end{equation*}
#+end_export

En general:
#+begin_export latex
\begin{equation*}
  \boxed{i_o(t) = i(t) \cdot \frac{G_o}{G_p}}
\end{equation*}
#+end_export

*** Conexión en paralelo de inductancias
#+ATTR_LATEX: :height 0.45\textheight
[[file:figs/BobinasParalelo.pdf]]

****  :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

#+begin_export latex
\begin{align*}
  u(t) &= L_1 \cdot \frac{di_1(t)}{dt}\\
  u(t) &= L_2 \cdot \frac{di_2(t)}{dt}\\
  u(t) &= L_3 \cdot \frac{di_3(t)}{dt}\\
\end{align*}
#+end_export
****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  \Aboxed{\frac{1}{L_p} &= \sum_{i = 1}^n \frac{1}{L_i}}\\
  u(t) &= L_p \cdot \frac{di(t)}{dt}
\end{align*}
#+end_export

*** Conexión en paralelo de condensadores

#+ATTR_LATEX: :height 0.45\textheight
[[file:figs/CondensadoresParalelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  i_1(t) &= C_1 \cdot \frac{du(t)}{dt}\\
  i_2(t) &= C_2 \cdot \frac{du(t)}{dt}\\
  i_3(t) &= C_3 \cdot \frac{du(t)}{dt}\\
\end{align*}
#+end_export
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  \Aboxed{C_p &= \sum_{i = 1}^n C_i}\\
  i(t) &= C_p \cdot \frac{du(t)}{dt}
\end{align*}
#+end_export

** Generadores

*** Ecuación del generador

Los generadores reales tienen pérdidas que se modelan con una resistencia en *serie* (generador de tensión) o en *paralelo* (generador de corriente)

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 file:figs/FuenteTensionRealDC.pdf
#+begin_export latex
\[
  U_{AB} = \epsilon_g - R_{\epsilon_g} \cdot I
\]
#+end_export
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 file:figs/FuenteCorrienteRealDC.pdf
#+begin_export latex
\[
  I = I_g - \frac{U_{AB}}{R_{I_g}}
\]
#+end_export


*** Equivalencia de Fuentes
Sólo es posible establecer equivalencia entre *fuentes reales*.
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 file:figs/FuenteTensionRealDC.pdf
#+begin_export latex
\[
  U_{AB} = \epsilon_g - R_{\epsilon_g} \cdot I
\]
#+end_export
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
    #+begin_export latex
    \begin{align*}
      R_g &= R_{\epsilon_g} = R_{I_g}\\
      \epsilon_g &= R_g \cdot I_g\\
      I_g &= \frac{\epsilon_g}{R_g}
    \end{align*}
    #+end_export
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.33
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 file:figs/FuenteCorrienteRealDC.pdf
#+begin_export latex
\[
  I = I_g - \frac{U_{AB}}{R_{I_g}}
\]
#+end_export


* Métodos de Análisis

** Método de las mallas

** Método de los nudos
