#+TITLE: Fundamentos. Circuitos de Corriente Continua.
#+SUBTITLE: Teoría de Circuitos
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: 
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:3

* Conceptos Fundamentales
** Teoría de Circuitos
*** 
Este curso está dedicado al *análisis* de *circuitos eléctricos* *lineales* de *parámetros concentrados*.
*** Circuito Eléctrico

Un *circuito eléctrico* es un conjunto de componentes eléctricos interconectados mediante conductores que crean un camino cerrado por el que puede circular corriente eléctrica. 

Un circuito eléctrico puede incluir:
- *elementos activos* (generadores), que entregan potencia al circuito
- *elementos pasivos* (receptores), que consumen o almacenan la potencia que circula.

*** Análisis y Diseño
 El *análisis* (o resolución) de un circuito eléctrico existente persigue determinar sus condiciones de funcionamiento:
 1. Definir las ecuaciones correspondientes al circuito,
 2. Obtener los valores de determinadas variables importantes a partir de dichas ecuaciones. 

 El *diseño* (o síntesis) de un circuito eléctrico tiene como objetivo definir el circuito eléctrico, es decir, determinar los componentes necesarios y su interconexión, para obtener unas condiciones de funcionamiento.
*** Sistemas lineales

Todos los circuitos eléctricos que se estudian en este curso se comportan como *sistemas lineales*: 

  - $f(x + y) = f(x) + f(y)$
    
    La respuesta $f$ a la suma de dos entradas $x$ e $y$ es igual a la suma de la respuesta individual a cada una de las entradas
  - $f(k \cdot x) = k \cdot f(x)$
    
    La respuesta a una entrada que está multiplicada por un factor de escala $k$ es igual a multiplicar por este factor a la respuesta a la entrada.

*** La linealidad es una aproximación de la realidad

  - Estas propiedades simplifican el tratamiento de los circuitos, y *permiten aplicar técnicas de resolución de ecuaciones lineales*.
  - La linealidad es una *aproximación de la realidad* que no puede aplicarse de manera indiscriminada a cualquier componente y en cualquier condición.
  - En particular, los *dispositivos electrónicos* como diodos o transistores tienen un *comportamiento* marcadamente *no lineal*, de forma que los circuitos que los contienen no pueden analizarse directamente con las técnicas que aquí se exponen sin realizar previamente aproximaciones de su funcionamiento.

*** Parámetros concentrados
- Los circuitos eléctricos reales ocupan espacio, las máquinas generadoras y los receptores tienen grandes dimensiones, y los cables conductores se extienden a lo largo de longitudes variopintas.
- Sin embargo, el análisis de circuitos no toma en consideración las propiedades espaciales de los circuitos ni de sus componentes, sino que los confina a elementos puntuales con un modelo de *parámetros concentrados*.
- Por ejemplo, un conductor real de $\SI{100}{\meter}$ se representará habitualmente como un conductor ideal con una resistencia en su punto medio.
*** Simplificación de las ecuaciones de Maxwell

- Este tratamiento es una simplificación de las ecuaciones del electromagnetismo de Maxwell
- Es aplicable únicamente cuando las dimensiones del circuito real son inferiores a la longitud de onda de la señal que circula por el circuito.
- Por ejemplo:
  - A la frecuencia de $\SI{50}{\hertz}$, habitual en sistemas eléctricos industriales, la longitud de onda de la señal es de $\SI{6000}{\kilo\meter}$.
  - A la frecuencia de $\SI{2.6}{\giga\hertz}$, característica de la telefonía 4G, la longitud de onda se reduce a $\SI{11.5}{\centi\meter}$. 


** Variables
*** Tensión Eléctrica
El *potencial eléctrico en un punto*, $v(t)$,  es la energía potencial que tiene una carga unitaria en ese punto debida al campo eléctrico. 

#+ATTR_LATEX: :height 0.3\textheight
[[file:../figs/tension_puntos.pdf]]

La *tensión o diferencia de potencial entre dos puntos* A y B, $u_{AB}(t)$, es el trabajo realizado por el campo eléctrico al desplazar una carga unitaria entre esos puntos. 

\begin{equation*}
  u_{AB}(t) = v_A(t) - v_B(t) = \frac{dW_{e}}{dq}
\end{equation*}

La *unidad* de la tensión eléctrica es el *voltio* (V).

*** La trayectoria no importa

Dado que el campo eléctrico es *conservativo*, la diferencia de potencial entre A y B *no depende de la trayectoria* seguida para realizar el desplazamiento, sino únicamente del potencial existente en cada uno de los puntos. 

#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/diagrama_tension.pdf]]

*** El signo depende del sentido

Aunque la trayectoria no sea relevante para el cálculo de la tensión, siempre hay que tener en cuenta el *sentido del desplazamiento*. 

#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/sentido_tension.pdf]]

Así, si el movimiento se produce desde B hasta A obtenemos el signo contrario al anterior resultado:

\begin{equation*}
  u_{BA} = v_B - v_A = - u_{AB} 
\end{equation*}

*** Corriente Eléctrica

Se define la *intensidad de la corriente eléctrica* como la variación de la carga $q(t)$ que atraviesa la sección transversal de un conductor por unidad de tiempo:

\begin{equation*}
  i(t)=\frac{dq(t)}{dt}
\end{equation*}

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/seccion_conductor.pdf]]

La corriente eléctrica se produce por el *movimiento de los electrones libres* que fluyen por el conductor. Sin embargo, por razones históricas, el *convenio* que se se emplea considera como sentido de la corriente el debido al *movimiento de las cargas positivas*.

La *unidad* de la corriente es el *amperio* (A).

*** Potencia Eléctrica

La *potencia eléctrica* es la variación del trabajo del campo eléctrico por unidad de tiempo:

\begin{equation*}
  p(t)=\frac{dW_{e}}{dt}
\end{equation*}

Esta definición genérica puede relacionarse con las anteriores variables:

\begin{align*}
  p(t) &= \frac{dW_e}{dq} \cdot \frac{dq(t)}{dt}\\
       &= v(t)\cdot i(t)
\end{align*}

La *unidad* de la potencia eléctrica es el *vatio* (W).

*** Signo de la potencia eléctrica

Para determinar el *signo de la potencia eléctrica* hay que tener en consideración los signos de las variables de las que depende, la tensión y la corriente. 
- Cuando las flechas de ambas variables tienen el *mismo sentido* la potencia eléctrica es *positiva*
- Cuando las flechas tienen *sentidos opuestos* la potencia eléctrica es *negativa*. 

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/signo_potencia.pdf]]

*** Receptores y Generadores
Es habitual *interpretar* este resultado en términos de potencia absorbida o potencia entregada. 
- Un *circuito receptor absorbe potencia* y la corriente /entra/ por el terminal de mayor potencial,
- Un *circuito generador entrega potencia* y la corriente /sale/ por el terminal de mayor potencial.

#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/receptor_generador.pdf]]

*** Potencia y Energía

-  Energía :: es la capacidad para realizar un trabajo.

   Unidades Wh, kWh

   1 kWh = 3.6 MJ

-  Potencia :: es la cantidad de trabajo efectuado /por unidad de
   tiempo/.

   Unidades W, kW

*** Rendimiento/Eficiencia
Cuadripolo (entrada/salida)
#+begin_export latex
\begin{equation*}
  \eta = \frac{P_{salida}}{P_{entrada}}
\end{equation*}
#+end_export

Receptor
#+begin_export latex
\begin{equation*}
  \eta_m = \frac{P_{util}}{P_{absorbida}}
\end{equation*}
#+end_export

Generador
#+begin_export latex
\begin{equation*}
  \eta_g = \frac{P_{entregada}}{P_{producida}}
\end{equation*}
#+end_export

Cualquier máquina tiene pérdidas:

#+begin_export latex
\begin{equation*}
  \boxed{\eta < 1}
\end{equation*}
#+end_export

*** Corriente Continua y Corriente Alterna

- Corriente Continua ($\frac{d}{dt} = 0$)
#+ATTR_LATEX: :height 0.25\textheight
[[file:../figs/continua.pdf]]

- Corriente Alterna ($\frac{d}{dt} \neq 0$)
#+ATTR_LATEX: :height 0.25\textheight
[[file:../figs/sin.pdf]]

* Elementos circuitales

** Elementos Pasivos
*** Resistencia

-  *Ley de Ohm*: una resistencia provoca una *diferencia de potencial* entre sus terminales *directamente proporcional* a su corriente: *resistencia* (Ohmios, [\Omega])
#+BEGIN_EXPORT latex
\[
u(t) = R \cdot i(t)
\]
#+END_EXPORT   
- *Criterio de Signos*: la tensión es positiva en el terminal por el que entra la corriente (las flechas de tensión y corriente tienen el mismo sentido).
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Resistencia.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Resistencia_Flecha.pdf]]

*** Resistividad
-  El valor de la resistencia depende de la *resistividad del material* (\rho), de la *sección* ($S$), y de la
   longitud ($l$):
#+begin_export latex
\begin{equation*}
  R = \rho \cdot \frac{l}{S}
\end{equation*}
#+end_export

- La *sección* se expresa en $\si{\milli\meter\squared}$.

- La *resistividad* depende del material conductor y de la temperatura ambiente:

  - Cobre a 20ºC: $\qty{17.24}{\milli\ohm\milli\meter\squared\per\meter}$.

*** Cortocircuito y Circuito Abierto
- Cortocircuito: resistencia nula (tensión nula)

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Cortocircuito.pdf]]

- Circuito abierto: resistencia infinita (corriente nula).

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/CircuitoAbierto.pdf]]

*** Ley de Joule

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Resistencia.pdf]]

- *Ley de Joule*: una resistencia disipa energía eléctrica produciendo *calor*.
#+BEGIN_EXPORT latex
\[
p(t)=R\cdot i^{2}(t)
\]
#+END_EXPORT


*** Bobina o inductancia

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Bobina.pdf]]

-  Cuando una corriente oscilante atraviesa un conductor arrollado alrededor de un núcleo, se produce una *tensión inducida que se opone a esta corriente* (ley de Faraday y Lenz)

-  La tensión en sus terminales es directamente proporcional al cambio de la corriente: coeficiente de autoinducción o *inductancia* (Henrios [H]).
   
#+BEGIN_EXPORT latex
\[
u_L(t)=L\cdot\frac{di(t)}{dt}
\]
#+END_EXPORT

*** Bobina o inductancia

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Bobina.pdf]]

-  Almacena *energía magnética*.

#+begin_export latex
\[
  E_L(t) = \int_{-\infty}^t u(\tau) \cdot i(\tau) d\tau = \frac{1}{2} \cdot L \cdot i^2(t)
\]
#+end_export
-  En circuitos de corriente continua es un cortocircuito.

#+begin_export latex
\begin{equation*}
  \frac{di(t)}{dt} = 0 \Rightarrow U_L = 0
\end{equation*}
#+end_export

*** Condensador

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Condensador.pdf]]

- Un *condensador* está formado por dos placas metálicas separadas por una capa dieléctrica. Al aplicar tensión se produce una *separación de cargas opuestas* que se *acumulan* en cada placa.

- La *carga acumulada* en un instante es *proporcional* a la *diferencia de potencial* en ese instante: *capacidad* (Faradios [F]).

#+BEGIN_EXPORT latex
\[
q(t) = C \cdot u(t)
\]
#+END_EXPORT

-  En el proceso de carga se produce una corriente eléctrica entre las dos placas.
#+BEGIN_EXPORT latex
\[
i_C(t)=\frac{dq(t)}{d(t)}=C\frac{du(t)}{dt}
\]
#+END_EXPORT


*** Condensador

#+ATTR_LATEX: :height 0.2\textheight
[[file:../figs/Condensador.pdf]]

- Un condensador almacena *energía eléctrica*

#+begin_export latex
\[
  E_c(t) = \int_{-\infty}^t u(\tau) \cdot i(\tau) d\tau = \frac{1}{2} \cdot C \cdot u^2(t)
\]
#+end_export

-  En un circuito de corriente continua se comporta como un circuito abierto.

\begin{equation*}
  \frac{du(t)}{dt} = 0 \Rightarrow I_c = 0
\end{equation*}

** Generadores Independientes


*** Generador Ideal

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 [[file:../figs/FuenteTensionIdealDC.pdf]]
 Un *generador de tensión ideal* impone la tensión a la salida (/la corriente depende del circuito/). Se caracteriza por su *fuerza electromotriz* (voltios [V]).

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 [[file:../figs/FuenteCorrienteIdeal.pdf]]
 Un *generador de corriente ideal* impone la corriente a la salida (/la tensión depende del circuito/). Se caracteriza por su corriente de generador.

*** Generador Real
Los generadores reales tienen pérdidas que se modelan con una resistencia en *serie* (generador de tensión) o en *paralelo* (generador de corriente)

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.7\textheight
 file:../figs/FuenteTensionRealDC.pdf
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.7\textheight
 file:../figs/FuenteCorrienteRealDC.pdf


** Generadores Dependientes 

*** Generadores de Tensión
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
  #+ATTR_LATEX: :height 0.7\textheight
  [[file:../figs/FuenteTensionDependienteTension.pdf]]
... de Tensión
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
  #+ATTR_LATEX: :height 0.7\textheight
  [[file:../figs/FuenteTensionDependienteCorriente.pdf]]
... de Corriente
*** Generadores de Corriente  
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
   #+ATTR_LATEX: :height 0.7\textheight
 [[file:../figs/FuenteCorrienteDependienteTension.pdf]]
... de Tensión
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
  #+ATTR_LATEX: :height 0.7\textheight
 [[file:../figs/FuenteCorrienteDependienteCorriente.pdf]]
... de Corriente



* Leyes de Kirchhoff

** Definiciones
*** Nudo, rama, malla
  - Nudo :: unión de *3* o más conductores.
  - Rama :: elementos conectados entre dos nudos consecutivos.
  - Lazo :: conjunto de ramas que forman un camino cerrado.
  - Malla :: lazo que no contiene ningún otro en su interior.

#+ATTR_LATEX: :height 0.5\textheight
file:../figs/mallas.pdf

*** Ley de Kirchhoff de las Corrientes (LKC)
- La *LKC* es el principio de conservación de la carga aplicado a los circuitos eléctricos.

- *LKC*: la suma de las corrientes que llegan a un nudo es igual a la suma de las que salen.

  - Las lineas de corriente son cerradas (o solenoidales).

#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/LKC_FM.pdf]]
#+BEGIN_EXPORT latex
\[
i_1(t) - i_2(t) + i_3(t) - i_4(t) + i_5(t) = 0
\]
#+END_EXPORT

*** Ley de Kirchhoff de los Voltajes (LKV)
- La *LKV* es el principio de conservación de la energía aplicado a los circuitos eléctricos.

- *LKV*: la suma (con signo) de las tensiones a lo largo de un camino cerrado (circuito) es cero.

  - La energía producida por un generador es consumida por los receptores del circuito para producir trabajo (mecánico, químico, etc.) o calor.

#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/LKV_FM.pdf]]
#+BEGIN_EXPORT latex
\[
u_3(t) + u_4 (t) - u_5 (t) - u_1 (t) - u_2 (t)  = 0
\]
#+END_EXPORT

*** Balance de Tensiones
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/circuito_lkv.pdf]]

#+begin_export latex
\begin{equation*}
  U_{A'A} + U_{AC} + U_{CC'} + U_{C'D'} + U_{D'D} + U_{DB} + U_{BB'} + U_{B'A'} = 0
\end{equation*}

\begin{align*}
  U_{AB} &= U_{AA'} + U_{A'B'} + U_{B'B}\\
  U_{CD} &= U_{CC'} + U_{C'D'} + U_{D'D}
\end{align*}
#+end_export

*** Balance de Tensiones
#+ATTR_LATEX: :height 0.25\textheight
[[file:../figs/circuito_lkv.pdf]]
#+begin_export latex
\begin{equation*}
  U_{A'A} + U_{AC} + U_{CC'} + U_{C'D'} + U_{D'D} + U_{DB} + U_{BB'} + U_{B'A'} = 0
\end{equation*}
#+end_export

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+begin_export latex
\begin{align*}
  U_{A'A} &= I \cdot R_g\\
  U_{AC} &= I \cdot R_L\\
  U_{CC'} &= I \cdot R_m\\
  U_{C'D'} &= \epsilon_m\\
  U_{D'D} &= 0 = U_{BB'}\\
  U_{DB} &= I \cdot R_L\\
  U_{B'A'} &= -\epsilon_g
\end{align*}
#+end_export
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
#+begin_export latex
\begin{equation*}
  \boxed{I \cdot (R_g + 2\cdot R_L + R_m) + \epsilon_m = \epsilon_g}
\end{equation*}
#+end_export
*** Generador y Receptor
#+ATTR_LATEX: :height 0.25\textheight
[[file:../figs/circuito_lkv.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+begin_export latex
\begin{align*}
  U_{A'A} &= I \cdot R_g\\
  U_{AC} &= I \cdot R_L\\
  U_{CC'} &= I \cdot R_m\\
  U_{C'D'} &= \epsilon_m\\
  U_{D'D} &= 0 = U_{BB'}\\
  U_{DB} &= I \cdot R_L\\
  U_{B'A'} &= -\epsilon_g
\end{align*}
#+end_export
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
#+begin_export latex
\begin{align*}
  U_{AB} &= U_{AA'} + U_{A'B'} + U_{B'B}\\
  \Aboxed{U_{AB} &= \epsilon_g - I \cdot R_g}
\end{align*}

\begin{align*}
  U_{CD} &= U_{CC'} + U_{C'D'} + U_{D'D}\\
  \Aboxed{U_{CD} &= \epsilon_m + I\cdot R_m}
\end{align*}
#+end_export
** Generadores

*** Ecuación del generador

Los generadores reales tienen pérdidas que se modelan con una resistencia en *serie* (generador de tensión) o en *paralelo* (generador de corriente)

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 file:../figs/FuenteTensionRealDC.pdf
#+begin_export latex
\[
  U_{AB} = \epsilon_g - R_{\epsilon_g} \cdot I
\]
#+end_export
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
#+ATTR_LATEX: :height 0.5\textheight
 file:../figs/FuenteCorrienteRealDC.pdf
#+begin_export latex
\[
  I = I_g - \frac{U_{AB}}{R_{I_g}}
\]
#+end_export


*** Equivalencia de Fuentes

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.25
    :END:
#+ATTR_LATEX: :height 0.45\textheight
 file:../figs/FuenteTensionRealDC.pdf

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

- Dos fuentes son equivalentes cuando suministran el mismo valor de tensión y corriente a un *circuito externo*, para cualquier circuito.

- Sólo es posible establecer equivalencia entre *fuentes reales*.

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.25
    :END:

#+ATTR_LATEX: :height 0.45\textheight
 file:../figs/FuenteCorrienteRealDC.pdf


*** Equivalencia de Fuentes

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.25
    :END:
#+ATTR_LATEX: :height 0.43\textheight
 file:../figs/FuenteTensionRealDC.pdf

#+ATTR_LATEX: :height 0.43\textheight
 file:../figs/FuenteCorrienteRealDC.pdf

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.75
    :END:

La salida de tensión de una fuente de tensión es:
#+begin_export latex
\[
  U_{AB} = \epsilon_g - R_{\epsilon_g} \cdot I
\]
#+end_export
Y de una fuente de corriente:
#+begin_export latex
\[
  I = I_g - \frac{U_{AB}}{R_{I_g}} \rightarrow U_{AB} = R_{I_g} \cdot I_g - R_{I_g} \cdot I
\]
#+end_export
Las fuentes son equivalentes cuando las ecuaciones coinciden para cualquier combinación $(U_{AB}, I)$:
#+begin_export latex
    \[
    \boxed{R_g = R_{\epsilon_g} = R_{I_g}}
    \]
    \[
      \boxed{\epsilon_g = R_g \cdot I_g} \Leftrightarrow \boxed{I_g = \frac{\epsilon_g}{R_g}}
    \]
#+end_export

** Asociación de Elementos

*** Conexión en serie

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+ATTR_LATEX: :height 0.85\textheight
[[file:../figs/AsociacionSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

Un conjunto de elementos están asociados en serie cuando circula la misma corriente por todos ellos.
#+begin_export latex
\begin{align*}
  u_1(t) &= R_1 \cdot i(t)\\
  u_2(t) &= R_2 \cdot i(t)\\
  u_3(t) &= R_3 \cdot i(t)
\end{align*}
#+end_export
*** Conexión en serie
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+ATTR_LATEX: :height 0.85\textheight
[[file:../figs/AsociacionSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

Aplicando LKV:
#+begin_export latex
\begin{equation*}
  u(t) = u_1(t) + u_2(t) + u_3(t)
\end{equation*}
#+end_export

Sacando $i(t)$ como factor común:
#+begin_export latex
\begin{equation*}
  u(t) = i(t) \cdot (R_1 + R_2 + R_3)
\end{equation*}
#+end_export

Definimos la resistencia equivalente de la conexión serie:
#+begin_export latex
\begin{align*}
  \Aboxed{R_s &= \sum_{i = 1}^n R_i}\\
  u(t) &= R_s \cdot i(t)
\end{align*}
#+end_export

*** Divisor de Tensión
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+ATTR_LATEX: :height 0.85\textheight
[[file:../figs/AsociacionSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

De las ecuaciones anteriores tenemos:
#+begin_export latex
\begin{align*}
  i(t) &= \frac{u(t)}{R_1 + R_2 + R_3}\\
  u_3(t) &= R_3 \cdot i(t)\\
\end{align*}
#+end_export

Por tanto, la tensión parcial $u_3(t)$ se puede expresar en función de la tensión total $u(t)$: 
#+begin_export latex
\begin{equation*}
  u_3(t) = u(t) \cdot \frac{R_3}{R_1 + R_2 + R_3}  
\end{equation*}
#+end_export

En general:
#+begin_export latex
\begin{equation*}
  \boxed{u_o(t) = u(t) \cdot \frac{R_o}{R_s}}
\end{equation*}
#+end_export
*** Conexión en serie de inductancias
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+ATTR_LATEX: :height 0.85\textheight
[[file:../figs/BobinasSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

#+begin_export latex
\begin{align*}
  u_1(t) &= L_1 \cdot \frac{di(t)}{dt}\\
  u_2(t) &= L_2 \cdot \frac{di(t)}{dt}\\
  u_3(t) &= L_3 \cdot \frac{di(t)}{dt}\\
\end{align*}
#+end_export

#+begin_export latex
\begin{align*}
  \Aboxed{L_s &= \sum_{i = 1}^n L_i}\\
  u(t) &= L_s \cdot \frac{di(t)}{dt}
\end{align*}
#+end_export

*** Conexión en serie de condensadores
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+ATTR_LATEX: :height 0.85\textheight
[[file:../figs/CondensadoresSerie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

#+begin_export latex
\begin{align*}
  i(t) &= C_1 \cdot \frac{du_1(t)}{dt}\\
  i(t) &= C_2 \cdot \frac{du_2(t)}{dt}\\
  i(t) &= C_3 \cdot \frac{du_3(t)}{dt}\\
\end{align*}
#+end_export

#+begin_export latex
\begin{align*}
  \Aboxed{\frac{1}{C_s} &= \sum_{i = 1}^n \frac{1}{C_i}}\\
  i(t) &= C_s \cdot \frac{du(t)}{dt}
\end{align*}
#+end_export
*** Conexión en serie de generadores
**** Generadores de Tensión

- Pueden conectarse en serie sin restricción.

  #+begin_export latex
  \begin{align*}
    \epsilon_T &= \sum_{i = 1}^N \epsilon_i\\
    R_{gT} &= \sum_{i = 1}^N R_{gi}\\ 
  \end{align*}
#+end_export

**** Generadores de Corriente

- Ideal: todas las fuentes deben ser idénticas (valor y sentido).
- Real:  sin restricción, transformación de fuentes para fuente equivalente.


*** Conexión en paralelo

Un conjunto de elementos están asociados en paralelo cuando están sometidos a la misma diferencia de potencial.
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/AsociacionParalelo.pdf]]

#+begin_export latex
\begin{align*}
  i_1(t) &= u(t)/R_1\\
  i_2(t) &= u(t)/R_2\\
  i_3(t) &= u(t)/R_3
\end{align*}
#+end_export
*** Conexión en paralelo
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
[[file:../figs/AsociacionParalelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:

Aplicando LKC:
#+begin_export latex
\begin{equation*}
  i(t) = i_1(t) + i_2(t) + i_3(t)
\end{equation*}
#+end_export

Sacando $u(t)$ como factor común:
#+begin_export latex
\begin{equation*}
  i(t) = u(t) \cdot (\frac{1}{R_1} + \frac{1}{R_2} + \frac{1}{R_3})
\end{equation*}
#+end_export

Definimos la resistencia equivalente de la conexión paralelo:
#+begin_export latex
\begin{align*}
  \Aboxed{\frac{1}{R_p} &= \sum_{i = 1}^n \frac{1}{R_i}}\\
  u(t) &= R_p \cdot i(t)
\end{align*}
#+end_export
*** Dos resistencias en paralelo

En el caso concreto de *dos* resistencias en paralelo ...
#+begin_export latex
\begin{equation*}
  \frac{1}{R_p} = \frac{1}{R_1} + \frac{1}{R_2}
\end{equation*}
#+end_export
... la expresión es:
#+begin_export latex
\begin{equation*}
  \boxed{R_p = \frac{R_1 \cdot R_2}{R_1 + R_2}}
\end{equation*}
#+end_export

*** Conductancia

Para facilitar las operaciones es conveniente utilizar el inverso de la resistencia:

#+begin_export latex
\begin{equation*}
  G = \frac{1}{R}
\end{equation*}
#+end_export

Así, en lugar de...
#+begin_export latex
\begin{align*}
  \frac{1}{R_p} &= \sum_{i = 1}^n \frac{1}{R_i}\\
  u(t) &= R_p \cdot i(t)
\end{align*}
#+end_export

... podemos escribir:
#+begin_export latex
\begin{align*}
  \Aboxed{G_p &= \sum_{i = 1}^n G_i}\\
  i(t) &= G_p \cdot u(t)
\end{align*}
#+end_export

*** Divisor de corriente
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
[[file:../figs/AsociacionParalelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:

De las ecuaciones anteriores tenemos (usando conductancia):
#+begin_export latex
\begin{align*}
  u(t) &= \frac{i(t)}{G_1 + G_2 + G_3}\\
  i_3(t) &= G_3 \cdot u(t)\\
\end{align*}
#+end_export

Por tanto, la corriente parcial $i_3(t)$ se puede expresar en función de la corriente total $i(t)$: 
#+begin_export latex
\begin{equation*}
  i_3(t) = i(t) \cdot \frac{G_3}{G_1 + G_2 + G_3}  
\end{equation*}
#+end_export

En general:
#+begin_export latex
\begin{equation*}
  \boxed{i_o(t) = i(t) \cdot \frac{G_o}{G_p}}
\end{equation*}
#+end_export

*** Conexión en paralelo de inductancias
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/BobinasParalelo.pdf]]

****  :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

#+begin_export latex
\begin{align*}
  u(t) &= L_1 \cdot \frac{di_1(t)}{dt}\\
  u(t) &= L_2 \cdot \frac{di_2(t)}{dt}\\
  u(t) &= L_3 \cdot \frac{di_3(t)}{dt}\\
\end{align*}
#+end_export
****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  \Aboxed{\frac{1}{L_p} &= \sum_{i = 1}^n \frac{1}{L_i}}\\
  u(t) &= L_p \cdot \frac{di(t)}{dt}
\end{align*}
#+end_export

*** Conexión en paralelo de condensadores

#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/CondensadoresParalelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  i_1(t) &= C_1 \cdot \frac{du(t)}{dt}\\
  i_2(t) &= C_2 \cdot \frac{du(t)}{dt}\\
  i_3(t) &= C_3 \cdot \frac{du(t)}{dt}\\
\end{align*}
#+end_export
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  \Aboxed{C_p &= \sum_{i = 1}^n C_i}\\
  i(t) &= C_p \cdot \frac{du(t)}{dt}
\end{align*}
#+end_export

*** Conexión en paralelo de generadores
**** Generadores de Tensión

- Ideal: todas las fuentes deben ser idénticas (valor y polaridad).
- Real:  sin restricción, transformación de fuentes para fuente equivalente.


**** Generadores de Corriente
- Pueden conectarse en paralelo sin restricción.

  #+begin_export latex
  \begin{align*}
    I_{gT} &= \sum_{i = 1}^N I_{gi}\\
    G_{gT} &= \sum_{i = 1}^N G_{gi}\\ 
  \end{align*}
#+end_export

*** Conexión Estrella - Triángulo
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/Conexion_Triangulo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/Conexion_Estrella.pdf]]
*** Conexión Estrella - Triángulo
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/Conexion_Triangulo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  R_{AB} &= \frac{R_{ab} \cdot (R_{bc} + R_{ca})}{R_{ab} + R_{bc} + R_{ca}}\\
  \\
  R_{BC} &= \frac{R_{bc} \cdot (R_{ab} + R_{ca})}{R_{ab} + R_{bc} + R_{ca}}\\
  \\
  R_{CA} &= \frac{R_{ca} \cdot (R_{ab} + R_{bc})}{R_{ab} + R_{bc} + R_{ca}}
\end{align*}
#+end_export
*** Conexión Estrella - Triángulo
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:../figs/Conexion_Triangulo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
#+begin_export latex
\begin{align*}
  R_{AB} &= \frac{R_{ab} \cdot R_{bc}}{R_{ab} + R_{bc} + R_{ca}} + \frac{R_{ab} \cdot R_{ca}}{R_{ab} + R_{bc} + R_{ca}}\\
  \\
  R_{BC} &= \frac{R_{bc} \cdot R_{ab}}{R_{ab} + R_{bc} + R_{ca}} + \frac{R_{bc} \cdot R_{ca}}{R_{ab} + R_{bc} + R_{ca}}\\
  \\
  R_{CA} &= \frac{R_{ca} \cdot R_{ab}}{R_{ab} + R_{bc} + R_{ca}} + \frac{R_{ca} \cdot R_{bc}}{R_{ab} + R_{bc} + R_{ca}}
\end{align*}
#+end_export
*** Conexión Estrella - Triángulo
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/Conexion_Estrella.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  R_{AB} &= R_a + R_b\\
  \\
  R_{BC} &= R_b + R_c\\
  \\
  R_{CA} &= R_c + R_a\\
\end{align*}
#+end_export
*** Conexión Estrella - Triángulo
#+begin_export latex
\begin{align*}
  \frac{R_{a{\color{red}b}} \cdot R_{{\color{red}b}c}}{R_{ab} + R_{bc} + R_{ca}} + \frac{R_{{\color{blue}a}b} \cdot R_{c{\color{blue}a}}}{R_{ab} + R_{bc} + R_{ca}} &= R_{\color{blue}a} + R_{\color{red}b}\\
  \\
  \frac{R_{a{\color{red}b}} \cdot R_{{\color{red}b}c}}{R_{ab} + R_{bc} + R_{ca}} + \frac{R_{b{\color{green}c}} \cdot R_{{\color{green}c}a}}{R_{ab} + R_{bc} + R_{ca}} &= R_{\color{red}b} + R_{\color{green}c}\\
  \\
  \frac{R_{{\color{blue}a}b} \cdot R_{c{\color{blue}a}}}{R_{ab} + R_{bc} + R_{ca}} + \frac{R_{b{\color{green}c}} \cdot R_{{\color{green}c}a}}{R_{ab} + R_{bc} + R_{ca}} &= R_{\color{green}c} + R_{\color{blue}a}
\end{align*}
#+end_export
*** Conversión de Triángulo a Estrella
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:../figs/Conexion_Triangulo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+begin_export latex
\begin{align*}
  R_a &= \frac{R_{ab} \cdot R_{ca}}{R_{ab} + R_{bc} + R_{ca}}\\
  \\
  R_b &= \frac{R_{ab} \cdot R_{bc}}{R_{ab} + R_{bc} + R_{ca}}\\
  \\
  R_c &= \frac{R_{bc} \cdot R_{ca}}{R_{ab} + R_{bc} + R_{ca}}
\end{align*}
#+end_export

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:../figs/Conexion_Estrella.pdf]]
*** Conversión de Estrella a Triángulo
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:../figs/Conexion_Estrella.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+begin_export latex
\begin{align*}
  G_{ab} &= \frac{G_a \cdot G_b}{G_a + G_b + G_c}\\
  \\
  G_{bc} &= \frac{G_b \cdot G_c}{G_a + G_b + G_c}\\
  \\
  G_{ca} &= \frac{G_c \cdot G_a}{G_a + G_b + G_c}
\end{align*}
#+end_export
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
[[file:../figs/Conexion_Triangulo.pdf]]
* Métodos de Análisis

** Método de las mallas

*** 
#+ATTR_LATEX: :height 0.95\textheight
[[file:../figs/mallas1.pdf]]

*** Aplicamos LKC

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/mallas1.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
Nudo A:
\begin{equation*}
  I_6 = I_1 + I_2
\end{equation*}

Nudo B:
\begin{equation*}
  I_1 + I_3 + I_5 = 0
\end{equation*}

Nudo C:
\begin{equation*}
  I_2 = I_3 + I_4
\end{equation*}

Nudo D:
\begin{equation*}
  I_4 = I_5 + I_6
\end{equation*}
#+end_export

****                                                     :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
\vspace{5pt}

#+begin_export latex

No son ecuaciones linealmente independientes:
\begin{equation*}
  C = A + B + D
\end{equation*}
#+end_export

*** Aplicamos LKV

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/mallas1.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
Malla ABCA
\begin{equation*}
  I_1 \cdot R_1 - \epsilon_1 + \epsilon_2 - I_3 \cdot R_3 - I_2 \cdot R_2 = 0
\end{equation*}

Malla BDCB
\begin{equation*}
  -I_5 \cdot R_5 - I_4 \cdot R_4 + I_3 \cdot R_3 - \epsilon_2 = 0
\end{equation*}

Malla ACDA
\begin{equation*}
  I_2 \cdot R_2 + I_4 \cdot R_4 + I_6 \cdot R_6 - \epsilon_3 = 0
\end{equation*}
#+end_export

*** Combinamos las ecuaciones
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/mallas1.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

#+begin_export latex
\begin{align*}
  - I_1 -  I_2 + I_6  &= 0\\
  I_1 + I_3 + I_5 &= 0\\
  I_4 - I_5 - I_6 &= 0\\
  I_1 \cdot R_1 - I_2 \cdot R_2 - I_3 \cdot R_3 &= \epsilon_1 - \epsilon_2\\
  I_3 \cdot R_3 - I_4 \cdot R_4 -I_5 \cdot R_5 &= \epsilon_2\\
  I_2 \cdot R_2 + I_4 \cdot R_4 + I_6 \cdot R_6 &= \epsilon_3
\end{align*}
#+end_export
*** Y las expresamos en forma matricial

#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    -1 & -1 & 0 & 0 & 0 & 1\\
    1 & 0 & 1 & 0 & 1 & 0\\
    0 & 0 & 0 & 1 & -1 & -1\\
    R_1 & -R_2 & - R_3 & 0 & 0 & 0\\
    0 & 0 & R_3 & - R_4 & - R_5 & 0\\
    0 & R_2 & 0 & R_4 & 0 & R_6
  \end{bmatrix} \cdot %
  \begin{bmatrix}
    I_1\\
    I_2\\
    I_3\\
    I_4\\
    I_5\\
    I_6    
  \end{bmatrix} = %
  \begin{bmatrix}
    0\\
    0\\
    0\\
    \epsilon_1 - \epsilon_2\\
    \epsilon_2\\
    \epsilon_3
  \end{bmatrix}
\end{equation*}
#+end_export

Resolver el circuito implica resolver un sistema lineal de 6 ecuaciones, en el que las incógnitas son las corrientes de cada rama.
*** Método de las mallas

El método de las mallas simplifica el sistema de ecuaciones necesario mediante unas corrientes /virtuales/ denominadas *corrientes de malla*, aprovechando las relaciones entre corrientes de la LKC.

#+ATTR_LATEX: :height 0.7\textheight
[[file:../figs/mallas1_corrientes.pdf]]
*** Relaciones entre las corrientes de rama y malla
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
[[file:../figs/mallas1_corrientes.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+begin_export latex
Ramas externas:
\begin{align*}
  I_1 &= I_a\\
  I_5 &= -I_b\\
  I_6 &= I_c
\end{align*}
Ramas internas:
\begin{align*}
  I_2 &= I_c -I_a\\
  I_3 &= I_b - I_a\\
  I_4 &= I_c - I_b
\end{align*}
#+end_export
*** Ecuaciones de malla
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/mallas1_corrientes.pdf]]

#+begin_export latex
Malla ABCA
\begin{equation*}
  I_a \cdot R_1 - \epsilon_1 + \epsilon_2 + (I_a - I_b) \cdot R_3 + (I_a - I_c) \cdot R_2 = 0
\end{equation*}
Malla BDCB
\begin{equation*}
  I_b \cdot R_5 + (I_b - I_c) \cdot R_4 + (I_b - I_a) \cdot R_3 - \epsilon_2 = 0
\end{equation*}
Malla ACDA
\begin{equation*}
  (I_c - I_a) \cdot R_2 + (I_c - I_b) \cdot R_4 + I_c \cdot R_6 - \epsilon_3 = 0
\end{equation*}
#+end_export
*** Reagrupamos corrientes en las ecuaciones
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/mallas1_corrientes.pdf]]

#+begin_export latex
\begin{align*}
  I_a \cdot (R_1 + R_3 + R_2)  - I_b\cdot R_3 - I_c \cdot R_2 &= \epsilon_1 - \epsilon_2\\
  - I_a \cdot R_3 + I_b \cdot (R_5 + R_4 + R_3) - I_c \cdot R_4 &=  \epsilon_2\\
  - I_a \cdot R_2 - I_b \cdot R_4 + I_c \cdot (R_2 + R_4 + R_6) &= \epsilon_3
\end{align*}
#+end_export
*** Y lo expresamos en forma matricial
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/mallas1_corrientes.pdf]]

#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    (R_1 + R_3 + R_2) &  - R_3 & - R_2 \\
    - R_3 & (R_5 + R_4 + R_3) & - R_4 \\
    - R_2 & - R_4 &  (R_2 + R_4 + R_6)
  \end{bmatrix} \cdot %
  \begin{bmatrix}
    I_a\\
    I_b\\
    I_c\\
  \end{bmatrix} = %
  \begin{bmatrix}
    \epsilon_1 - \epsilon_2\\
    \epsilon_2\\
    \epsilon_3
  \end{bmatrix}
\end{equation*}
#+end_export
*** Ecuación General
#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    {\color{BrickRed}\sum R_{aa}} &  - {\color{MidnightBlue}\sum R_{ab}} & - {\color{MidnightBlue}\sum R_{ca}} \\
    - {\color{MidnightBlue}\sum R_{ab}} & {\color{BrickRed}\sum R_{bb}} & - {\color{MidnightBlue}\sum R_{bc}} \\
    - {\color{MidnightBlue}\sum R_{ca}} & - {\color{MidnightBlue}\sum R_{bc}} &  {\color{BrickRed}\sum R_{cc}}
  \end{bmatrix} \cdot %
  \begin{bmatrix}
    I_a\\
    I_b\\
    I_c\\
  \end{bmatrix} = %
  \begin{bmatrix}
    {\color{OliveGreen}\sum\epsilon_a}\\
    {\color{OliveGreen}\sum\epsilon_b}\\
    {\color{OliveGreen}\sum\epsilon_c}
  \end{bmatrix}
\end{equation*}
#+end_export
- ${\color{BrickRed}\sum R_{aa}}$ :: suma de las resistencias incluidas en la malla de $I_a$.
- ${\color{MidnightBlue}\sum R_{ab}}$ :: suma de las resistencias incluidas en las ramas compartidas por las mallas de $I_a$ e $I_b$.
- ${\color{OliveGreen}\sum \epsilon_a}$ :: suma algebraica de las fuerzas electromotrices de los generadores de la malla de $I_a$. Su signo es positivo si contribuyen al giro de la corriente.
*** Procedimiento

1. Identificar las corrientes de rama.
2. Asignar un sentido a las corrientes de malla.
3. Relacionar corrientes de rama con corrientes de malla.
4. Escribir ecuación de mallas.
5. Resolver la ecuación, obteniendo las corrientes de malla.
6. Obtener las corrientes de rama con las relaciones del punto 3.

*Importante*: todos los generadores deben ser fuentes de tensión.

** Método de los nudos
*** 
[[file:../figs/nudos.pdf]]

*** Aplicamos LKC
[[file:../figs/nudos.pdf]]

#+begin_export latex
Nudo A
\begin{equation*}
  I_{g1} - I_a - I_{ab} = 0
\end{equation*}

Nudo B
\begin{equation*}
  I_{ab} - I_{g2} - I_b = 0
\end{equation*}
#+end_export
*** Tensiones en las resistencias
[[file:../figs/nudos.pdf]]

#+begin_export latex
\begin{align*}
  V_A &= I_a \cdot R_1\\
  V_B &= I_b \cdot R_3\\
  V_{AB} &= I_{ab} \cdot R_2
\end{align*}
#+end_export
*** Despejamos las corrientes
[[file:../figs/nudos.pdf]]

#+begin_export latex
\begin{align*}
  I_a &= V_A \cdot G_1\\
  I_b &= V_B \cdot G_3\\
  I_{ab} &= (V_A - V_B) \cdot G_2
\end{align*}
#+end_export


*** Combinamos las ecuaciones
[[file:../figs/nudos.pdf]]

#+begin_export latex
Nudo A
\begin{equation*}
  I_{g1} - V_A \cdot G_1 - (V_A - V_B) \cdot G_2 = 0
\end{equation*}

Nudo B
\begin{equation*}
  (V_A - V_B) \cdot G_2 - I_{g2} - V_B \cdot G_3 = 0
\end{equation*}
#+end_export


*** Reorganizamos las ecuaciones
[[file:../figs/nudos.pdf]]

#+begin_export latex
Nudo A
\begin{equation*}
  I_{g1} = V_A \cdot (G_1 + G_2) - V_B \cdot G_2 
\end{equation*}

Nudo B
\begin{equation*}
  - I_{g2} = - V_A \cdot G_2 + V_B \cdot (G_2 + G_3)
\end{equation*}
#+end_export

*** Expresión matricial
[[file:../figs/nudos.pdf]]
#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    G_1 + G_2 & - G_2\\
    -G_2 & G_2 + G_3
  \end{bmatrix} \cdot%
  \begin{bmatrix}
    V_A\\
    V_B
  \end{bmatrix} = %
  \begin{bmatrix}
    I_{g1}\\
    -I_{g2}
  \end{bmatrix}
\end{equation*}
#+end_export

*** Ecuación general

#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    {\color{BrickRed}\sum G_A} & - {\color{MidnightBlue}\sum G_{AB}} & - {\color{MidnightBlue}\sum G_{AC}}\\
    -{\color{MidnightBlue}\sum G_{AB}} & {\color{BrickRed}\sum G_B} & -{\color{MidnightBlue}\sum G_{BC}}\\
    -{\color{MidnightBlue}\sum G_{AC}} & -{\color{MidnightBlue}\sum G_{BC}} & {\color{BrickRed}\sum G_C}
  \end{bmatrix} \cdot%
  \begin{bmatrix}
    V_A\\
    V_B\\
    V_C
  \end{bmatrix} = %
  \begin{bmatrix}
    {\color{OliveGreen}\sum I_{gA}}\\
    {\color{OliveGreen}\sum I_{gB}}\\
    {\color{OliveGreen}\sum I_{gC}}
  \end{bmatrix}
\end{equation*}
#+end_export

- ${\color{BrickRed}\sum G_A}$ :: Suma de las conductancias conectadas al nudo $A$.
- ${\color{MidnightBlue}\sum G_{AB}}$ :: Suma de las conductancias conectadas entre los nudos $A$ y $B$.
- ${\color{OliveGreen}\sum I_{gA}}$ :: Suma algebraica de las corrientes de los generadores conectados en el nudo A. El signo es positivo si el generador inyecta corriente en el nudo.

*Importante*: todos los generadores deben ser fuentes de corriente.

* Teoremas
** Circuitos Lineales

*** Elementos lineales

- Un circuito eléctrico es lineal si los elementos pasivos y activos que incluye son lineales.
- Un *elemento pasivo* es lineal si la relación entre la tensión entre sus terminales y la corriente que lo recorre es lineal: *resistencias, condensadores y bobinas*.
- Una *fuente dependiente* es lineal si su salida (tensión o corriente) tiene una relación lineal con la magnitud del circuito de la que depende.
- Un circuito lineal tiene dos propiedades:
  - Homogeneidad o *proporcionalidad*.
  - Aditividad o *superposición*.

*** Homogeneidad o Proporcionalidad
Sea $y(t)$ la respuesta de un *circuito lineal* a una excitación $x(t)$. 

Si la excitación es multiplicada por una *constante*, $K \cdot x(t)$, la respuesta del circuito será modificada por la misma constante, $K \cdot y(t)$.

#+ATTR_LATEX: :width 0.6\textwidth
[[file:../figs/proporcionalidad.pdf]]

*** Análisis de un circuito mediante proporcionalidad

**** ¿Qué excitación debo aplicar a un circuito para obtener una determinada respuesta?
 - Aplicamos una excitación de valor unidad.
 - Resolvemos el circuito, obteniendo la respuesta del circuito a la excitación unidad.
 - Hallamos la constante de proporcionalidad entre la respuesta obtenida y la respuesta deseada.
 - La excitación que se debe aplicar es esta constante de proporcionalidad (puede ser un número complejo).

*** Análisis de un circuito mediante proporcionalidad

**** ¿Qué respuesta proporciona un circuito ante una determinada excitación?
 - Suponemos una respuesta de valor unidad.
 - Resolvemos el circuito a la inversa, obteniendo la excitación que provoca la respuesta unidad.
 - Hallamos la constante de proporcionalidad entre la excitación obtenida y la excitación deseada.
 - La respuesta que entrega el circuito es esta constante de proporcionalidad (puede ser un número complejo).

*** Aditividad o Superposición

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
La respuesta de un *circuito lineal* a varias fuentes de excitación actuando simultáneamente es igual a la suma de las respuestas que se tendrían cuando actuase cada una de ellas por separado

#+begin_export latex
\[
y(t) = \sum_i y_i(t)
\]
#+end_export

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:

 [[file:../figs/superposicion.pdf]]

*** Análisis de un circuito mediante superposición
**** Procedimiento
 1. Se apagan todas las fuentes *independientes* del circuito menos una.
    - Las fuentes de tensión se sustituyen por un cortocircuito ($U = 0$).
    - Las fuentes de corriente se sustituyen por un circuito abierto ($I = 0$).
    - Las fuentes *dependientes* *no* se modifican.
 2. Se analiza el circuito, obteniendo la respuesta individual a la fuente que permanece activa.
 3. Se repite este procedimiento para cada una de las fuentes *independientes* del circuito.
 4. La respuesta total del circuito es la suma de las respuestas individuales.

*** Principio de superposición y Potencia

El principio de superposición aplica a tensiones y corrientes, pero *no* a potencias. Supongamos $I = I_1 + I_2$:
#+begin_export latex
\begin{align*}
  P &= R \cdot I^2 =\\
       &= R \cdot (I_1 + I_2)^2 =\\
       &=R \cdot (I_1^2 + I_2^2 + 2\cdot I_1 \cdot I_2)\\
  P &\neq P_1 + P_2
\end{align*}
#+end_export


** Teorema de Thévenin/Norton

*** Thévenin

Cualquier *red lineal* compuesta por elementos activos de corriente continua y pasivos puede sustituirse, desde el punto de vista de sus terminales externos AB, por una *fuente de tensión* (generador de Thévenin, $\epsilon_{th}$) en *serie* con una resistencia (resistencia de Thévenin, $R_{th}$).
 #+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/EquivalenteThevenin_R.pdf]]

*** Norton
Cualquier *red lineal* compuesta por elementos activos de corriente continua y pasivos puede sustituirse, desde el punto de vista de sus terminales externos AB, por una *fuente de corriente* (generador de Norton, $I_N$) en *paralelo* con una resistencia (resistencia de Norton, $R_N$).
 #+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/EquivalenteNorton_R.pdf]]

*** Cálculo del equivalente de Thévenin
#+ATTR_LATEX: :height 0.43\textheight
[[file:../figs/EquivalenteThevenin_R.pdf]]

- Circuito Abierto ($R_L \to \infty, \quad U_{AB} = U_{oc}$)
#+BEGIN_EXPORT latex
\[
\boxed{\epsilon_{th} = U_{oc}}
\]
#+END_EXPORT
- Cortocircuito ($R_L = 0, \quad I = I_{sc}$)
#+BEGIN_EXPORT latex
\[
\boxed{R_{th} = \frac{\epsilon_{th}}{I_{sc}} = \frac{U_{oc}}{I_{sc}}}
\]
#+END_EXPORT

*** Cálculo del equivalente de Norton
#+ATTR_LATEX: :height 0.43\textheight
[[file:../figs/EquivalenteNorton_R.pdf]]

- Cortocircuito ($R_L = 0, \quad I = I_{sc}$)
#+BEGIN_EXPORT latex
\[
\boxed{I_N = I_{sc}}
\]
#+END_EXPORT
- Circuito Abierto ($R_L \to \infty, \quad U_{AB} = U_{oc}$)
#+BEGIN_EXPORT latex
\[
\boxed{R_N = \frac{U_{oc}}{I_N} = \frac{U_{oc}}{I_{sc}}}
\]
#+END_EXPORT

*** Cálculo de Thévenin/Norton

**** Observaciones
- Cálculo de la impedancia:
  - Si el circuito *no* contiene fuentes dependientes, se puede realizar *apagando* todos los *generadores* y obteniendo la impedancia equivalente.
  - Si el circuito contiene fuentes dependientes, es necesario conectar un *generador de prueba* a la salida del circuito y obtener la relación entre la tensión y corriente de este generador.

- Gracias a la equivalencia de fuentes, una vez obtenido uno de los equivalentes se puede obtener el otro mediante una transformación.

** Teorema de máxima transferencia de potencia

*** Planteamiento
Sea el circuito lineal de la figura. ¿Qué resistencia $R_L$ hay que conectar en los terminales AB para que el circuito entregue la máxima potencia disponible?

#+ATTR_LATEX: :height 0.55\textheight
[[file:../figs/EquivalenteThevenin_R.pdf]]

Resolvemos esta pregunta mediante el generador equivalente de Thévenin.



*** Ecuaciones
Calculamos la potencia en la resistencia de carga $R_L$:
****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.45
    :END:
    #+ATTR_LATEX: :height 0.45\textheight
    [[file:../figs/EquivalenteThevenin0_R.pdf]]

****                                                               :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.45
    :END:
   #+begin_export latex
   \begin{align*}
   I &= \frac{\epsilon_{th}}{R_{th} + R_L}\\
   P_L &= I^2 \cdot R_L\\
   \Aboxed{P_L &= \frac{\epsilon^2_{th}}{R_{th} + R_L^2} \cdot R_L}
   \end{align*}
 #+end_export

****                                                     :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:


La condición de máximo es:
#+begin_export latex
\[
  \boxed{%
    \diff{P_L}{R_L} = 0%
  }
\]

 #+end_export

*** Resistencia
   #+begin_export latex
   \[
     P_L = \frac{\epsilon^2_{th}}{(R_{th} + R_L)^2} \cdot R_L
   \]
   #+end_export
Calculamos la derivada:
   #+begin_export latex
   \begin{align*}
     \diffp{P_L}{R_L} &= \epsilon^2_{th} \cdot \left[\frac{1}{(R_L + R_{th})^2} - 2 \cdot \frac{R_L}{(R_L + R_{th})^3}\right]\\
		      &= \frac{\epsilon^2_{th} \cdot (R_{th} - R_L)}{(R_L + R_{th})^3}
   \end{align*}
   #+end_export
Aplicamos la condición de máximo y obtenemos la resistencia:
   #+begin_export latex
   \[
      \diff{P_L}{R_L} = 0 \Rightarrow \boxed{R_L = R_{th}}
   \]
   #+end_export

*** Resistencia de carga

Dado un circuito lineal de corriente continua (del que podemos calcular su equivalente de Thévenin) ...
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/EquivalenteThevenin_R.pdf]]

... la resistencia de carga que hay que conectar entre sus terminales AB para obtener la máxima potencia disponible es:
#+begin_export latex
\[
  \boxed{R_L = R_{th}}
\]
#+end_export

*** Máxima potencia disponible

La máxima potencia disponible en la carga es:
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/EquivalenteThevenin_R.pdf]]

#+begin_export latex
\begin{equation*}
  \left.
    \begin{matrix}
      R_L = R_{th}\\
      P_L = \frac{\epsilon^2_{th}}{(R_{th} + R_L)^2} \cdot R_L
    \end{matrix} \right\}\rightarrow
  \boxed{P_L = \frac{\epsilon^2_{th}}{4 R_{th}}}
\end{equation*}
#+end_export

* Footnotes

[fn:1] Dos señales son ortogonales si cumplen la siguiente ecuación: \[<f_1, f_2>_T = \int_T f_1(t) \cdot f_2(t) dt = 0\] 

