#+TITLE: Transformadores
#+SUBTITLE: Teoría de Circuitos II
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: 
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:2

** Recordatorio

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

[[file:../figs/acoplamientoTikz.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+begin_export latex
\[
  L_1 = N_1 \frac{\phi_{11}}{i_1}
\]

\[
  L_2 = N_2 \frac{\phi_{22}}{i_2}
\]


\begin{align*}
  M &= N_1 \frac{\phi_{12}}{i_2}\\
    &= N_2 \frac{\phi_{21}}{i_1}
\end{align*}

\[
  M = k \sqrt{L_1 \cdot L_2}
\]
#+end_export

* Transformador Real

** Ecuaciones del Transformador Real
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/Trafo_Real.pdf]]

#+begin_export latex
\begin{align*}
  \overline{U}_1 &= (R_1 + j \omega L_1) \cdot \overline{I}_1 + j \omega M \cdot\overline{I}_2\\
  \overline{U}_2 &= j \omega M \cdot \overline{I}_1 + (R_2 + j \omega L_2) \cdot \overline{I}_2
\end{align*}
#+end_export

** Ejemplo: impedancia de entrada desde primario

#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/Trafo_Real_ImpSec.pdf]]

Ecuaciones del transformador
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= (R_1 + j \omega L_1) \cdot \overline{I}_1 + j \omega M \cdot\overline{I}_2\\
  \overline{U}_2 &= j \omega M \cdot \overline{I}_1 + (R_2 + j \omega L_2) \cdot \overline{I}_2
\end{align*}
#+end_export
Ecuación de la carga
#+begin_export latex
\[
  \overline{U}_2 = - \overline{I}_2 \cdot \overline{Z}_L
\]
#+end_export
** Ejemplo: impedancia de entrada desde primario

#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/Trafo_Real_ImpSec.pdf]]
Combinando la ecuación del secundario con la ecuación de la carga:
#+begin_export latex
\[
  \overline{I}_2  = - \frac{j \omega M}{(R_2 + j \omega L_2) + \overline{Z}_L} \cdot \overline{I}_1
\]
#+end_export

** Ejemplo: impedancia de entrada desde primario

#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/Trafo_Real_ImpSec.pdf]]
Combinando con la ecuación del primario:
#+begin_export latex
\[
  \overline{Z}_{in}  = \frac{\overline{U}_1}{\overline{I}_1} =  (R_1 + j \omega L_1) + \frac{\omega^2 M^2}{(R_2 + j \omega L_2) + \overline{Z}_L} = \boxed{\overline{Z}_1 + \frac{\omega^2 M^2}{\overline{Z}_2 + \overline{Z}_L}}
\]
#+end_export

** Ejemplo: Equivalente de Thévenin desde secundario
#+ATTR_LATEX: :height 0.8\textheight
[[file:../figs/Trafo_Real_FuentePrimario.pdf]]

** Tensión de Thévenin
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/Trafo_Real_FuentePrimario.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
Ecuación del generador:
#+begin_export latex
\[
  \overline{U}_1 = \overline{\epsilon}_g - \overline{I}_1 \cdot \overline{Z}_g
\]
#+end_export

Ecuaciones del transformador ($\overline{I}_2 = 0$)
#+begin_export latex
    \begin{align*}
      \overline{U}_1 &= (R_1 + j \omega L_1) \cdot \overline{I}_1\\
      \overline{U}_2 &= j \omega M \cdot \overline{I}_1
    \end{align*}
#+end_export

** Tensión de Thévenin
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/Trafo_Real_FuentePrimario.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
Despejamos $I_1$:
#+begin_export latex
\[
  \overline{I}_1 = \frac{\overline{\epsilon_g}}{\overline{Z}_1 + \overline{Z}_g}
\]
#+end_export

Tensión en abierto:
#+begin_export latex
\[
  \overline{U}_2 = \boxed{\overline{\epsilon}_{th} = \frac{j\omega M}{\overline{Z}_1 + \overline{Z}_g} \cdot \overline{\epsilon}_g}
\]
#+end_export
** Impedancia de Thévenin 
[[file:../figs/Trafo_Real_ImpedanciaPrimario.pdf]]
** Impedancia de Thévenin
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
[[file:../figs/Trafo_Real_ImpedanciaPrimario.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
Ecuaciones del transformador:
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= (R_1 + j \omega L_1) \cdot \overline{I}_1 + j \omega M \cdot\overline{I}_0\\
  \overline{\epsilon}_0 &= j \omega M \cdot \overline{I}_1 + (R_2 + j \omega L_2) \cdot \overline{I}_0
\end{align*}
#+end_export
Ecuación de la impedancia:
#+begin_export latex
\[
  \overline{U}_1 = - \overline{Z}_g \cdot \overline{I}_1
\]
#+end_export
Impedancia de Thévenin:
#+begin_export latex
\[
  \boxed{\overline{Z}_{th} = \frac{\overline{\epsilon}_0}{\overline{I}_0} = \overline{Z}_2 + \frac{\omega^2 M^2}{\overline{Z}_1 + \overline{Z}_g}}
\]
#+end_export
** Resumen: Equivalente de Thévenin
#+ATTR_LATEX: :height 0.45\textheight
file:../figs/Trafo_Real_FuentePrimario.pdf

#+begin_export latex
\[
  \boxed{\overline{\epsilon}_{th} = \frac{j\omega M}{\overline{Z}_1 + \overline{Z}_g} \cdot \overline{\epsilon}_g}
\]
#+end_export

#+begin_export latex
\[
  \boxed{\overline{Z}_{th} = \frac{\overline{\epsilon}_0}{\overline{I}_0} = \overline{Z}_2 + \frac{\omega^2 M^2}{\overline{Z}_1 + \overline{Z}_g}}
\]
#+end_export


* Transformador Perfecto
** Definición
#+ATTR_LATEX: :height 0.35\textheight
[[file:../figs/Trafo_Perfecto.pdf]]

Las pérdidas resistivas son despreciables.
#+begin_export latex
\[
  R_1 = R_2 = 0
\]
#+end_export

El acoplamiento es perfecto.
#+begin_export latex
\[
  k = 1
\rightarrow 
\left\{
\begin{array}{cc}
  \phi_{12} &= \phi_{22}\\
  \phi_{21} &= \phi_{11}\\
\end{array} \right.
\]
#+end_export
** Relación de Transformación
Retomamos las ecuaciones de $M_{12} = M_{21} = M$:
#+begin_export latex
\[
  N_1 \frac{\phi_{12}}{i_2} = N_2 \frac{\phi_{21}}{i_1}
\]
#+end_export

Con la condición $k=1$ escribimos:
#+begin_export latex
\[  
  N_1 \frac{\phi_{22}}{i_2} = N_2 \frac{\phi_{11}}{i_1}
\]
#+end_export

Y con las definiciones de $L_1$ y $L_2$:
#+begin_export latex
\[
  N_1 \frac{L_2}{N_2} = N_2 \frac{L_1}{N_1}
\]
#+end_export

Obtenemos la relación de transformación:
#+begin_export latex
\[
  \boxed{\frac{L_1}{L_2} = \left(\frac{N_1}{N_2}\right)^2 = a^2}
\]
#+end_export
** Ecuaciones del Transformador Perfecto
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/Trafo_Perfecto.pdf]]

#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega L_1 \cdot \overline{I}_1 + j \omega M \cdot \overline{I}_2\\
  \overline{U}_2 &= j \omega M \cdot \overline{I}_1 + j \omega L_2 \cdot \overline{I}_2
\end{align*}
#+end_export
** Relación de Tensiones
Dividiendo las ecuaciones:
#+begin_export latex
\[
  \frac{\overline{U}_1}{\overline{U}_2} = \frac{j \omega L_1 \cdot \overline{I}_1 + j \omega M \cdot \overline{I}_2}{j \omega M \cdot \overline{I}_1 + j \omega L_2 \cdot \overline{I}_2}
\]
#+end_export
Empleando la relación de transformación:
#+begin_export latex
\[
  \frac{L_1}{L_2} = a^2
  \rightarrow
  \left\{
  \begin{array}{ll}
    L_1 &= a^2 \cdot L_2\\
    M &= a \cdot L_2\\
  \end{array}\right.
\]
#+end_export
Obtenemos:
#+begin_export latex
\[
  \frac{\overline{U}_1}{\overline{U}_2} = \frac{a^2 L_2 \cdot \overline{I}_1 + a L_2 \cdot \overline{I}_2}{a L_2 \cdot \overline{I}_1 + L_2 \cdot \overline{I}_2}
\]
#+end_export

#+begin_export latex
\[
  \boxed{\frac{\overline{U}_1}{\overline{U}_2} = a = \frac{N_1}{N_2}}
\]
#+end_export
** Ejemplo: Impedancia de Entrada
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/TrafoPerfecto_ImpedanciaSecundario.pdf]]

Ecuaciones del transformador:
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega L_1 \cdot \overline{I}_1 + j \omega M \cdot \overline{I}_2\\
  \overline{U}_2 &= j \omega M \cdot \overline{I}_1 + j \omega L_2 \cdot \overline{I}_2
\end{align*}
#+end_export
Ecuación de la impedancia:
#+begin_export latex
\[
  \overline{U}_2 = - \overline{Z}_L \cdot \overline{I}_2
\]
#+end_export
** Ejemplo: Impedancia de Entrada
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/TrafoPerfecto_ImpedanciaSecundario.pdf]]
Despejamos $I_2$:
#+begin_export latex
\[
  \overline{I}_2 = - \frac{j \omega M}{j\omega L_2 + \overline{Z}_L} \cdot \overline{I}_1
\]
#+end_export
Y sustituimos:
#+begin_export latex
\[
  \overline{Z}_{in} = \frac{\overline{U}_1}{\overline{I}_1} = j\omega L_1 + \frac{\omega^2 M^2}{j\omega L_2 + \overline{Z}_L}
\]
#+end_export
** Ejemplo: Impedancia de Entrada
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/TrafoPerfecto_ImpedanciaSecundario.pdf]]

Teniendo en cuenta la relación entre $L_1$, $L_2$ y $M$:
#+begin_export latex
\[
  \overline{Z}_{in} = j\omega L_1 + \frac{\omega^2 M^2}{j\omega L_2 + \overline{Z}_L} = \frac{j\omega L_1 \overline{Z}_L}{j\omega L_2 + \overline{Z}_L} \rightarrow
\boxed{  \overline{Z}_{in} =  a^2 \cdot \frac{j \omega L_2 \cdot \overline{Z}_L}{j\omega L_2 + \overline{Z}_L} =  \frac{j \omega L_1 \cdot a^2 \cdot \overline{Z}_L}{j\omega L_1 + a^2 \cdot \overline{Z}_L}}  
\]
#+end_export
** Ejemplo: Equivalente de Thévenin desde secundario
#+ATTR_LATEX: :height 0.8\textheight
[[file:../figs/Trafo_Perfecto_FuentePrimario.pdf]]
** Tensión de Thévenin
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/Trafo_Perfecto_FuentePrimario.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
Ecuación del generador:
#+begin_export latex
\[
  \overline{U}_1 = \overline{\epsilon}_g - \overline{I}_1 \cdot \overline{Z}_g
\]
#+end_export

Ecuaciones del transformador ($\overline{I}_2 = 0$)
#+begin_export latex
    \begin{align*}
      \overline{U}_1 &= j \omega L_1 \cdot \overline{I}_1\\
      \overline{U}_2 &= j \omega M \cdot \overline{I}_1
    \end{align*}
#+end_export
Despejamos $I_1$:
#+begin_export latex
\[
  \overline{I}_1 = \frac{\overline{\epsilon_g}}{\overline{Z}_g + j\omega L_1}
\]
#+end_export

** Tensión de Thévenin
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/Trafo_Perfecto_FuentePrimario.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
Tensión en abierto:
#+begin_export latex
\[
  \overline{\epsilon}_{th} = \overline{U}_2 = \frac{j\omega M}{j\omega L_1 + \overline{Z}_g} \cdot \overline{\epsilon}_g
\]
#+end_export
Teniendo en cuenta que $M = L_1/a$:
#+begin_export latex
\[
  \overline{\epsilon}_{th} = \frac{1}{a} \cdot \left(\frac{j\omega L_1}{j\omega L_1 + \overline{Z}_g}\right) \cdot \overline{\epsilon}_g
\]
#+end_export
** Impedancia de Thévenin 
[[file:../figs/Trafo_Perfecto_ImpedanciaPrimario.pdf]]
** Impedancia de Thévenin
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
[[file:../figs/Trafo_Perfecto_ImpedanciaPrimario.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
Ecuaciones del transformador:
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega L_1 \cdot \overline{I}_1 + j \omega M \cdot\overline{I}_0\\
  \overline{\epsilon}_0 &= j \omega M \cdot \overline{I}_1 + j \omega L_2 \cdot \overline{I}_0
\end{align*}
#+end_export
Ecuación de la impedancia:
#+begin_export latex
\[
  \overline{U}_1 = - \overline{Z}_g \cdot \overline{I}_1
\]
#+end_export
Impedancia de Thévenin:
#+begin_export latex
\[
  \overline{Z}_{th} = \frac{\overline{\epsilon}_0}{\overline{I}_0} = j\omega L_2 + \frac{\omega^2 M^2}{j\omega L_1 + \overline{Z}_g}
\]
#+end_export
Con $L_2 = L_1/a^2$ y $M = L_1/a$:
#+begin_export latex
\[
  \overline{Z}_{th} = \frac{1}{a^2} \cdot \frac{j \omega L_1 \cdot \overline{Z}_g}{j\omega L_1 + \overline{Z}_g}
\]
#+end_export
** Resumen: Equivalente de Thévenin
#+ATTR_LATEX: :height 0.5\textheight
file:../figs/Trafo_Perfecto_FuentePrimario.pdf

#+begin_export latex
\[
  \overline{Z}_{th} = \frac{1}{a^2} \cdot \frac{j \omega L_1 \cdot \overline{Z}_g}{j\omega L_1 + \overline{Z}_g}
\]
#+end_export

#+begin_export latex
\[
  \overline{\epsilon}_{th} = \frac{1}{a} \cdot \left(\frac{j\omega L_1}{j\omega L_1 + \overline{Z}_g}\right) \cdot \overline{\epsilon}_g
\]
#+end_export


* Transformador Ideal
** Definición
#+ATTR_LATEX: :height 0.35\textheight
[[file:../figs/Trafo_Ideal.pdf]]

Las pérdidas resistivas son despreciables.
#+begin_export latex
\[
  R_1 = R_2 = 0
\]
#+end_export

El acoplamiento es perfecto.
#+begin_export latex
\[
  k = 1
\]
#+end_export

Las bobinas tienen un número muy elevado de espiras.
#+begin_export latex
\begin{align*}
  N_1 &\to \infty\\
  N_2 &\to \infty
\end{align*}
#+end_export
** El flujo en cada bobina es nulo
Para que las tensiones inducidas sean finitas... 

#+begin_export latex
\begin{align*}
  \overline{U}_1 &= N_1 \overline{\phi}_1\\ 
  \overline{U}_2 &= N_2 \overline{\phi}_2
\end{align*}
#+end_export
...los flujos (fasoriales) que los atraviesan deben ser nulos.
#+begin_export latex
\begin{align*}
  \overline{\phi}_1 &\to 0\\
  \overline{\phi}_2 &\to 0\\
\end{align*}
#+end_export
Siendo:
#+begin_export latex
\begin{align*}
  \overline{\phi}_1 &= \overline{\phi}_{11} + \overline{\phi}_{12}\\
  \overline{\phi}_2 &= \overline{\phi}_{22} + \overline{\phi}_{21}
\end{align*}
#+end_export
** El flujo mutuo es nulo
Teniendo en cuenta que el acoplamiento es perfecto, $k = 1$:
#+begin_export latex
\[
  \left.
    \begin{array}{ll}
      \phi_{12} &= \phi_{22}\\
      \phi_{21} &= \phi_{11}\\
    \end{array} \right\} 
  \rightarrow
  \left\{
    \begin{array}{ll}
      0 &= \overline{\phi}_{21} + \overline{\phi}_{12}\\
      0 &= \overline{\phi}_{12} + \overline{\phi}_{21}\\
    \end{array}\right.
\]
#+end_export

O también:

#+begin_export latex
\[
  \boxed{\overline{\phi}_{11} + \overline{\phi}_{22} = 0}
\]
#+end_export
** Relación de Transformación

Hemos obtenido:
#+begin_export latex
\[
  \overline{\phi}_{11} + \overline{\phi}_{22} = 0
\]
#+end_export

Con las definiciones de $L_1$, $L_2$:
#+begin_export latex
\[
  L_1 = N_1 \frac{\phi_{11}}{I_1}; \quad L_2 = N_2 \frac{\phi_{22}}{I_2}
\]
#+end_export
Podemos escribir:
#+begin_export latex
\[
  \frac{L_1 \overline{I}_1}{N_1} + \frac{L_2 \overline{I}_2}{N_2} = 0
\]
#+end_export
Y con la relación entre ambas obtenemos[fn:1]:
#+begin_export latex
\[
  L_1 = L_2 \cdot \left(\frac{N_1}{N_2}\right)^2
  \rightarrow
  \frac{N_1L_2 \overline{I}_1}{N^2_2} + \frac{L_2 \overline{I}_2}{N_2} = 0
  \rightarrow
  \boxed{\frac{\overline{I}_1}{\overline{I}_2} = {\color{red}-} \frac{1}{a} = {\color{red}-} \frac{N_2}{N_1}}
\]
#+end_export
** Un transformador ideal no consume potencia

#+begin_export latex
\[
  \overline{S}_1 = \overline{U}_1 \cdot \overline{I}_1^*
\]
#+end_export

#+begin_export latex
\[
  \overline{S}_2 = \overline{U}_2 \cdot \overline{I}_2^* 
\]
#+end_export

#+begin_export latex
\[
  \overline{U}_2 \cdot \overline{I}_2^* = \frac{1}{a} \cdot \overline{U}_1 \cdot a \cdot \overline{I}_1^* = \overline{S}_1
\]
#+end_export

#+begin_export latex
\[
  \boxed{\overline{S}_1 = \overline{S}_2}
  \quad
  \boxed{P_1 = P_2}
  \quad
  \boxed{Q_1 = Q_2}
\]
#+end_export
* Transferencia de Circuitos
** Fuente de Tensión de Secundario a Primario
[[file:../figs/TrafoIdeal_VSec.pdf]]

#+begin_export latex
\[
  \overline{U}_1 = a \cdot \overline{U}_2 \rightarrow \boxed{\overline{\epsilon}_{g1} = a \cdot \overline{\epsilon}_g}
\]
#+end_export
** Fuente de Tensión de Primario a Secundario
[[file:../figs/TrafoIdeal_VPrim.pdf]]

#+begin_export latex
\[
  \overline{U}_2 = \overline{U}_1 / a \rightarrow \boxed{\overline{\epsilon}_{g2} = \overline{\epsilon}_g / a}
\]
#+end_export
** Fuente de Corriente de Secundario a Primario
[[file:../figs/TrafoIdeal_ISec.pdf]]

#+begin_export latex
\[
  \overline{I}_1 = \overline{I}_2 / a \rightarrow \boxed{\overline{I}_{g1} = \overline{I}_g / a} 
\]
#+end_export
** Fuente de Corriente de Primario a Secundario
[[file:../figs/TrafoIdeal_IPrim.pdf]]
#+begin_export latex
\[
  \overline{I}_2 = a \cdot \overline{I}_1 \rightarrow \boxed{\overline{I}_{g2} = a \cdot \overline{I}_g}
\]
#+end_export
** Impedancia de Secundario a Primario
[[file:../figs/TrafoIdeal_ZSec.pdf]]
#+begin_export latex
\[
  \left.
    \begin{array}{ll}
    \overline{U}_1 &= a \cdot \overline{U}_2\\
    \overline{I}_1 &= \overline{I}_2 / a\\
  \end{array}\right\}
   \rightarrow \boxed{\overline{Z}_1 = \frac{\overline{U}_1}{\overline{I}_1} = a^2 \cdot \overline{Z}} 
\]
#+end_export
** Impedancia de Primario a Secundario
[[file:../figs/TrafoIdeal_ZPrim.pdf]]
#+begin_export latex
\[
  \left.
    \begin{array}{ll}
    \overline{U}_2 &= \overline{U}_1 /a\\
    \overline{I}_2 &= a \cdot \overline{I}_1\\
  \end{array}\right\}
   \rightarrow \boxed{\overline{Z}_2 = \frac{\overline{U}_2}{\overline{I}_2} = \overline{Z} / a^2} 
\]
#+end_export
* Transformador Perfecto vs. Transformador Ideal
** Recordatorio: impedancia de entrada de un T. Perfecto
#+ATTR_LATEX: :height 0.45\textheight
[[file:../figs/TrafoPerfecto_ImpedanciaSecundario.pdf]]

#+begin_export latex
\[
  \boxed{\overline{Z}_{in} = \frac{j \omega L_1 \cdot (a^2 \overline{Z}_L)}{j\omega L_1 + (a^2 \cdot \overline{Z}_L)}}
\]

\[
  \boxed{\overline{Z}_{in} = a^2 \cdot \frac{j \omega L_2 \cdot \overline{Z}_L}{j\omega L_2 + \overline{Z}_L}}
\]
#+end_export
** Circuito equivalente con transformador ideal
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/TrafoPerfecto_Ideal.pdf]]

#+begin_export latex
\[
  \boxed{\overline{Z}_{in} = \frac{j \omega L_1 \cdot (a^2 \overline{Z}_L)}{j\omega L_1 + (a^2 \cdot \overline{Z}_L)}}
\]
#+end_export
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/TrafoPerfecto_Ideal2.pdf]]

#+begin_export latex
\[
  \boxed{\overline{Z}_{in} = a^2 \cdot \frac{j \omega L_2 \cdot \overline{Z}_L}{j\omega L_2 + \overline{Z}_L}}
\]
#+end_export

** Recordatorio: Equivalente de Thévenin
#+ATTR_LATEX: :height 0.5\textheight
file:../figs/Trafo_Perfecto_FuentePrimario.pdf

#+begin_export latex
\[
  \overline{Z}_{th} = \frac{1}{a^2} \cdot \frac{j \omega L_1 \cdot \overline{Z}_g}{j\omega L_1 + \overline{Z}_g}
\]
#+end_export

#+begin_export latex
\[
  \overline{\epsilon}_{th} = \frac{1}{a} \cdot \left(\frac{j\omega L_1}{j\omega L_1 + \overline{Z}_g}\right) \cdot \overline{\epsilon}_g
\]
#+end_export

** Equivalente en primario con transformador ideal

#+begin_export latex
\[
  \overline{Z}_{th} = \frac{1}{a^2} \cdot \frac{j \omega L_1 \cdot \overline{Z}_g}{j\omega L_1 + \overline{Z}_g}
\]
#+end_export

#+begin_export latex
\[
  \overline{\epsilon}_{th} = \frac{1}{a} \cdot \left(\frac{j\omega L_1}{j\omega L_1 + \overline{Z}_g}\right) \cdot \overline{\epsilon}_g
\]
#+end_export

#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/TrafoPerfecto_Ideal_FuentePrim.pdf]]
** Equivalente en secundario con transformador ideal
#+begin_export latex
\[
  \overline{Z}_{th} = a^2 \cdot \frac{j \omega L_2 \cdot \overline{Z}_g}{j\omega L_2 + \overline{Z}_g}
\]
#+end_export

#+begin_export latex
\[
  \overline{\epsilon}_{th} = a \cdot \left(\frac{j\omega L_2}{j\omega L_2 + \overline{Z}_g}\right) \cdot \overline{\epsilon}_g
\]
#+end_export

#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/TrafoPerfecto_Ideal_FuenteSec.pdf]]
* Transformador de Varios Devanados
** Transformador Real de Varios Devanados
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/TrafoVariosDevanados.pdf]]

** Ecuaciones del Transformador Real
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/TrafoVariosDevanados.pdf]]

#+begin_export latex
\begin{align*}
  \overline{U}_1 &= (R_1 + j \omega L_1) \cdot \overline{I}_1 + j \omega M_{12} \cdot\overline{I}_2 + j \omega M_{13} \cdot\overline{I}_3\\
  \overline{U}_2 &= j \omega M_{12} \cdot \overline{I}_1 + (R_2 + j \omega L_2) \cdot \overline{I}_2 + j \omega M_{23} \cdot \overline{I}_3\\
  \overline{U}_3 &= j \omega M_{13} \cdot \overline{I}_1 + j \omega M_{12} \cdot\overline{I}_2 + (R_3 + j \omega L_3) \cdot \overline{I}_3
\end{align*}
#+end_export

** Transformador Perfecto

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
#+ATTR_LATEX: :height 0.8\textheight
[[file:../figs/TrafoPerfectoVariosDevanados.pdf]]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
Las pérdidas resistivas son despreciables.
#+begin_export latex
\[
  R_1 = R_2 = R_3 = 0
\]
#+end_export

El acoplamiento es perfecto.
#+begin_export latex
\[
  k_{12} = k_{13} = k_{23} = 1
\]
#+end_export

** Ecuaciones del Transformador Perfecto
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/TrafoPerfectoVariosDevanados.pdf]]

#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega L_1 \cdot \overline{I}_1 + j \omega M_{12} \cdot\overline{I}_2 + j \omega M_{13} \cdot\overline{I}_3\\
  \overline{U}_2 &= j \omega M_{12} \cdot \overline{I}_1 + j \omega L_2 \cdot \overline{I}_2 + j \omega M_{23} \cdot \overline{I}_3\\
  \overline{U}_3 &= j \omega M_{13} \cdot \overline{I}_1 + j \omega M_{12} \cdot\overline{I}_2 + j \omega L_3 \cdot \overline{I}_3
\end{align*}
#+end_export

** Relaciones de Transformación

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/TrafoPerfectoVariosDevanados.pdf]]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+begin_export latex
\begin{align*}
  \frac{L_1}{L_2} &= \left(\frac{N_1}{N_2}\right)^2 = a^2_{12}\\
  \frac{L_1}{L_3} &= \left(\frac{N_1}{N_3}\right)^2 = a^2_{13}
\end{align*}

\begin{align*}
  \frac{\overline{U}_1}{\overline{U}_2} &= a_{12}\\
  \frac{\overline{U}_1}{\overline{U}_3} &= a_{13}
\end{align*}
#+end_export

** Transformador Ideal
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/TrafoIdealVariosDevanados.pdf]]

** Relación de Transformación del Transformador Ideal

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
Debido a las condiciones de idealidad:

#+begin_export latex
\[
  \overline{\phi}_{11} + \overline{\phi}_{22} + \overline{\phi}_{33} = 0
\]

\[
  N_1 \overline{I}_1 + N_ 2\overline{I}_2 + N_3 \overline{I}_{3} = 0
\]

#+end_export

En términos de corriente:
#+begin_export latex
\[
  \boxed{\overline{I}_1 = {\color{red}-} 1/a_{12} \cdot \overline{I}_2 {\color{red}-} 1/a_{13} \cdot  \overline{I}_3}
\]
#+end_export
Si las corrientes $I_2$ e $I_3$ son salientes, en la ecuación anterior los signos serán positivos.
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/TrafoIdealVariosDevanados.pdf]]


** Impedancia de Entrada
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/TrafoIdealVariosDevanados_Impedancia.pdf]]


** Impedancia de Entrada[fn:2]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
[[file:../figs/TrafoIdealVariosDevanados_Impedancia.pdf]]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
Ecuaciones del transformador:
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= \overline{U}_2 \cdot a_{12}\\
  \overline{U}_1 &= \overline{U}_3 \cdot a_{13}\\
  \overline{I}_1 &= 1/a_{12} \cdot \overline{I}_2 + 1/a_{13} \cdot  \overline{I}_3
\end{align*}
#+end_export

Ecuaciones Terminales
#+begin_export latex
\begin{align*}
  \overline{U}_2 &= \overline{Z}_2 \cdot \overline{I}_2\\
  \overline{U}_3 &= \overline{Z}_3 \cdot \overline{I}_3
\end{align*}
#+end_export

Resultado:
#+begin_export latex
\[
  \frac{\overline{I}_1}{\overline{U}_1} = \boxed{\overline{Y}_{in} = \frac{1}{a^2_{12} \overline{Z}_2} +  \frac{1}{a^2_{13} \overline{Z}_3}}
\]
#+end_export

** Circuito Equivalente

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/TrafoIdealVariosDevanados_Impedancia.pdf]]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/TrafoIdealVariosDevanados_Impedancia_Equivalente.pdf]]


** Circuito Equivalente de un Transformador Perfecto
\vspace{0.3cm}
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:BEAMER_opt: t
:END:

Transformador Perfecto
#+ATTR_LATEX: :width \textwidth
[[file:../figs/TrafoPerfectoVariosDevanados_Impedancia.pdf]]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:BEAMER_opt: t
:END:

Equivalente Ideal
#+ATTR_LATEX: :width \textwidth
[[file:../figs/TrafoPerfectoIdealVariosDevanados_Impedancia.pdf]]


** Circuito Equivalente de un Transformador Perfecto

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :width \textwidth
[[file:../figs/TrafoPerfectoIdealVariosDevanados_Impedancia.pdf]]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :width \textwidth
[[file:../figs/TrafoPerfectoVariosDevanados_Impedancia_Equivalente.pdf]]
* Autotransformador
** Autotransformador Perfecto
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/AutotrafoPerfecto.pdf]]


** Ecuaciones del Autotransformador Perfecto
#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/AutotrafoPerfecto.pdf]]
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega L_1 \cdot \overline{I}_1 + j \omega (M + L_2) \cdot \overline{I}_2\\
  \overline{U}_2 &= j \omega (M + L_2) \cdot \overline{I}_1 + j \omega L_2 \cdot \overline{I}_2\\
  M &= \sqrt{L' \cdot L_2}
\end{align*}
#+end_export
** Circuito Alternativo del Autotransformador Perfecto
#+ATTR_LATEX: :height 0.8\textheight
[[file:../figs/AutotrafoPerfecto2.pdf]]

** Ecuaciones del Circuito Alternativo
#+ATTR_LATEX: :height 0.5\textheight
[[file:../figs/AutotrafoPerfecto2.pdf]]
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega (L' + L_2 + 2M) \cdot \overline{I}_1 + j \omega (L_2 + M) \cdot \overline{I}_2\\
  \overline{U}_2 &= j \omega (L_2 + M) \cdot \overline{I}_1 + j \omega L_2 \cdot \overline{I}_2
\end{align*}
#+end_export

** Ecuaciones Comparadas

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/AutotrafoPerfecto.pdf]]
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega{\color{blue} L_1} \cdot \overline{I}_1 + j \omega{\color{red} (M + L_2)} \cdot \overline{I}_2\\
  \overline{U}_2 &= j \omega{\color{red} (L_2 + M)} \cdot \overline{I}_1 + j \omega{\color{PineGreen} L_2} \cdot \overline{I}_2 
\end{align*}

#+end_export
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:
#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/AutotrafoPerfecto2.pdf]]
#+begin_export latex
\begin{align*}
  \overline{U}_1 &= j \omega{\color{blue} (L' + L_2 + 2M)} \cdot \overline{I}_1 + j \omega{\color{red} (M + L_2)} \cdot \overline{I}_2\\
  \overline{U}_2 &= j \omega{\color{red} (L_2 + M)} \cdot \overline{I}_1 + j \omega{\color{PineGreen} L_2} \cdot \overline{I}_2
\end{align*}

#+end_export
***                                                       :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+begin_export latex
\begin{align*}
  L_1 &= L' + L_2 + 2M\\
  M &= \sqrt{L' \cdot L_2}
\end{align*}
#+end_export

** Transformador Perfecto Equivalente
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/AutotrafoPerfecto.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/AutoTrafo_TrafoPerfecto.pdf]]

#+begin_export latex
\begin{align*}
  L_1 &= L' + L_2 + 2M\\
  M' &= M + L_2
\end{align*}
#+end_export
** Transformador Perfecto Equivalente
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/AutotrafoPerfecto.pdf]]
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.33\textheight
[[file:../figs/AutoTrafo_TrafoPerfecto.pdf]]

Comprobamos:
#+begin_export latex
\begin{align*}
  M' &= \sqrt{L_1 \cdot L_2} = \\
     &= \sqrt{(L' + L_2 + 2M) L_2} =\\
     &= \sqrt{L'L_2 + L_2^2 + 2ML_2} =\\
     &= \sqrt{M^2 + L_2^2 + 2ML_2} = \\
     &= M + L_2
\end{align*}
#+end_export
** Equivalente del Autotransformador Ideal
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:BEAMER_opt: [b]
:END:
[[file:../figs/AutoTrafoIdeal.pdf]]

***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:BEAMER_opt: [b]
:END:
[[file:../figs/Trafo_Ideal2.pdf]]

***                                                      :B_beamercolorbox:
:PROPERTIES:
:BEAMER_env: beamercolorbox
:END:
#+begin_export latex
\begin{align*}
  \frac{U_1}{U_2} &= \frac{N_1}{N_2} = a\\
  \frac{I_1}{I_2} &= - \frac{N_2}{N_1} = - \frac{1}{a}
\end{align*}
#+end_export
* Footnotes
[fn:2]Las corrientes en 2 y 3 son salientes, y por tanto, en la ecuación de corrientes usamos el signo positivo. 

[fn:1]Si las dos corrientes van en el mismo sentido, la ecuación tendrá un signo positivo.
