#+TITLE: Técnicas Generales de Análisis
#+SUBTITLE: Teoría de Circuitos II
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: 
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:3

* Leyes de Kirchhoff

*** Nudo, rama, malla
  - Nudo :: unión de *3* o más conductores.
  - Rama :: elementos conectados entre dos nudos consecutivos.
  - Lazo :: conjunto de ramas que forman un camino cerrado.
  - Malla :: lazo que no contiene ningún otro en su interior.

#+ATTR_LATEX: :height 0.5\textheight
file:../figs/mallas.pdf

*** Ley de Kirchhoff de las Corrientes (LKC)
- La *LKC* es el principio de conservación de la carga aplicado a los circuitos eléctricos.

- *LKC*: la suma de las corrientes que llegan a un nudo es igual a la suma de las que salen.

  - Las lineas de corriente son cerradas (o solenoidales).

#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/LKC_FM.pdf]]
#+BEGIN_EXPORT latex
\[
i_1(t) - i_2(t) + i_3(t) - i_4(t) + i_5(t) = 0
\]
#+END_EXPORT

*** Ley de Kirchhoff de los Voltajes (LKV)
- La *LKV* es el principio de conservación de la energía aplicado a los circuitos eléctricos.

- *LKV*: la suma (con signo) de las tensiones a lo largo de un camino cerrado (circuito) es cero.

  - La energía producida por un generador es consumida por los receptores del circuito para producir trabajo (mecánico, químico, etc.) o calor.

#+ATTR_LATEX: :height 0.4\textheight
[[file:../figs/LKV_FM.pdf]]
#+BEGIN_EXPORT latex
\[
u_3(t) + u_4 (t) - u_5 (t) - u_1 (t) - u_2 (t)  = 0
\]
#+END_EXPORT

** Asociación de condensadores

*** Zona aislada

En una asociación de 3 o más condensadores pueden aparecer zonas aisladas (puntos a los que no se puede llegar sin atravesar un condensador.)

#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/CondensadoresZonaAislada.pdf]]

La tensión en estas zonas aisladas no se puede determinar de forma directa a partir del resto del circuito.

*** Método de resolución (1)

Se asignan polaridades arbitrarias a los condensadores.

#+ATTR_LATEX: :height 0.8\textheight
[[file:../figs/CondensadoresZonaAislada_Tensiones.pdf]]

*** Método de resolución (2)

La suma de cargas en una zona aislada es nula si los condensadores no tienen carga inicial, o igual a la suma total de las cargas iniciales.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.75\textheight
[[file:../figs/CondensadoresZonaAislada_Tensiones.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  (C) &\quad q_1 + q_5 + q_3 = 0\\
  (D) &\quad q_5 - q_2 - q_4 = 0
\end{align*}
#+end_export

*** Método de resolución (3)

Se aplica la LKV a las mallas que sean necesarias para completar el sistema de ecuaciones (usando $u_{Ci} = q_i/C_i$).
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+ATTR_LATEX: :height 0.75\textheight
[[file:../figs/CondensadoresZonaAislada_Tensiones.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+begin_export latex
\begin{align*}
  (ACDA) &\quad \frac{q_1}{C_1} - \frac{q_5}{C_5} - \frac{q_2}{C_2} = 0\\
  (CBDC) &\quad -\frac{q_3}{C_3} + \frac{q_4}{C_4} + \frac{q_5}{C_5} = 0\\
  (ACBA) &\quad \frac{q_1}{C_1} - \frac{q_3}{C_3} - u_{AB} = 0
\end{align*}
#+end_export

*** Método de resolución (y 4)

Se resuelve el sistema de ecuaciones para obtener los valores de $q_i$.

#+begin_export latex
\begin{align*}
  q_1 + q_5 + q_3 &= 0\\
  q_5 - q_2 - q_4 &= 0\\
  \frac{q_1}{C_1} - \frac{q_5}{C_5} - \frac{q_2}{C_2} &= 0\\
  -\frac{q_3}{C_3} + \frac{q_4}{C_4} + \frac{q_5}{C_5} &= 0\\
  \frac{q_1}{C_1} - \frac{q_3}{C_3} &= u_{AB}
\end{align*}
#+end_export



* Métodos de Análisis

** Método de las mallas

*** 
#+ATTR_LATEX: :height 0.95\textheight
[[file:../figs/mallas1_corrientes.pdf]]

*** Ecuación General
#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    {\color{BrickRed}\sum \overline{Z}_{aa}} &  - {\color{MidnightBlue}\sum \overline{Z}_{ab}} & - {\color{MidnightBlue}\sum \overline{Z}_{ca}} \\
    - {\color{MidnightBlue}\sum \overline{Z}_{ab}} & {\color{BrickRed}\sum \overline{Z}_{bb}} & - {\color{MidnightBlue}\sum \overline{Z}_{bc}} \\
    - {\color{MidnightBlue}\sum \overline{Z}_{ca}} & - {\color{MidnightBlue}\sum \overline{Z}_{bc}} &  {\color{BrickRed}\sum \overline{Z}_{cc}}
  \end{bmatrix} \cdot %
  \begin{bmatrix}
    \overline{I}_a\\
    \overline{I}_b\\
    \overline{I}_c\\
  \end{bmatrix} = %
  \begin{bmatrix}
    {\color{OliveGreen}\sum\overline{\epsilon}_a}\\
    {\color{OliveGreen}\sum\overline{\epsilon}_b}\\
    {\color{OliveGreen}\sum\overline{\epsilon}_c}
  \end{bmatrix}
\end{equation*}
#+end_export
- ${\color{BrickRed}\sum \overline{Z}_{aa}}$ :: suma de las impedancias incluidas en la malla de $\overline{I}_a$.
- ${\color{MidnightBlue}\sum \overline{Z}_{ab}}$ :: suma de las impedancias incluidas en las ramas compartidas por las mallas de $\overline{I}_a$ e $\overline{I}_b$.
- ${\color{OliveGreen}\sum \overline{\epsilon}_a}$ :: suma algebraica de las fuerzas electromotrices de los generadores de la malla de $\overline{I}_a$. Su signo es positivo si contribuyen al giro de la corriente.
*** Procedimiento

1. Identificar las corrientes de rama.
2. Asignar un sentido a las corrientes de malla.
3. Relacionar corrientes de rama con corrientes de malla.
4. Escribir ecuación de mallas.
5. Resolver la ecuación, obteniendo las corrientes de malla.
6. Obtener las corrientes de rama con las relaciones del punto 3.

*Importante*: todos los generadores deben ser fuentes de tensión.

*** Admitancia generalizada

#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    \overline{Z}_{11} & \overline{Z}_{12} & \dots & \overline{Z}_{1n} \\
    \overline{Z}_{21} & \overline{Z}_{22} & \dots & \overline{Z}_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    \overline{Z}_{n1} & \overline{Z}_{n2} &  \dots & \overline{Z}_{nn}
  \end{bmatrix} \cdot %
  \begin{bmatrix}
    \overline{I}_1\\
    \overline{I}_2\\
    \vdots \\
    \overline{I}_n\\
  \end{bmatrix} = %
  \begin{bmatrix}
    \overline{\epsilon}_1\\
    \overline{\epsilon}_2\\
    \vdots \\
    \overline{\epsilon}_n
  \end{bmatrix}
\end{equation*}

#+end_export
Aplicando la regla de Cramer
#+begin_export latex
\[
  \overline{I}_k = \overline{\epsilon}_1 \frac{\Delta_{1k}}{|Z|} + \overline{\epsilon}_2 \frac{\Delta_{2k}}{|Z|} + \dots + \overline{\epsilon}_n \frac{\Delta_{nk}}{|Z|}
\]
#+end_export
siendo $\Delta_{ij}$ el adjunto del elemento $ij$ de la matriz $Z$:
#+begin_export latex
\[
  \Delta_{ij} = (-1)^{i+j} \cdot |M_{ij}|
\]
#+end_export
donde $M_{ij}$ es la matriz resultante de eliminar la fila $i$ y la columna $k$ de la matriz $Z$.

*** Admitancia generalizada

Esta expresión indica que las respuestas del circuito ($I_k$) dependen de todas las excitaciones que existan ($\epsilon_i$):
#+begin_export latex
\[
  \overline{I}_k = \overline{\epsilon}_1 \frac{\Delta_{1k}}{|Z|} + \overline{\epsilon}_2 \frac{\Delta_{2k}}{|Z|} + \dots + \overline{\epsilon}_n \frac{\Delta_{nk}}{|Z|}
\]
#+end_export
También se puede definir la admitancia generalizada entre dos partes del circuito:
#+begin_export latex
\[
  \overline{Y}_{ki} = \frac{\overline{I}_k}{\overline{\epsilon}_i} = \frac{\Delta_{ik}}{|Z|}
\]
#+end_export

*** Impedancia de Entrada

A partir de esta expresión se puede calcular la impedancia de entrada vista por una fuente que alimenta un circuito pasivo (todas las fuentes salvo la de entrada son nulas en la expresión anterior):

#+begin_export latex
\[
  \overline{I}_1 = \overline{\epsilon}_1 \frac{\Delta_{11}}{|Z|} + 0 \cdot \frac{\Delta_{21}}{|Z|} + \dots + 0 \cdot \frac{\Delta_{n1}}{|Z|}
\]
#+end_export
Por tanto:
#+begin_export latex
\[
  \boxed{\overline{Z}_{in} = \frac{\overline{\epsilon}_1}{\overline{I}_1}=  \frac{|Z|}{\Delta_{11}}}
\]
#+end_export

*** Impedancia de Transferencia

También se puede calcular la impedancia de transferencia de un circuito pasivo, es decir, la impedancia entre dos partes del circuito en las que la primera está alimentada por una fuente, y la segunda está cortocircuitada.

En este caso, todas las fuentes salvo la de interés están apagadas:

#+begin_export latex
\[
  \overline{I}_k = 0 \cdot \frac{\Delta_{1k}}{|Z|} + 0 \cdot \frac{\Delta_{2k}}{|Z|} + \dots + \epsilon_j \cdot \frac{\Delta_{jk}}{|Z|} + 0 \cdot \frac{\Delta_{nk}}{|Z|}
\]
#+end_export
Por tanto:
#+begin_export latex
\[
  \boxed{\overline{Z}_{Tjk} = \frac{\overline{\epsilon}_j}{\overline{I}_k}=  \frac{|Z|}{\Delta_{jk}}}
\]
#+end_export


*** Mallas con fuentes de intensidad ideales

- Si la fuente de corriente está en una rama que pertenece a una única malla, se fija la corriente de dicha malla igual a la corriente de la fuente (desaparece una incógnita del sistema).
- Si la fuente de corriente está en una rama que pertenece a dos mallas:
  - Se introduce la tensión en la fuente de corriente como variable adicional.
  - Se plantean las ecuaciones del método de mallas.
  - la variable adicional (tensión de la fuente) se elimina sumando las dos ecuaciones de las mallas afectadas.
  - Se añade una ecuación que relaciona la corriente de la fuente con las dos corrientes de malla.
*** Mallas con fuentes dependientes
- Se plantean las ecuaciones de mallas como si no hubiese fuentes dependientes.
- Se añade la ecuación de la fuente dependiente como una ecuación adicional.
- La matriz de impedancias deja de ser simétrica.

** Método de los nudos
*** 
[[file:../figs/nudosAC.pdf]]

*** Ecuación general

#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    {\color{BrickRed}\sum \overline{Y}_A} & - {\color{MidnightBlue}\sum \overline{Y}_{AB}} & - {\color{MidnightBlue}\sum \overline{Y}_{AC}}\\
    -{\color{MidnightBlue}\sum \overline{Y}_{AB}} & {\color{BrickRed}\sum \overline{Y}_B} & -{\color{MidnightBlue}\sum \overline{Y}_{BC}}\\
    -{\color{MidnightBlue}\sum \overline{Y}_{AC}} & -{\color{MidnightBlue}\sum \overline{Y}_{BC}} & {\color{BrickRed}\sum \overline{Y}_C}
  \end{bmatrix} \cdot%
  \begin{bmatrix}
    \overline{V}_A\\
    \overline{V}_B\\
    \overline{V}_C
  \end{bmatrix} = %
  \begin{bmatrix}
    {\color{OliveGreen}\sum \overline{I}_{gA}}\\
    {\color{OliveGreen}\sum \overline{I}_{gB}}\\
    {\color{OliveGreen}\sum \overline{I}_{gC}}
  \end{bmatrix}
\end{equation*}
#+end_export

- ${\color{BrickRed}\sum \overline{Y}_A}$ :: Suma de las admitancias conectadas al nudo $A$.
- ${\color{MidnightBlue}\sum \overline{Y}_{AB}}$ :: Suma de las admitancias conectadas entre los nudos $A$ y $B$.
- ${\color{OliveGreen}\sum \overline{I}_{gA}}$ :: Suma de las corrientes de los generadores conectados en el nudo A. El signo es positivo si el generador inyecta corriente en el nudo.

*Importante*: todos los generadores deben ser fuentes de corriente.

*** Impedancia generalizada
#+begin_export latex
\begin{equation*}
  \begin{bmatrix}
    \overline{Y}_{11} & \overline{Y}_{12} & \dots & \overline{Y}_{1n} \\
    \overline{Y}_{21} & \overline{Y}_{22} & \dots & \overline{Y}_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    \overline{Y}_{n1} & \overline{Y}_{n2} &  \dots & \overline{Y}_{nn}
  \end{bmatrix} \cdot %
  \begin{bmatrix}
    \overline{V}_1\\
    \overline{V}_2\\
    \vdots \\
    \overline{V}_n\\
  \end{bmatrix} = %
  \begin{bmatrix}
    \overline{I}_{g1}\\
    \overline{I}_{g2}\\
    \vdots \\
    \overline{I}_{gn}
  \end{bmatrix}
\end{equation*}

#+end_export
Aplicando la regla de Cramer
#+begin_export latex
\[
  \overline{V}_k = \overline{I}_{g1} \frac{\Delta_{1k}}{|Y|} + \overline{I}_{g2} \frac{\Delta_{2k}}{|Y|} + \dots + \overline{I}_{gn} \frac{\Delta_{nk}}{|Y|}
\]
#+end_export
siendo $\Delta_{ij}$ el adjunto del elemento $ij$ de la matriz $Y$:
#+begin_export latex
\[
  \Delta_{ij} = (-1)^{i+j} \cdot |M_{ij}|
\]
#+end_export
donde $M_{ij}$ es la matriz resultante de eliminar la fila $i$ y la columna $k$ de la matriz $Y$.

*** Impedancia generalizada

Esta expresión indica que las respuestas del circuito ($V_k$) dependen de todas las excitaciones que existan ($I_{gi}$):
#+begin_export latex
\[
  \overline{V}_k = \overline{I}_{g1} \frac{\Delta_{1k}}{|Y|} + \overline{I}_{g2} \frac{\Delta_{2k}}{|Y|} + \dots + \overline{I}_{gn} \frac{\Delta_{nk}}{|Y|}
\]
#+end_export
También se puede definir la impedancia generalizada entre dos partes del circuito:
#+begin_export latex
\[
  \overline{Z}_{ki} = \frac{\overline{V}_k}{\overline{I}_{gi}} = \frac{\Delta_{ik}}{|Y|}
\]
#+end_export

*** Admitancia de Entrada

A partir de esta expresión se puede calcular la admitancia de entrada vista por una fuente que alimenta un circuito pasivo (todas las fuentes salvo la de entrada son nulas en la expresión anterior):

#+begin_export latex
\[
  \overline{V}_1 = \overline{I}_{g1} \frac{\Delta_{11}}{|Y|} + 0 \cdot \frac{\Delta_{21}}{|Y|} + \dots + 0 \cdot \frac{\Delta_{n1}}{|Y|}
\]
#+end_export
Por tanto:
#+begin_export latex
\[
  \boxed{\overline{Y}_{in} = \frac{\overline{I}_{g1}}{\overline{V}_1}=  \frac{|Y|}{\Delta_{11}}}
\]
#+end_export

*** Admitancia de Transferencia

También se puede calcular la admitancia de transferencia de un circuito pasivo, es decir, la admitancia entre dos partes del circuito en las que la primera está alimentada por una fuente, y la segunda está en abierto.

En este caso, todas las fuentes salvo la de interés están apagadas:

#+begin_export latex
\[
  \overline{V}_k = 0 \cdot \frac{\Delta_{1k}}{|Y|} + 0 \cdot \frac{\Delta_{2k}}{|Y|} + \dots + I_{gj} \cdot \frac{\Delta_{jk}}{|Y|} + 0 \cdot \frac{\Delta_{nk}}{|Y|}
\]
#+end_export
Por tanto:
#+begin_export latex
\[
  \boxed{\overline{Y}_{Tjk} = \frac{\overline{I}_{gj}}{\overline{V}_k}=  \frac{|Y|}{\Delta_{jk}}}
\]
#+end_export


*** Nudos con fuentes de tensión ideales

- Si la fuente de tensión está conectada entre el nudo de referencia y otro nudo cualquiera, se fija la tensión de este último igual a la tensión de la fuente.
- Si la fuente de tensión está conectada entre dos nudos, no siendo ninguno de ellos de referencia:
  - Se introduce la corriente que atraviesa la fuente como variable adicional.
  - Se plantean las ecuaciones del método de nudos.
  - Se elimina la variable adicional (corriente de la fuente de tensión) sumando las ecuaciones de nudos afectadas.
  - Se añade una ecuación que relaciona la tensión de la fuente con las dos tensiones nodales.
    
*** Nudos con fuentes de tensión ideales: supernudos

Si la fuente de tensión está conectada entre dos nudos, no siendo ninguno de ellos de referencia, estos dos nudos se pueden considerar como un único supernudo:
  - Este supernudo no tiene tensión propia.
  - Se plantean las ecuaciones de nudos incluyendo el supernudo.
  - El supernudo aporta una ecuación adicional, la tensión de la fuente que contiene.
  

*** Nudos con fuentes dependientes
- Se plantean las ecuaciones de nudos como si no hubiese fuentes dependientes.
- Se añade la ecuación de la fuente dependiente como una ecuación adicional.
- La matriz de admitancias deja de ser simétrica.


