#+TITLE: Análisis Clásico de Circuitos de Primer Orden
#+SUBTITLE: Teoría de Circuitos III
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: Septiembre 2018
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:2

* Introducción

** Circuitos de Primer Orden
- Circuitos que tienen un *único elemento de acumulación* (o /varios elementos que pueden ser simplificados a un elemento equivalente/) y parte resistiva.
- *Ecuación diferencial de primer orden*: la respuesta natural es siempre una *exponencial decreciente*.
- Circuitos típicos:
  - RL serie
  - RC paralelo
** Respuesta natural y forzada
- El método de resolución analiza el circuito en dos etapas:
  - Sin fuentes: *respuesta natural* (la energía acumulada en $t < 0$ se disipa en la resistencia).
  - Con fuentes: *respuesta forzada* (determinada por la forma de onda de las fuentes).

* Circuito RL serie

** Circuito básico
- En $t < 0$ la fuente alimenta el circuito RL (la bobina almacena energía).
- En $t = 0$ la fuente se desconecta (la bobina se descarga en la resistencia)
[[file:figs/transitorio_circuitoRL.pdf]]

** Respuesta natural

file:figs/transitorio_circuitoRL.pdf

*** Ecuaciones
#+BEGIN_EXPORT latex
\begin{align*}
  u_R(t) + u_L(t) &= 0\\
  R i + L\diff{i}{t} &= 0
\end{align*}
#+END_EXPORT

** Respuesta natural
*** Solución Genérica
#+BEGIN_EXPORT latex
\[
  i(t) = A e^{st}
\]
#+END_EXPORT

*** Ecuación Característica
#+BEGIN_EXPORT latex
\[
  s + \frac{R}{L} = 0 \Rightarrow s = -\frac{R}{L}
\]
#+END_EXPORT

** Condiciones Iniciales
- Analizando circuito para $t < 0$ obtenemos  $i(0^-) = I_0$ 
- Por otra parte, para $t > 0$:
#+BEGIN_EXPORT latex
\begin{align*}
  i(t) &= A e^{-R/L t}\\
  i(0^+) &= A e^0 = A\\
\end{align*}
#+END_EXPORT

- Y dada la condición de continuidad, $i(0^+) = i(0^-)$:
#+BEGIN_EXPORT latex
\begin{align*}
  A &= I_0\\
  i(t) &= I_0 e^{-R/L t}\\
\end{align*}
#+END_EXPORT


** Constante de tiempo
- $\tau = \frac{L}{R}$ es la constante de tiempo (unidades [s]).
- Ratio entre almacenamiento ($L$) y disipación ($R$).

#+BEGIN_EXPORT latex
\[
  i(t) = I_0 e^{-t/\tau}  
\]
#+END_EXPORT

[[file:figs/RespuestaNatural_RL.pdf]]

** Constante de tiempo
- Valores altos de $\tau$ implican decrecimiento lento.
- La respuesta natural "desaparece" tras $\simeq 5\tau$.

[[file:figs/constante_tiempo.pdf]]

** Balance Energético

*** 
La energía acumulada en la bobina en $t < 0$ se disipa en la resistencia en $t > 0$

#+BEGIN_EXPORT latex
\[
  W_R = \int_0^\infty R i^2(t)  \mathrm{d}t = \frac{1}{2} L I_0^2 = W_L
\]
#+END_EXPORT

** Respuesta forzada
Cambia el funcionamiento del interruptor: en $t > 0$ la fuente alimenta el circuito RL.
[[file:figs/RL_forzada.pdf]]

** Respuesta forzada
*** Ecuaciones
#+BEGIN_EXPORT latex
\begin{align*}
  u_R(t) + u_L(t) &= u(t)\\
  R i + L\diff{i}{t} &= U_0
\end{align*}
#+END_EXPORT

*** Solución
Para la solución particular se propone función análoga a la excitación (analizando circuito para $t > 0$)
#+BEGIN_EXPORT latex
\begin{align*}
  i(t) &= i_n(t) + i_\infty(t)\\
  i_n(t) &= A e^{st}\\
  i_\infty(t) &= U_0/R\\
\end{align*}
#+END_EXPORT

** Condiciones iniciales
*** Planteamiento General
#+BEGIN_EXPORT latex
\begin{align*}
  i(0^+) &= i_n(0^+) + i_\infty(0^+)\\
  i(0^+) &= A + i_\infty(0^+)\\
  A &= i(0^+) - i_\infty(0^+)
\end{align*}
#+END_EXPORT

** Respuesta completa (ejemplo)
Suponiendo que la bobina está inicialmente descargada, $i(0^-) = 0 \Rightarrow i(0^+) = 0$
#+BEGIN_EXPORT latex
\begin{align*}
  A &= 0 - U_0/R\\
  i(t) &= \frac{U_0}{R}(1 - e^{-\frac{t}{\tau}})  
\end{align*}
#+END_EXPORT

[[file:figs/RespuestaCompleta_RL.pdf]]


** Respuesta completa

- $i(0^+)$: corriente en la bobina, condiciones iniciales ($i(0^-) = i(0^+)$).
- $i_\infty(t)$: corriente en la bobina en régimen permanente para $t > 0$.
- $i_\infty(0^+)$: corriente en la bobina en régimen permanente particularizada en $t = 0$.

#+BEGIN_EXPORT latex
\[
i(t) = \left(i(0^+) - i_\infty(0^+)\right) e^{-t/\tau} + i_\infty(t)
\]
#+END_EXPORT

* Circuito RC paralelo

** Circuito básico
- En $t <0$ la fuente alimenta el circuito RC (el condensador se carga).
- En $t = 0$ se desconecta la fuente (el condensador comienza a descargarse en la resistencia).
[[file:figs/transitorio_circuitoRC.pdf]]

** Respuesta natural
[[file:figs/transitorio_circuitoRC.pdf]]

*** Ecuaciones
#+BEGIN_EXPORT latex
\begin{align*}
  i_R(t) + i_C(t) &= 0\\
  G u + C\diff{u}{t} &= 0
\end{align*}
#+END_EXPORT

** Respuesta natural
*** Solución Genérica
#+BEGIN_EXPORT latex
\[
  u(t) = A e^{st}
\]
#+END_EXPORT

*** Ecuación Característica
#+BEGIN_EXPORT latex
\[
  s + \frac{G}{C} = 0 \Rightarrow s = -\frac{G}{C}
\]
#+END_EXPORT

*** Condiciones Iniciales
#+BEGIN_EXPORT latex
\[
  u(t) = U_0 e^{-G/C t}
\]
#+END_EXPORT



** Constante de tiempo
- $\tau = \frac{C}{G}$ es la constante de tiempo (unidades [s]).
- Ratio entre almacenamiento ($C$) y disipación ($G$).

#+BEGIN_EXPORT latex
\[
  u(t) = U_0 e^{-t/\tau}  
\]
#+END_EXPORT

[[file:figs/constante_tiempo.pdf]]

** Balance Energético

*** 
La energía acumulada en el condensador en $t < 0$ se disipa en la resistencia (conductancia) en $t > 0$

#+BEGIN_EXPORT latex
\[
  W_G = \int_0^\infty G u^2(t)  \mathrm{d}t = \frac{1}{2} C U_0^2 = W_C
\]
#+END_EXPORT

** Respuesta completa

- $u(0^+)$: tensión en el condensador, condiciones iniciales ($u(0^-) = u(0^+)$).
- $u_\infty(t)$: tensión en el condensador en régimen permanente para $t > 0$.
- $u_\infty(0^+)$: tensión en el condensador en régimen permanente particularizada en $t = 0$.

#+BEGIN_EXPORT latex
\[
u(t) = \left(u(0^+) - u_\infty(0^+)\right) e^{-t/\tau} + u_\infty(t)
\]
#+END_EXPORT

*** Ejemplo
Suponiendo que el condensador está inicialmente descargado, $u(0^-) = 0 \Rightarrow u(0^+) = 0$
#+BEGIN_EXPORT latex
\begin{align*}
  A &= 0 - I_0/G\\
  u(t) &= \frac{I_0}{G}(1 - e^{-\frac{t}{\tau}})  
\end{align*}
#+END_EXPORT

* Análisis Sistemático

** Equivalente de Thévenin (Norton)

[[file:figs/Thevenin_PrimerOrden.pdf]]

** Procedimiento General

- Dibujar el circuito para $t < 0$.
  - Determinar variables en régimen permanente, $u_c(t)$, $i_L(t)$.
  - Particularizar para $t = 0$, obteniendo $u_c(0^-)$ o $i_L(0^-)$.
  - Continuidad: $u_c(0^+) = u_c(0^-)$, $i_L(0^+) = i_L(0^-)$.
- Dibujar el circuito para $t > 0$.
  - Calcular el equivalente de Thevenin (Norton) visto por el elemento de acumulación.
  - La constante de tiempo de la respuesta natural es $\tau = \frac{L}{R_{th}}$ o $\tau = \frac{C}{G_{th}}$.
  - Calcular las variables $i_L(t)$ o $u_c(t)$ en régimen permanente, obteniendo $i_\infty(t)$ o $u_\infty(t)$.
  - Obtener respuesta completa:
#+BEGIN_EXPORT latex
\begin{align*}
i_L(t) &= \left(i_L(0^+) - i_\infty(0^+)\right) e^{-t/\tau} + i_\infty(t)\\
u_C(t) &= \left(u_C(0^+) - u_\infty(0^+)\right) e^{-t/\tau} + u_\infty(t)\\
\end{align*}
#+END_EXPORT


* Ejercicios Recomendados

** Ejercicios

*** FM
Ejemplos de aplicación 4.2, 4.3, 4.4, y 4.7
*** HKD
Ejemplo 8.4, 8.6, 8.10
*** AS
Ejemplo 7.13
