#+TITLE: Cuadripolos
#+SUBTITLE: Teoría de Circuitos III
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: 
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:3

* Introducción

*** Cuadripolo

[[file:../figs/cuadripolo.pdf]]

#+BEGIN_CENTER
*Atención al sentido de las corrientes*
#+END_CENTER
*** Cuadripolos Recíprocos y Simétricos

- Un cuadripolo es *recíproco* si, al intercambiar la posición de las excitaciones, la respuesta en el puerto correspondiente no sufre cambios (teorema de reciprocidad).
- Un cuadripolo lineal (RLC) y *sin fuentes dependientes* es recíproco.
- Un *cuadripolo recíproco es simétrico* si se puede intercambiar la entrada con la salida (simetría física).
* Parámetros de Cuadripolos
** Parámetros de Impedancia

*** Definición

[[file:../figs/cuadripolo_fuentes_corriente.pdf]]

Mediante teorema de superposición:
#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{V}_1 = \mathbf{z}_{11} \mathbf{I}_1 + \mathbf{z}_{12} \mathbf{I}_2\\
  \mathbf{V}_2 = \mathbf{z}_{21} \mathbf{I}_1 + \mathbf{z}_{22} \mathbf{I}_2\\
\end{array}
\]
#+END_EXPORT

Las variables independientes (/generadores/) son $\mathbf{I}_1$ e $\mathbf{I}_2$.

*** Expresión Matricial
[[file:../figs/cuadripolo_fuentes_corriente.pdf]]

#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{z}_{11} & \mathbf{z}_{12}\\
      \mathbf{z}_{21} & \mathbf{z}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Circuito Equivalente

[[file:../figs/circuitoEquivalenteZ.pdf]]

#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{V}_1 = \mathbf{z}_{11} \mathbf{I}_1 + \mathbf{z}_{12} \mathbf{I}_2\\
  \mathbf{V}_2 = \mathbf{z}_{21} \mathbf{I}_1 + \mathbf{z}_{22} \mathbf{I}_2\\
\end{array}
\]
#+END_EXPORT

*** Cálculo de parámetros

**** Salida en abierto

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{z}_{11} = \left.\frac{\mathbf{V}_1}{\mathbf{I}_1}\right\rvert_{\mathbf{I}_2 = 0} \\
    \mathbf{z}_{21} = \left.\frac{\mathbf{V}_2}{\mathbf{I}_1}\right\rvert_{\mathbf{I}_2 = 0}
  \end{array}
\]
#+END_EXPORT

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
[[file:../figs/parametrosZ_entrada.pdf]]

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \color{blue}{\mathbf{z}_{11}} & \mathbf{z}_{12}\\
      \color{blue}{\mathbf{z}_{21}} & \mathbf{z}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \color{blue}{\mathbf{I}_1}\\
      \mathbf{I}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Cálculo de parámetros

**** Entrada en abierto

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.75
:END:
[[file:../figs/parametrosZ_salida.pdf]]

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.25
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{z}_{12} = \left.\frac{\mathbf{V}_1}{\mathbf{I}_2}\right\rvert_{\mathbf{I}_1 = 0}\\
    \mathbf{z}_{22} = \left.\frac{\mathbf{V}_2}{\mathbf{I}_2}\right\rvert_{\mathbf{I}_1 = 0}
  \end{array}
\]
#+END_EXPORT

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{z}_{11} & \color{blue}{\mathbf{z}_{12}}\\
      \mathbf{z}_{21} & \color{blue}{\mathbf{z}_{22}}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \color{blue}{\mathbf{I}_2}
    \end{array}
  \right]
\]
#+END_EXPORT

*** Reciprocidad
#+BEGIN_EXPORT latex
\[
\left.\mathbf{V_1}\right\rvert_{
  \begin{array}{l}
\mathbf{I_1} = 0\\ \mathbf{I_2} = \mathbf{I_x}
  \end{array}
} =% 
\left.\mathbf{V_2}\right\rvert_{
  \begin{array}{l}
\mathbf{I_2} = 0\\ \mathbf{I_1} = \mathbf{I_x}
  \end{array}
}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadZ_entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadZ_salida.pdf]]
*** Relación entre parámetros
Las impedancias de transferencia son idénticas
#+BEGIN_EXPORT latex
\[
  \left.
    \begin{array}{l}
      \mathbf{V}_x = \mathbf{z}_{11} 0  + \mathbf{z}_{12} \mathbf{I}_x\\
      \mathbf{V}_x = \mathbf{z}_{21} \mathbf{I}_x + \mathbf{z}_{22} 0\\
    \end{array} \right\} \rightarrow \boxed{\mathbf{z_{12}} = \mathbf{z_{21}}}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadZ_entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadZ_salida.pdf]]

*** Circuito Equivalente en T

#+BEGIN_EXPORT latex
\[
\boxed{\mathbf{z_{12}} = \mathbf{z_{21}}}
\rightarrow
\left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{z}_{11} & \color{red}{\mathbf{z}_{12}}\\
      \color{red}{\mathbf{z}_{12}} & \mathbf{z}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right]
\]
#+END_EXPORT

**** Ejercicio
Demostrar que un cuadripolo recíproco es equivalente al circuito en T de la figura.

[[file:../figs/circuitoEquivalenteZReciproco.pdf]]

*** Cuadripolo Simétrico
[[file:../figs/circuitoEquivalenteZSimetrico.pdf]]

#+BEGIN_EXPORT latex
\[
\boxed{\mathbf{z_{11}} = \mathbf{z_{22}}}
\rightarrow
\left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \color{blue}{\mathbf{z}_{11}} & \color{red}{\mathbf{z}_{12}}\\
      \color{red}{\mathbf{z}_{12}} & \color{blue}{\mathbf{z}_{11}}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right]
\]
#+END_EXPORT


*** No siempre hay parámetros Z

¿Cuáles son los parámetros Z ... 

- de un transformador ideal?
- de una impedancia serie?

** Parámetros de Admitancia
*** Definición

[[file:../figs/cuadripolo_fuentes_tension.pdf]]

Mediante teorema de superposición:
#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{I}_1 = \mathbf{y}_{11} \mathbf{V}_1 + \mathbf{y}_{12} \mathbf{V}_2\\
  \mathbf{I}_2 = \mathbf{y}_{21} \mathbf{V}_1 + \mathbf{y}_{22} \mathbf{V}_2\\
\end{array}
\]
#+END_EXPORT

Las variables independientes (/generadores/) son $\mathbf{V}_1$ e $\mathbf{V}_2$.

*** Expresión Matricial
[[file:../figs/cuadripolo_fuentes_tension.pdf]]

#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{y}_{11} & \mathbf{y}_{12}\\
      \mathbf{y}_{21} & \mathbf{y}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Circuito Equivalente

[[file:../figs/circuitoEquivalenteY.pdf]]

#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{I}_1 = \mathbf{y}_{11} \mathbf{V}_1 + \mathbf{y}_{12} \mathbf{V}_2\\
  \mathbf{I}_2 = \mathbf{y}_{21} \mathbf{V}_1 + \mathbf{y}_{22} \mathbf{V}_2\\
\end{array}
\]
#+END_EXPORT


*** Cálculo de parámetros

**** Salida en cortocircuito

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{y}_{11} = \left.\frac{\mathbf{I}_1}{\mathbf{V}_1}\right\rvert_{\mathbf{V}_2 = 0} \\
    \mathbf{y}_{21} = \left.\frac{\mathbf{I}_2}{\mathbf{V}_1}\right\rvert_{\mathbf{V}_2 = 0}
  \end{array}
\]
#+END_EXPORT

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
[[file:../figs/parametrosY_entrada.pdf]]

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \color{blue}{\mathbf{y}_{11}} & \mathbf{y}_{12}\\
      \color{blue}{\mathbf{y}_{21}} & \mathbf{y}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \color{blue}{\mathbf{V}_1}\\
      \mathbf{V}_2
    \end{array}
  \right]
\]
#+END_EXPORT


*** Cálculo de parámetros

**** Entrada en cortocircuito

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
[[file:../figs/parametrosY_salida.pdf]]

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{y}_{12} = \left.\frac{\mathbf{I}_1}{\mathbf{V}_2}\right\rvert_{\mathbf{V}_1 = 0}\\
    \mathbf{y}_{22} = \left.\frac{\mathbf{I}_2}{\mathbf{V}_2}\right\rvert_{\mathbf{V}_1 = 0}
  \end{array}
\]
#+END_EXPORT

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{y}_{11} & \color{blue}{\mathbf{y}_{12}}\\
      \mathbf{y}_{21} & \color{blue}{\mathbf{y}_{22}}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \color{blue}{\mathbf{V}_2}
    \end{array}
  \right]
\]
#+END_EXPORT

*** Reciprocidad

#+BEGIN_EXPORT latex
\[
\mathbf{I_1}\rvert_{
  \begin{array}{l}
\mathbf{V_1} = 0 \\ \mathbf{V_2} = \mathbf{V_x}
  \end{array}
} =% 
\mathbf{I_2}\rvert_{
  \begin{array}{l}
\mathbf{V_2} = 0 \\ \mathbf{V_1} = \mathbf{V_x}
  \end{array}
}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadY_entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadY_salida.pdf]]
*** Relación entre parámetros
Las admitancias de transferencia son idénticas
#+BEGIN_EXPORT latex
\[
  \left.
    \begin{array}{l}
      \mathbf{I}_x = \mathbf{y}_{11} 0  + \mathbf{y}_{12} \mathbf{V}_x\\
      \mathbf{I}_x = \mathbf{y}_{21} \mathbf{V}_x + \mathbf{y}_{22} 0\\
    \end{array} \right\} \rightarrow \boxed{\mathbf{y_{12}} = \mathbf{y_{21}}}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadY_entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/reciprocidadY_salida.pdf]]
*** Circuito Equivalente en $\pi$
#+BEGIN_EXPORT latex
\[
\boxed{\mathbf{y_{12}} = \mathbf{y_{21}}}
\rightarrow
\left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{y}_{11} & \color{red}{\mathbf{y}_{12}}\\
      \color{red}{\mathbf{y}_{12}} & \mathbf{y}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right]
\]
#+END_EXPORT

**** Ejercicio
Demostrar que un cuadripolo recíproco es equivalente al circuito en $\pi$ de la figura.

[[file:../figs/circuitoEquivalenteYReciproco.pdf]]

*** Cuadripolo Simétrico


[[file:../figs/circuitoEquivalenteYSimetrico.pdf]]


#+BEGIN_EXPORT latex
\[
\boxed{\mathbf{y_{11}} = \mathbf{y_{22}}}
\rightarrow
\left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \color{blue}{\mathbf{y}_{11}} & \color{red}{\mathbf{y}_{12}}\\
      \color{red}{\mathbf{y}_{12}} & \color{blue}{\mathbf{y}_{11}}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{V}_2
    \end{array}
  \right]
\]
#+END_EXPORT


*** No siempre hay parámetros Y

¿Cuáles son los parámetros Y ... 

- de un transformador ideal?
- de una impedancia paralelo?

** Parámetros Híbridos
*** Definición

[[file:../figs/cuadripolo_hibrido.pdf]]

Mediante teorema de superposición:
#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{V}_1 = \mathbf{h}_{11} \mathbf{I}_1 + \mathbf{h}_{12} \mathbf{V}_2\\
  \mathbf{I}_2 = \mathbf{h}_{21} \mathbf{I}_1 + \mathbf{h}_{22} \mathbf{V}_2\\
\end{array}
\]
#+END_EXPORT

Las variables independientes (/generadores/) son $\mathbf{I}_1$ e $\mathbf{V}_2$.


*** Expresión Matricial
[[file:../figs/cuadripolo_hibrido.pdf]]

#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{h}_{11} & \mathbf{h}_{12}\\
      \mathbf{h}_{21} & \mathbf{h}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{V}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Circuito Equivalente

[[file:../figs/circuitoEquivalenteH.pdf]]

#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{V}_1 = \mathbf{h}_{11} \mathbf{I}_1 + \mathbf{h}_{12} \mathbf{V}_2\\
  \mathbf{I}_2 = \mathbf{h}_{21} \mathbf{I}_1 + \mathbf{h}_{22} \mathbf{V}_2\\
\end{array}
\]
#+END_EXPORT

*** Cálculo de parámetros

**** Salida en cortocircuito

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{h}_{11} = \left.\frac{\mathbf{V}_1}{\mathbf{I}_1}\right\rvert_{\mathbf{V}_2 = 0} \\
    \mathbf{h}_{21} = \left.\frac{\mathbf{I}_2}{\mathbf{I}_1}\right\rvert_{\mathbf{V}_2 = 0}
  \end{array}
\]
#+END_EXPORT

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
[[file:../figs/parametrosH_entrada.pdf]]

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \color{blue}{\mathbf{h}_{11}} & \mathbf{h}_{12}\\
      \color{blue}{\mathbf{h}_{21}} & \mathbf{h}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \color{blue}{\mathbf{I}_1}\\
      \mathbf{V}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Cálculo de parámetros

**** Entrada en abierto

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.75
:END:
[[file:../figs/parametrosH_salida.pdf]]

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.25
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{h}_{12} = \left.\frac{\mathbf{V}_1}{\mathbf{V}_2}\right\rvert_{\mathbf{I}_1 = 0}\\
    \mathbf{h}_{22} = \left.\frac{\mathbf{I}_2}{\mathbf{V}_2}\right\rvert_{\mathbf{I}_1 = 0}
  \end{array}
\]
#+END_EXPORT

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{h}_{11} & \color{blue}{\mathbf{h}_{12}}\\
      \mathbf{h}_{21} & \color{blue}{\mathbf{h}_{22}}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \color{blue}{\mathbf{V}_2}
    \end{array}
  \right]
\]
#+END_EXPORT


** Parámetros Híbridos Inversos

*** Definición

[[file:../figs/cuadripolo_hibrido_inverso.pdf]]

Mediante teorema de superposición:
#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{I}_1 = \mathbf{g}_{11} \mathbf{V}_1 + \mathbf{g}_{12} \mathbf{I}_2\\
  \mathbf{V}_2 = \mathbf{g}_{21} \mathbf{V}_1 + \mathbf{g}_{22} \mathbf{I}_2\\
\end{array}
\]
#+END_EXPORT

Las variables independientes (/generadores/) son $\mathbf{V}_1$ e $\mathbf{I}_2$.

*** Expresión Matricial
[[file:../figs/cuadripolo_hibrido_inverso.pdf]]

#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{g}_{11} & \mathbf{g}_{12}\\
      \mathbf{g}_{21} & \mathbf{g}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Circuito Equivalente

[[file:../figs/circuitoEquivalenteG.pdf]]

#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{I}_1 = \mathbf{g}_{11} \mathbf{V}_1 + \mathbf{g}_{12} \mathbf{I}_2\\
  \mathbf{V}_2 = \mathbf{g}_{21} \mathbf{V}_1 + \mathbf{g}_{22} \mathbf{I}_2\\
\end{array}
\]
#+END_EXPORT

*** Cálculo de parámetros

**** Salida en abierto

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{g}_{11} = \left.\frac{\mathbf{I}_1}{\mathbf{V}_1}\right\rvert_{\mathbf{I}_2 = 0} \\
    \mathbf{g}_{21} = \left.\frac{\mathbf{V}_2}{\mathbf{V}_1}\right\rvert_{\mathbf{I}_2 = 0}
  \end{array}
\]
#+END_EXPORT

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
[[file:../figs/parametrosG_entrada.pdf]]

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \color{blue}{\mathbf{g}_{11}} & \mathbf{g}_{12}\\
      \color{blue}{\mathbf{g}_{21}} & \mathbf{g}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \color{blue}{\mathbf{V}_1}\\
      \mathbf{I}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Cálculo de parámetros

**** Entrada en cortocircuito

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
[[file:../figs/parametrosG_salida.pdf]]

*****                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{2}
\[
  \begin{array}{c}
    \mathbf{g}_{12} = \left.\frac{\mathbf{I}_1}{\mathbf{I}_2}\right\rvert_{\mathbf{V}_1 = 0}\\
    \mathbf{g}_{22} = \left.\frac{\mathbf{V}_2}{\mathbf{I}_2}\right\rvert_{\mathbf{V}_1 = 0}
  \end{array}
\]
#+END_EXPORT

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{g}_{11} & \color{blue}{\mathbf{g}_{12}}\\
      \mathbf{g}_{21} & \color{blue}{\mathbf{g}_{22}}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \color{blue}{\mathbf{I}_2}
    \end{array}
  \right]
\]
#+END_EXPORT


** Parámetros de Transmisión

*** Definición

[[file:../figs/cuadripolo_transmision.pdf]]

#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{V}_1 = \mathbf{A} \mathbf{V}_2 + \mathbf{B}\mathbf{I'}_2\\
  \mathbf{I}_1 = \mathbf{C} \mathbf{V}_2 + \mathbf{D} \mathbf{I'}_2\\
\end{array}
\]
#+END_EXPORT

#+BEGIN_CENTER
*Atención* al sentido de la corriente $\mathbf{I'}_2$. ($\mathbf{I'}_2 = - \mathbf{I}_2$).

#+END_CENTER

*** Expresión Matricial
[[file:../figs/cuadripolo_transmision.pdf]]

#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_1
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{A} & \mathbf{B}\\
      \mathbf{C} & \mathbf{D}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_2\\
      \mathbf{I'}_2
    \end{array}
  \right]
\]
#+END_EXPORT

*** Cálculo de parámetros

Se debe medir el inverso de cada parámetro, dado que la magnitud a medir y la excitación pertenecen al mismo puerto.

#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{3}
\[
  \begin{array}{cc}
    \frac{1}{\mathbf{A}} = \left.\frac{\mathbf{V}_2}{\mathbf{V}_1}\right\rvert_{\mathbf{I}_2 = 0} &
    \frac{1}{\mathbf{B}} = \left.\frac{\mathbf{I'}_2}{\mathbf{V}_1}\right\rvert_{\mathbf{V}_2 = 0}\\
    \frac{1}{\mathbf{C}} = \left.\frac{\mathbf{V}_2}{\mathbf{I}_1}\right\rvert_{\mathbf{I}_2 = 0} &
    \frac{1}{\mathbf{D}} = \left.\frac{\mathbf{I'}_2}{\mathbf{I}_1}\right\rvert_{\mathbf{V}_2 = 0}\\
  \end{array}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/cuadripolo_transmision.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{1}
\[
\begin{array}{l}
  \mathbf{V}_1 = \mathbf{A} \mathbf{V}_2 + \mathbf{B}\mathbf{I'}_2\\
  \mathbf{I}_1 = \mathbf{C} \mathbf{V}_2 + \mathbf{D} \mathbf{I'}_2\\
\end{array}
\]
#+END_EXPORT


** Parámetros de Transmisión Inversa

*** Definición

[[file:../figs/cuadripolo_transmision_inversa.pdf]]

#+BEGIN_EXPORT latex
\[
\begin{array}{l}
  \mathbf{V}_2 = \mathbf{a} \mathbf{V}_1 + \mathbf{b}\mathbf{I'}_1\\
  \mathbf{I}_2 = \mathbf{c} \mathbf{V}_1 + \mathbf{d} \mathbf{I'}_1\\
\end{array}
\]
#+END_EXPORT

#+BEGIN_CENTER
*Atención* al sentido de la corriente $\mathbf{I'}_1$ ($\mathbf{I'}_1 = - \mathbf{I}_1$).
#+END_CENTER

*** Expresión Matricial
[[file:../figs/cuadripolo_transmision_inversa.pdf]]

#+BEGIN_EXPORT latex
\[
  \left[
    \begin{array}{c}
      \mathbf{V}_2\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{a} & \mathbf{b}\\
      \mathbf{c} & \mathbf{d}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I'}_1
    \end{array}
  \right]
\]
#+END_EXPORT

*** Cálculo de parámetros
Se debe medir el inverso de cada parámetro, dado que la magnitud a medir y la excitación pertenecen al mismo puerto.

#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{3}
\[
  \begin{array}{cc}
    \frac{1}{\mathbf{a}} = \left.\frac{\mathbf{V}_1}{\mathbf{V}_2}\right\rvert_{\mathbf{I}_1 = 0} &
    \frac{1}{\mathbf{b}} = \left.\frac{\mathbf{I'}_1}{\mathbf{V}_2}\right\rvert_{\mathbf{V}_1 = 0}\\
    \frac{1}{\mathbf{c}} = \left.\frac{\mathbf{V}_1}{\mathbf{I}_2}\right\rvert_{\mathbf{I}_1 = 0} &
    \frac{1}{\mathbf{d}} = \left.\frac{\mathbf{I'}_1}{\mathbf{I}_2}\right\rvert_{\mathbf{V}_1 = 0}\\
  \end{array}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
[[file:../figs/cuadripolo_transmision_inversa.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:


#+BEGIN_EXPORT latex
\renewcommand{\arraystretch}{1}
\[
\begin{array}{l}
  \mathbf{V}_2 = \mathbf{a} \mathbf{V}_1 + \mathbf{b}\mathbf{I'}_1\\
  \mathbf{I}_2 = \mathbf{c} \mathbf{V}_1 + \mathbf{d} \mathbf{I'}_1\\
\end{array}
\]
#+END_EXPORT


* Relación entre parámetros

*** Impedancia y Admitancia
#+BEGIN_EXPORT latex
\[
  \left.
    \begin{array}{l}
      \left[
      \begin{array}{c}
        \mathbf{V}_1\\
        \mathbf{V}_2
      \end{array}
      \right] =
      \left[
      \begin{array}{cc}
        \mathbf{z}_{11} & \mathbf{z}_{12}\\
        \mathbf{z}_{21} & \mathbf{z}_{22}
      \end{array}
                          \right]
                          \cdot
                          \left[
                          \begin{array}{c}
                            \mathbf{I}_1\\
                            \mathbf{I}_2
                          \end{array}
      \right] \\ \\
      \left[
      \begin{array}{c}
        \mathbf{I}_1\\
        \mathbf{I}_2
      \end{array}
      \right] =
      \left[
      \begin{array}{cc}
        \mathbf{y}_{11} & \mathbf{y}_{12}\\
        \mathbf{y}_{21} & \mathbf{y}_{22}
      \end{array}
                          \right] \cdot
                          \left[
                          \begin{array}{c}
                            \mathbf{V}_1\\
                            \mathbf{V}_2
                          \end{array}
      \right]
    \end{array}
    \right\}
      \rightarrow
      \boxed{[\mathbf{Z}] = [\mathbf{Y}]^{-1}}
    \]
#+END_EXPORT

*** Híbridos
#+BEGIN_EXPORT latex
\[
  \left.
    \begin{array}{l}
      %% Híbridos
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{h}_{11} & \mathbf{h}_{12}\\
      \mathbf{h}_{21} & \mathbf{h}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{V}_2
    \end{array}
      \right]
      \\ \\
      %% Híbridos Inversos
  \left[
    \begin{array}{c}
      \mathbf{I}_1\\
      \mathbf{V}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{g}_{11} & \mathbf{g}_{12}\\
      \mathbf{g}_{21} & \mathbf{g}_{22}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_2
    \end{array}
      \right]
      \end{array}
    \right\}
      \rightarrow
      \boxed{[\mathbf{H}] = [\mathbf{G}]^{-1}}
    \]
#+END_EXPORT
*** Transmisión
#+BEGIN_EXPORT latex
\[
  \left.
    \begin{array}{l}
      %% Transmisión
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I}_1
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{A} & \mathbf{B}\\
      \mathbf{C} & \mathbf{D}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_2\\
      \mathbf{I'}_2
    \end{array}
  \right]
      \\ \\
      %% Transmisión Inversa
  \left[
    \begin{array}{c}
      \mathbf{V}_2\\
      \mathbf{I}_2
    \end{array}
  \right] =
  \left[
    \begin{array}{cc}
      \mathbf{a} & \mathbf{b}\\
      \mathbf{c} & \mathbf{d}
    \end{array}
  \right] \cdot
  \left[
    \begin{array}{c}
      \mathbf{V}_1\\
      \mathbf{I'}_1
    \end{array}
  \right]
      \end{array}
    \right\}
    \rightarrow
    \boxed{[\mathbf{T}] \neq [\mathbf{t}]^{-1}}
  \]
#+END_EXPORT
#+BEGIN_EXPORT latex
\[
  \boxed{
    \left[
      \begin{array}{cc}
        \mathbf{A} & \mathbf{B}\\
        \mathbf{C} & \mathbf{D}
      \end{array}\right] = 
      \left[
      \begin{array}{cc}
        \mathbf{a} & \mathbf{-b}\\
        \mathbf{-c} & \mathbf{d}
      \end{array}
      \right]^{-1}
    }
\]
#+END_EXPORT
*** 
:PROPERTIES:
:BEAMER_opt: plain
:END:
#+ATTR_LATEX: :width 1.15\textwidth
[[file:../figs/Tabla_Parametros.pdf]]

*** Reciprocidad
A partir de las relaciones ya obtenidas para impedancia y admitancia, utilizando la tabla anterior obtenemos la relación para parámetros híbridos y de transmisión:
#+BEGIN_EXPORT latex
\[
\left.
\begin{array}{l}
  \mathbf{z_{12}} = \mathbf{z_{21}}\\
  \mathbf{y_{12}} = \mathbf{y_{21}}\\
\end{array}
\right\} \rightarrow
\left\{
\begin{array}{l}
  \mathbf{h_{12}} = - \mathbf{h_{21}}\\
  \mathbf{g_{12}} = - \mathbf{g_{21}}\\
  \mathbf{A} \mathbf{D} - \mathbf{B} \mathbf{C} = 1\\
  \mathbf{a} \mathbf{d} - \mathbf{b} \mathbf{c} = 1\\
\end{array}
\right.
\]
#+END_EXPORT


*** Simetría
A partir de las relaciones ya obtenidas para impedancia y admitancia, utilizando la tabla anterior obtenemos la relación para parámetros híbridos y de transmisión:
#+BEGIN_EXPORT latex
\[
\left.
\begin{array}{l}
  \mathbf{z_{11}} = \mathbf{z_{22}}\\
  \mathbf{y_{11}} = \mathbf{y_{22}}\\
\end{array}
\right\} \rightarrow
\left\{
\begin{array}{l}
  \mathbf{h_{11}} \cdot \mathbf{h_{22}} - \mathbf{h_{12}}^2 = 1\\
  \mathbf{g_{11}} \cdot \mathbf{g_{22}} - \mathbf{g_{12}}^2 = 1\\
  \mathbf{A} =  \mathbf{D}\\
  \mathbf{a} =  \mathbf{d}\\
\end{array}
\right.
\]
#+END_EXPORT

Además:

#+BEGIN_EXPORT latex
\[
  \boxed{[\mathbf{T}] = [\mathbf{t}]}
\]
#+END_EXPORT


* Cuadripolos entre Dipolos Terminales

** Situación General
*** 

[[file:../figs/cuadripolo_cargado_fuente_tension.pdf]]

#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{V}_1 &= \mathbf{E}_g - \mathbf{Z}_g \cdot \mathbf{I}_1\\
  \mathbf{V}_2 &= - \mathbf{Z}_L \cdot \mathbf{I}_2\\
\end{align*}
#+END_EXPORT

*** 

[[file:../figs/cuadripolo_cargado_fuente_corriente.pdf]]

#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{V}_1 &= (\mathbf{I}_g - \mathbf{I}_1) \cdot \mathbf{Z}_g\\
  \mathbf{V}_2 &= - \mathbf{Z}_L \cdot \mathbf{I}_2\\
\end{align*}
#+END_EXPORT

*** Ganancia

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

[[file:../figs/cuadripolo_cargado_fuente_tension.pdf]]

[[file:../figs/cuadripolo_cargado_fuente_corriente.pdf]]


****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
- Ganancia de Tensión
#+BEGIN_EXPORT latex
\[
\mathbf{A}_V = \frac{\mathbf{V}_2}{\mathbf{E}_g}
\]
#+END_EXPORT
- Ganancia de Corriente
#+BEGIN_EXPORT latex
\[
\mathbf{A}_I = \frac{\mathbf{I}_2}{\mathbf{I}_g}
\]
#+END_EXPORT

*** Impedancia
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

[[file:../figs/cuadripolo_cargado_fuente_tension.pdf]]

[[file:../figs/cuadripolo_cargado_fuente_corriente.pdf]]


****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

- Impedancia de Entrada
#+BEGIN_EXPORT latex
\[
\mathbf{Z}_i = \frac{\mathbf{V}_1}{\mathbf{I}_1}
\]
#+END_EXPORT

- Impedancia de Salida
#+BEGIN_EXPORT latex
\[
\mathbf{Z}_o = \left.\frac{\mathbf{V}_2}{\mathbf{I}_2}\right\rvert_{\mathbf{E}_g = 0}
\]
#+END_EXPORT

*** Transferencia
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

[[file:../figs/cuadripolo_cargado_fuente_tension.pdf]]

[[file:../figs/cuadripolo_cargado_fuente_corriente.pdf]]


****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:

- Transadmitancia directa
#+BEGIN_EXPORT latex
\[
\mathbf{Y}_f = \frac{\mathbf{I}_2}{\mathbf{E}_g}
\]
#+END_EXPORT

- Transimpedancia directa
#+BEGIN_EXPORT latex
\[
\mathbf{Z}_f = \frac{\mathbf{V}_2}{\mathbf{I}_g}
\]
#+END_EXPORT

*** Ejercicio de Cálculo (1)

Demuestra que la impedancia de entrada del circuito a la derecha de la fuente real expresada con parámetros de transmisión es:

#+BEGIN_EXPORT latex
\[
\mathbf{Z}_i = \frac{\mathbf{A} \mathbf{Z}_L + \mathbf{B}}{\mathbf{C}\mathbf{Z}_L + \mathbf{D}}
\]
#+END_EXPORT

#+ATTR_LATEX: :height 0.6\textheight
[[file:../figs/cuadripolo_cargado_impedancia_entrada.pdf]]



*** Ejercicio de Cálculo (2)

¿Qué impedancia de carga $\mathbf{Z}_L$ hay que conectar a la salida del cuadripolo para obtener la máxima transferencia de potencia?


[[file:../figs/cuadripolo_cargado_fuente_tension.pdf]]

** Parámetros Imagen

*** Impedancia Característica
Para un cuadripolo *recíproco* y *simétrico* se definen los parámetros imagen:

- *Impedancia característica*, $\mathbf{Z}_o$: impedancia que, conectada en una puerta, hace que desde la otra puerta se vea la misma impedancia.
#+BEGIN_EXPORT latex
\[
  \mathbf{Z}_o = \frac{\mathbf{U}_1}{\mathbf{I}_1}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:

[[file:../figs/cuadripolo_impedancia_caracteristica.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:

#+BEGIN_EXPORT latex 
\[
\mathbf{Z}_o = \frac{\mathbf{A} \mathbf{Z}_o + \mathbf{B}}{\mathbf{C}\mathbf{Z}_o + \mathbf{D}}
\]

\[
\mathbf{A} = \mathbf{D} \rightarrow \boxed{\mathbf{Z}_o = \pm \sqrt{\frac{\mathbf{B}}{\mathbf{C}}}}
\]
#+END_EXPORT

*** Impedancia Característica

**** Atención
La ecuación proporciona dos soluciones, una de las cuáles implicará una impedancia no viable (/resistencia negativa/).
#+begin_export latex
\[
\boxed{\mathbf{Z}_o = \pm \sqrt{\frac{\mathbf{B}}{\mathbf{C}}}}
\]
#+end_export

*** Función de Propagación
Para un cuadripolo *recíproco* y *simétrico* se definen los parámetros imagen:

- *Función de propagación*, $\gamma$: relacionada con el cociente de potencias en las puertas del cuadripolo cuando una de ellas está cargada con $\mathbf{Z}_o$

#+BEGIN_EXPORT latex
\[
  \exp(2\gamma) = \frac{\mathbf{U}_1\mathbf{I}_1}{\mathbf{U}_2\mathbf{I}'_2}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:

[[file:../figs/cuadripolo_impedancia_caracteristica.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{U}_1 &= \mathbf{I}_1 \mathbf{Z}_o\\
  \mathbf{U}_2 &= \mathbf{I}'_2 \mathbf{Z}_o
\end{align*}

\[
  \boxed{\exp(\gamma) = \frac{\mathbf{U}_1}{\mathbf{U}_2} = \frac{\mathbf{I}_1}{\mathbf{I}'_2}}
\]

#+END_EXPORT


*** Relación entre $\mathbf{Z}_o$ y $\gamma$
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.6
:END:

[[file:../figs/cuadripolo_impedancia_caracteristica.pdf]]

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.4
:END:

#+BEGIN_EXPORT latex
\begin{align*}
  \exp(\gamma) &= \frac{\mathbf{U}_1}{\mathbf{U}_2} =\\
               &= \frac{\mathbf{A}\mathbf{U}_2 + \mathbf{B}\mathbf{I}'_2}{\mathbf{U}_2} = \\
               &= \mathbf{A} + \mathbf{B}\frac{\mathbf{I}'_2}{\mathbf{U_2}}
\end{align*}

\[
  \boxed{\exp(\gamma) = \mathbf{A} + \frac{\mathbf{B}}{\mathbf{Z}_o}}
\]
#+END_EXPORT

*** Relación entre $\mathbf{Z}_o$ y $\gamma$

Teniendo en cuenta la expresión de $\mathbf{Z}_o$:
#+BEGIN_EXPORT latex
\[
  \left.
  \begin{array}{l}
    \mathbf{Z}_o = \pm \sqrt{\frac{\mathbf{B}}{\mathbf{C}}}\\
    \exp(\gamma) = \mathbf{A} + \frac{\mathbf{B}}{\mathbf{Z}_o}
  \end{array} \right\} \rightarrow
\boxed{\exp(\gamma) = \mathbf{A} \pm \sqrt{\mathbf{B}\mathbf{C}}}
\]
#+END_EXPORT

Además, teniendo en cuenta la relación de un cuadripolo recíproco y simétrico:

#+BEGIN_EXPORT latex
\[
  \mathbf{A}^2 - \mathbf{B}\mathbf{C} = 1 \rightarrow %
  \boxed{\exp(\gamma) = \mathbf{A} \pm \sqrt{\mathbf{A}^2 - 1}}
\]
#+END_EXPORT
*Atención* al signo que acompaña a las raíces cuadradas. Se debe elegir de forma que la parte real de $\gamma$ sea acorde al cuadripolo.

*** Transmisión a partir de Imagen

#+BEGIN_EXPORT latex
\[
\mathbf{A}^2 - \mathbf{B}\mathbf{C} = 1
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.33
:END:
#+BEGIN_EXPORT latex
\[
  e^\gamma = \mathbf{A} + \sqrt{\mathbf{A}^2 - 1}
\]

\[
  \mathbf{Z}_o = \sqrt{\frac{\mathbf{B}}{\mathbf{C}}}
\]
#+END_EXPORT

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.33
:END:
#+BEGIN_EXPORT latex
\begin{align*}
  \cosh(\gamma) &= \frac{e^\gamma + e^{-\gamma}}{2}\\
  \sinh(\gamma) &= \frac{e^\gamma - e^{-\gamma}}{2}\\
  \cosh^2(\gamma) &- \sinh^2(\gamma) = 1
\end{align*}
#+END_EXPORT

**** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+beamer: \vspace{1cm}
#+BEGIN_EXPORT latex
\[
\boxed{
  \begin{array}{ll}
    \mathbf{A} = \cosh(\gamma) &
    \mathbf{B} = \mathbf{Z}_o \sinh(\gamma)\\
    \mathbf{C} = \sinh(\gamma)/\mathbf{Z}_o &
    \mathbf{D} = \cosh(\gamma)\\
  \end{array}
}
\]
#+END_EXPORT

*** Régimen Permanente Sinusoidal

Cuando el circuito funciona en régimen permanente sinusoidal:

- La función de propagación es un número complejo denominado constante de propagación.
#+BEGIN_EXPORT latex
\[
  \overline{\gamma} = \alpha + j\beta
\]
#+END_EXPORT
- Las tensiones y corrientes son fasores
#+BEGIN_EXPORT latex
\[
  \exp(\overline{\gamma}) = \exp(\alpha) \cdot \exp(j\beta) = \frac{\overline{U}_1}{\overline{U}_2} = \frac{\overline{I}_1}{\overline{I}'_2}
\]
#+END_EXPORT

*** Régimen Permanente Sinusoidal
- *Constante de Atenuación* (cuando $\alpha > 1$ el cuadripolo atenúa la salida respecto de la entrada)
#+BEGIN_EXPORT latex
\[
  \exp(\alpha) = \frac{U_1}{U_2} = \frac{I_1}{I_2}
\]
#+END_EXPORT
- *Constante de Fase* (desfase entre puertos)
#+BEGIN_EXPORT latex
\[
  \beta = \theta_{\overline{U}_1} - \theta_{\overline{U}_2} = \theta_{\overline{I}_1} - \theta_{\overline{I}'_2}
\]
#+END_EXPORT

*** Atenuación de Potencia

*Cuando está conectada la impedancia característica*, las potencias activas en los puertos se expresan:

#+BEGIN_EXPORT latex
\begin{align*}
  P_1 &= U_1 I_1 \cos(\theta_o)\\
  P_2 &= U_2 I_2 \cos(\theta_o)
\end{align*}
#+END_EXPORT
donde $\theta_o$ es el ángulo de la impedancia $\overline{Z}_o$.

Por tanto, la relación de potencias activas es:

#+BEGIN_EXPORT latex
\[
\frac{P_1}{P_2} = \frac{U_1 I_1}{U_2 I_2}
\]
#+END_EXPORT
Teniendo en cuenta la expresión de la constante de atenuación, esta relación es:
#+BEGIN_EXPORT latex
\[
    \exp(\alpha) = \frac{U_1}{U_2} = \frac{I_1}{I_2} \rightarrow \boxed{\exp(2\alpha) = \frac{U_1 I_1}{U_2 I_1} = \frac{P_1}{P_2}}
\]
#+END_EXPORT

* Asociación de Cuadripolos

*** Conexiones

**** Definición
- *Serie*: misma corriente, suma de tensiones
- *Paralelo*: misma tensión, suma de corrientes
**** Catálogo
- Serie-Serie: *parámetros impedancia*
- Paralelo-Paralelo: *parámetros admitancia*
- Serie-Paralelo: *parámetros híbridos*
- Paralelo-Serie: *parámetros híbridos inversos*
- Cascada: *parámetros transmisión/imagen*
** Asociación Serie-Serie

*** Conexión

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
#+ATTR_LATEX: :height 0.85\textheight
[[file:../figs/serie-serie.pdf]]



****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:


***** Tensiones
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{V}_1 &= \mathbf{V}_{1A} + \mathbf{V}_{1B}\\
  \mathbf{V}_2 &= \mathbf{V}_{2A} + \mathbf{V}_{2B}
\end{align*}
#+END_EXPORT

***** Condición de Puerto
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{I}_{1A} &= \mathbf{I}_{1'A}\\
  \mathbf{I}_{1B} &= \mathbf{I}_{1'B}\\
  \mathbf{I}_{2A} &= \mathbf{I}_{2'A}\\
  \mathbf{I}_{2B} &= \mathbf{I}_{2'B}
\end{align*}
#+END_EXPORT

*** Cuadripolo Equivalente
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
#+ATTR_LATEX: :height 0.85\textheight
[[file:../figs/serie-serie.pdf]]


****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.35
:END:
***** Parámetros Impedancia
#+BEGIN_EXPORT latex
\begin{align*}
  [\mathbf{V}_A] &= [\mathbf{Z}_A] \cdot [\mathbf{I}_A]\\
  [\mathbf{V}_B] &= [\mathbf{Z}_B] \cdot [\mathbf{I}_B]
\end{align*}
  
#+END_EXPORT

***** Cuadripolo Equivalente
#+BEGIN_EXPORT latex
\[
  \boxed{[\mathbf{Z}] = [\mathbf{Z}_A] + [\mathbf{Z}_B]}
\]

#+END_EXPORT

*** Interacción
:PROPERTIES:
:BEAMER_opt: plain
:END:
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.9
:END:
[[file:../figs/serie-serie-interaccion.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
- Entrada
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{I}_{1A} &= \mathbf{I}_{g1}\\
  \mathbf{I}_{1'A} &= \mathbf{I}_{g1} - \mathbf{I}_h
\end{align*}
#+END_EXPORT
- Salida
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{I}_{2A} &= \mathbf{I}_{g2}\\
  \mathbf{I}_{2'A} &= \mathbf{I}_{g2}  + \mathbf{I}_h
\end{align*}
#+END_EXPORT
- Condición de Puerto
#+BEGIN_EXPORT latex
\[
\boxed{\mathbf{I}_h = 0}
\]
#+END_EXPORT
*** Interacción
:PROPERTIES:
:BEAMER_opt: plain
:END:
Si no hay interacción, al aplicar superposición la corriente de circulación debe ser nula *en ambos casos*.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/serie-serie-superposicion-entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/serie-serie-superposicion-salida.pdf]]

*** Test de Brune
:PROPERTIES:
:BEAMER_opt: plain
:END:
Aplicando superposición desconectamos los cuadripolos: *si no hay interacción, no habrá cambio de tensión*.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/serie-serie-brune-entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/serie-serie-brune-salida.pdf]]


*** Métodos para evitar interacción
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/serie-serie-transformador.pdf]]

*** Métodos para evitar interacción
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/serie-serie-corto.pdf]]

** Asociación Paralelo-Paralelo
*** Conexión
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
#+ATTR_LATEX: :height 0.75\textheight
[[file:../figs/paralelo-paralelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:

***** Corrientes
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{I}_1 &= \mathbf{I}_{1A} + \mathbf{I}_{1B}\\
  \mathbf{I}_2 &= \mathbf{I}_{2A} + \mathbf{I}_{2B}
\end{align*}
#+END_EXPORT

***** Condición de Puerto
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{I}_{1A} &= \mathbf{I}_{1'A}\\
  \mathbf{I}_{1B} &= \mathbf{I}_{1'B}\\
  \mathbf{I}_{2A} &= \mathbf{I}_{2'A}\\
  \mathbf{I}_{2B} &= \mathbf{I}_{2'B}
\end{align*}
#+END_EXPORT

*** Cuadripolo Equivalente
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
#+ATTR_LATEX: :height 0.7\textheight
[[file:../figs/paralelo-paralelo.pdf]]


****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.35
:END:
***** Parámetros Admitancia
#+BEGIN_EXPORT latex
\begin{align*}
  [\mathbf{I}_A] &= [\mathbf{Y}_A] \cdot [\mathbf{V}_A]\\
  [\mathbf{I}_B] &= [\mathbf{Y}_B] \cdot [\mathbf{V}_B]
\end{align*}
  
#+END_EXPORT

***** Cuadripolo Equivalente
#+BEGIN_EXPORT latex
\[
  \boxed{[\mathbf{Y}] = [\mathbf{Y}_A] + [\mathbf{Y}_B]}
\]
#+END_EXPORT
*** Interacción
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/paralelo-paralelo-interaccion.pdf]]
*** Interacción
:PROPERTIES:
:BEAMER_opt: plain
:END:
Si no hay interacción, al aplicar superposición la corriente de circulación debe ser nula *en ambos casos*.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-paralelo-superposicion-entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-paralelo-superposicion-salida.pdf]]

*** Test de Brune
:PROPERTIES:
:BEAMER_opt: plain
:END:
Aplicando superposición desconectamos los cuadripolos: *si no hay interacción, no habrá cambio de tensión*.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-paralelo-brune-entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-paralelo-brune-salida.pdf]]

*** Test de Brune
:PROPERTIES:
:BEAMER_opt: plain
:END:
Aplicando superposición desconectamos los cuadripolos: *si no hay interacción, no habrá cambio de tensión*.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-paralelo-brune-entrada2.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-paralelo-brune-salida2.pdf]]

*** Métodos para evitar interacción
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/paralelo-paralelo-transformador.pdf]]
*** Métodos para evitar interacción
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figs/paralelo-paralelo-corto.pdf]]
** Asociación Serie-Paralelo
*** Conexión
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
#+ATTR_LATEX: :height 0.75\textheight
[[file:../figs/serie-paralelo.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.35
:END:

***** Relaciones
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{V}_1 &= \mathbf{V}_{1A} + \mathbf{V}_{1B}\\
  \mathbf{I}_2 &= \mathbf{I}_{2A} + \mathbf{I}_{2B}
\end{align*}
#+END_EXPORT

***** Cuadripolo Equivalente
#+BEGIN_EXPORT latex
\[
  \boxed{[\mathbf{H}] = [\mathbf{H}_A] + [\mathbf{H}_B]}
\]
#+END_EXPORT
*** Test de Brune
:PROPERTIES:
:BEAMER_opt: plain
:END:
Aplicando superposición desconectamos los cuadripolos: *si no hay interacción, no habrá cambio de tensión*.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/serie-paralelo-brune-entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/serie-paralelo-brune-salida.pdf]]

** Asociación Paralelo-Serie
*** Conexión
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.7
:END:
#+ATTR_LATEX: :height 0.75\textheight
[[file:../figs/paralelo-serie.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.35
:END:
***** Relaciones
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{I}_1 &= \mathbf{I}_{1A} + \mathbf{I}_{1B}\\
  \mathbf{V}_2 &= \mathbf{V}_{2A} + \mathbf{V}_{2B}
\end{align*}
#+END_EXPORT

***** Cuadripolo Equivalente
#+BEGIN_EXPORT latex
\[
  \boxed{[\mathbf{G}] = [\mathbf{G}_A] + [\mathbf{G}_B]}
\]
#+END_EXPORT

*** Test de Brune
:PROPERTIES:
:BEAMER_opt: plain
:END:
Aplicando superposición desconectamos los cuadripolos: *si no hay interacción, no habrá cambio de tensión*.
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-serie-brune-entrada.pdf]]
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.65
:END:
[[file:../figs/paralelo-serie-brune-salida.pdf]]
** Asociación Cascada

*** Conexión
[[file:../figs/cascada.pdf]]

#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{V}_{2A} &= \mathbf{V}_{1B}\\
  \mathbf{I}'_{2A} &= \mathbf{I}_{1B}
\end{align*}
#+END_EXPORT


#+BEGIN_EXPORT latex
\[
  \boxed{[\mathbf{T}] = [\mathbf{T}_A] \cdot [\mathbf{T}_B]}
\]
#+END_EXPORT


