#+TITLE: Introducción al Régimen Transitorio
#+SUBTITLE: Teoría de Circuitos III
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: Septiembre 2018
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:2

* ¿Qué es el régimen transitorio?
** Permanente y Estacionario

*** Régimen permanente o estacionario
Las tensiones y corrientes de un circuito son constantes (continua) o periódicas (alterna) (circuito estabilizado)
*** Régimen transitorio
- Para alcanzar el régimen permanente (o para alternar entre dos regímenes permanentes) el circuito atraviesa el régimen transitorio.
- Posibles cambios: activación o apagado de fuentes, cambio en las cargas, cambio en el circuito (línea).
- En general, el estado transitorio es indeseado en sistemas eléctricos, pero provocado en sistemas electrónicos.

** Acumulación de Energía
*** Régimen Permanente
*Energía acumulada* en *bobinas* y *condensadores*
*** Régimen Estacionario
- *Redistribución* y *disipación* de energía acumulada.
- La redistribución de energía *no* se puede realizar de forma *inmediata*
- *Duración corta* ($\si{\micro\second}$) pero superior a 0, dependiendo de *relación entre acumulación y disipación* (resistencia).

* Métodos de resolución

** Análisis Clásico
- Formulación de las ecuaciones integro-diferenciales y resolución *directa*.
#+BEGIN_EXPORT latex
\[
LC \diff[2]{u_c}{t} + RC \diff{u_c}{t} + u_c = 0
\]
#+END_EXPORT
- Las *condiciones iniciales* determinan las constantes de integración.
- Fácil de aplicar a *circuitos simples* (primer y segundo orden, uno o dos elementos de acumulación).
- No es apropiado para circuitos de orden superior a 2.
- Permite comprensión del funcionamiento del circuito.
** Transformada de Laplace
- Transforma las ecuaciones integro-diferenciales en ecuaciones algebraicas de una variable compleja.
#+BEGIN_EXPORT latex
\[
LC s^2 + RC s + 1 = 0  
\]
#+END_EXPORT
- Incorpora las condiciones iniciales directamente en las ecuaciones algebraicas.
- Método sistemático y potente, adecuado para cualquier tipo de circuito.
** Variables de estado
- Método proveniente de la ingeniería de control.
- Las variables de estado son aquellas que definen la evolución de un sistema.
  - En circuitos eléctricos: tensión de condensadores, corriente de bobinas.
- El sistema evoluciona a través de diferentes estados según los cambios en la energía acumulada: *trayectoria del sistema*.
- Representa el sistema mediante una *ecuación diferencial matricial*:
#+BEGIN_EXPORT latex
\[
  \diff{\mathbf{x}}{t} = f\{\mathbf{x}, \mathbf{u}, t\}
  \]
#+END_EXPORT 
- Método sistemático y potente, adecuado para resolución con ordenador.
* Condiciones iniciales
** Respuesta completa de una red lineal
- La respuesta completa de una red lineal a un cambio tiene dos componentes:
  - Respuesta *natural* o propia (sin fuentes, determinada únicamente por la configuración del circuito)
  - Respuesta *forzada* o particular (determinada por las fuentes existentes, $t = \infty$).
#+BEGIN_EXPORT latex
\[
 \boxed{f(t) = f_n(t) + f_\infty(t) }
 \]
#+END_EXPORT
- Las constantes de integración de la respuesta natural se determinan con las condiciones iniciales del circuito.

** Condiciones iniciales
- *Condiciones Iniciales*: estado del circuito en el instante temporal en el que se produce el cambio (p.ej. apertura de interruptor).
- Este instante temporal se representa habitualmente con $t = 0$. 
** $t = 0^+$ y $t = 0^-$
- El estado previo a la conmutación es $t = 0^-$ 
  - La topología del circuito es la anterior al cambio.
- El estado posterior a la conmutación es $t = 0^+$.
  - La topología del circuito es la posterior al cambio.
** Resistencia
#+BEGIN_EXPORT latex
\[
u(t) = R i(t)
\]
#+END_EXPORT

- No acumula energía: sigue los cambios de forma instantánea.

** Inductancia
#+BEGIN_EXPORT latex
\[
u(t) = L \diff{i_L(t)}{t}
\]

\[
i_L(t) = \frac{1}{L} \int^t_{-\infty}u(t) \mathrm{d}t
\]
#+END_EXPORT

- La corriente en una bobina no puede variar de forma abrupta (implica tensión infinita).
#+BEGIN_EXPORT latex
\[
i_L(0^-) = i_L(0^+)
\]
#+END_EXPORT

** Capacidad
#+BEGIN_EXPORT latex
\[
i(t) = C \diff{u_C(t)}{t}
\]

\[
u(t) = \frac{1}{C} \int^t_{-\infty}i(t) \mathrm{d}t
\]
#+END_EXPORT

- La tensión en un condensador no puede variar de forma abrupta (implica corriente infinita).
#+BEGIN_EXPORT latex
\[
u_C(0^-) = u_C(0^+)
\]
#+END_EXPORT
** Circuitos Equivalentes en $t = 0^+$
- Sustituir fuentes de tensión $u_g(t)$ por $u_g(0^+)$.
- Sustituir fuentes de corriente $i_g(t)$ por $i_g(0^+)$.
- Sustituir bobinas por fuentes de corriente $i_L(0^+)$.
- Sustituir condensadores por fuentes de tensión $u_C(0^+)$.
- Calcular tensiones y corrientes en circuito.
[[file:figs/CondicionesIniciales_CircuitosEquivalentes.pdf]]

** Ejemplo

*** (Sep 2010) El interruptor lleva en la posición (1) desde un tiempo infinito y pasa a la posición (2) en $t = 0$.
[[file:figs/ejemplo_condiciones_iniciales.pdf]]

* Funciones importantes
** Función Escalón
#+BEGIN_EXPORT latex
\[   
u(t - t_0) = 
     \begin{cases}
       0 &\quad t < t_0\\
       1 &\quad t > t_0\\
     \end{cases}
\]
#+END_EXPORT
[[file:figs/funcion_escalon.pdf]]

** Función Escalón ($t_0 = 0$)

#+BEGIN_EXPORT latex
\[   
u(t) = 
     \begin{cases}
       0 &\quad t < 0\\
       1 &\quad t > 0\\
     \end{cases}
\]
#+END_EXPORT

[[file:figs/funcion_escalon0.pdf]]

** Función Exponencial
- Es igual a su derivada. 
#+BEGIN_EXPORT latex
\[
\diff{e^x}{x} = e^x
\]
#+END_EXPORT

- Es la solución habitual de las ecuaciones diferenciales.

#+BEGIN_EXPORT latex
\[
  \diff{f(t)}{t} = b f(t) \Rightarrow f(t) = A e^{bt}
\]
#+END_EXPORT
** Función Exponencial
- Cuando el exponente es positivo la respuesta crece indefinidamente (circuito inestable).
- Cuando el exponente es negativo la respuesta decae hasta 0 (circuito estable).
[[file:figs/exp_decreciente.pdf]]

