#+TITLE: Análisis del Régimen Transitorio con Variables de Estado
#+SUBTITLE: Teoría de Circuitos III
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: 
#+STARTUP: beamer
#+STARTUP: indent
#+SETUPFILE: config.org
#+OPTIONS: H:2

* Introducción
** Motivación
El comportamiento de un circuito puede ser descrito con ecuaciones diferenciales que pueden ser reescritas a un sistema de ecuaciones de primer orden[fn:1]:

#+BEGIN_EXPORT latex
\begin{align*}
  \dot{x}_1 &= \left[a_{11} x_1(t) + \dots + a_{1n} x_n(t)\right] + \left[b_{11} u_1(t) + \dots + b_{1m}u_r(t) \right]\\
  \vdots\\
    \dot{x}_n &= \left[a_{n1} x_1(t) + \dots + a_{nn} x_n(t)\right] + \left[b_{n1} u_1(t) + \dots + b_{nr}u_r(t) \right] 
\end{align*}

\begin{align*}
  y_1(t) &= \left[c_{11} x_1(t) + \dots + c_{1n} x_n(t)\right] + \left[d_{11} u_1(t) + \dots + d_{1r}u_r(t) \right]\\
  \vdots\\
    y_m(t) &= \left[c_{m1} x_1(t) + \dots + c_{mn} x_n(t)\right] + \left[d_{m1} u_1(t) + \dots + d_{mr}u_r(t) \right] 
\end{align*}

#+END_EXPORT

** Nomenclatura

- $x_1(t) \dots x_n(t)$ son las *n* variables del circuito, denominadas *variables de estado*, representadas como un vector $\mathbf{x}$ de dimensión n (*vector de estado*)
  - /Elegimos tensiones de condensadores y corrientes de bobinas/.
#+BEAMER: \pause
- $u_1(t) \dots u_r(t)$ son las *r* entradas del circuito, representadas con un vector $\mathbf{u}$ de dimensión r (*vector de entrada*)
#+BEAMER: \pause
- $y_1(t) \dots y_m(t)$ son las *m* salidas del circuito, representadas con un vector $\mathbf{y}$ de dimensión m (*vector de salida*)


** Notación funcional y matricial
*** Ecuación de estado
#+BEGIN_EXPORT latex
\begin{align*}
\dot{\mathbf{x}} &= f(\mathbf{x}, \mathbf{u}, t)\\
\dot{\mathbf{x}} &= \mathbf{A}\mathbf{x} + \mathbf{B}\mathbf{u}\\
\end{align*}
#+END_EXPORT

*** Ecuación de salida[fn:2]
#+BEGIN_EXPORT latex
\begin{align*}
\mathbf{y} &= g(\mathbf{x}, \mathbf{u}, t)\\
\mathbf{y} &= \mathbf{C}\mathbf{x} + \mathbf{D}\mathbf{u} 
\end{align*}
#+END_EXPORT

** Diagrama de Bloques

[[file:../figs/Bloques_Variables_Estado.pdf]]

#+BEGIN_EXPORT latex
\begin{align*}
  \dot{\mathbf{x}} &= \mathbf{A}\mathbf{x} + \mathbf{B}\mathbf{u}\\
  \mathbf{y} &= \mathbf{C}\mathbf{x} + \mathbf{D}\mathbf{u} 
\end{align*}
#+END_EXPORT

** Ventajas del análisis con variables de estado

- Las ecuaciones diferenciales son de primer orden. Existen numerosas técnicas disponibles para resolverlas.
- Ecuaciones de estado y de salida se pueden programar fácilmente (/enfoque orientado a computación/).
- Teoría de Sistemas: amplio conocimiento matemático para determinar las propiedades de la solución.

** Trayectoria
- Supongamos un circuito de segundo orden determinado por las variables $i_L(t)$ y $v_c(t)$.
- La *evolución con el tiempo* de estas dos variables (/intercambio y disipación de energía almacenada/) se puede representar como *coordenadas de puntos en un plano*.
- El plano $i_L$ -- $v_C$ es el *espacio de estados*. La curva que une estos puntos es la *trayectoria en el espacio de estados*.
- La curva comenzará en el punto de condiciones iniciales, $[i_L(0^+), v_C(0^+)]$, y finalizará en el régimen permanente $[i_L(\infty), v_C(\infty)]$.

** Trayectoria
#+ATTR_LATEX: :height 0.8\textheight
[[file:../figs/trayectoria.pdf]]

* Topología de Redes

** Definiciones

- *Grafo*: representación simplificada de un circuito eléctrico.
#+ATTR_LATEX: :height 0.65\textheight
[[file:../figs/grafo.pdf]]

** Definiciones

- *Árbol*: conjunto de ramas que unen todos los nudos sin formar caminos cerrados.
#+ATTR_LATEX: :height 0.65\textheight
[[file:../figs/grafo.pdf]]

** Definiciones

- *Cuerdas* o *Eslabones*: ramas no incluidas en el árbol.
- *Lazos básicos*: lazos de un árbol con sólo un eslabón.
#+ATTR_LATEX: :height 0.65\textheight
[[file:../figs/grafo.pdf]]

** Definiciones

- *Grupos de corte*: conjunto de ramas al que aplica la LKC.
- *Grupos de corte básicos*: grupo de corte que contiene sólo una rama del árbol.
#+ATTR_LATEX: :height 0.65\textheight
[[file:../figs/grafo.pdf]]

** LKC y LKV
- Al aplicar la *LKC* en los *grupos de corte básico* se obtienen ecuaciones linealmente independientes.
- Al aplicar la *LKV* en los *lazos básicos* se obtienen ecuaciones linealmente independientes.

* Planteamiento Sistemático de Ecuaciones

** Árbol Propio
*** Fundamento
- Las variables de estado a elegir son $u_C(t)$ e $i_L(t)$.
- Las ecuaciones de condensadores evalúan corrientes (LKC en grupos de corte básico).
#+BEGIN_EXPORT latex
\[
\diff{u_c}{t} = \frac{i_c}{C}
\] 
#+END_EXPORT
- Las ecuaciones de bobinas evalúan tensiones (LKV en lazos básicos)
#+BEGIN_EXPORT latex
\[
\diff{i_L}{t} = \frac{u_L}{L}
\] 
#+END_EXPORT

** Árbol propio
*** Composición
- Todas las fuentes de tensión.
- Todos los condensadores.
- Resistencias (las que sean necesarias).
- Ninguna inductancia (situar en eslabones).
- Ninguna fuente de corriente (situar en eslabones).

** Ecuación de estado en forma normal

1. Establecer el *árbol normal*.\pause
2. *Variables de Estado*: asignar tensiones (/con polaridad/) a condensadores y corrientes (/con sentido/) a inductancias.\pause
3. *Variables adicionales*: tensiones y corrientes en resistencias según necesidad.\pause
4. Una *ecuación para cada condensador* (usando LKC en el grupo de corte básico que corresponda).\pause
5. Una *ecuación para cada inductancia* (usando LKV en el lazo básico que corresponda).\pause
6. *Ecuaciones para resistencias* para determinar variables adicionales (punto 3) en función de variables de estado.\pause

7. Usar ecuaciones de punto 6 en puntos 4 y 5

* Resolución

** Laplace
*** Ecuación de Estado
#+BEGIN_EXPORT latex
\begin{align*}
  \dot{\mathbf{x}} &= \mathbf{A}\mathbf{x} + \mathbf{B}\mathbf{u}\\
  \slp \laplace{X} - \mathbf{x}(0^-) &= \mathbf{A}\laplace{X} + \mathbf{B}\laplace{U}\\
\end{align*}
#+END_EXPORT
*** Ecuación de Salida
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf{y} &= \mathbf{C}\mathbf{x}\\
  \laplace{Y} &= \mathbf{C}\laplace{X}
\end{align*}
#+END_EXPORT
** Ecuación de Estado con Laplace
*** Desarrollo
#+BEGIN_EXPORT latex
\begin{align*}
  \slp \laplace{X} - \mathbf{x}(0^-) &= \mathbf{A}\laplace{X} + \mathbf{B}\laplace{U}\\
  \slp \laplace{X} - \mathbf{A}\laplace{X} &= \mathbf{x}(0^-) + \mathbf{B}\laplace{U}\\
  \left(\slp \mathbf{I} - \mathbf{A} \right) \laplace{X} &= \mathbf{x}(0^-) + \mathbf{B}\laplace{U}\\
  \laplace{X} &= \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{x}(0^-) +\\ 
  &+ \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{B}\laplace{U}
\end{align*}
#+END_EXPORT

** Matriz $\slp \mathbf{I} - \mathbf{A}$
#+BEGIN_EXPORT latex
\[
\slp \mathbf{I} - \mathbf{A} = 
\begin{bmatrix} 
\slp - a_{11} & -a_{12} & \dots & -a_{1n}\\
- a_{21} & \slp -a_{22} & \dots & -a_{2n}\\
\vdots & \vdots & \dots & \vdots \\
- a_{n1} & -a_{n2} & \dots & \slp - a_{nn}
\end{bmatrix}
\]

\[
\left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} = \frac{\text{adj}(\slp \mathbf{I} - \mathbf{A})^T}{\det(\slp \mathbf{I} - \mathbf{A})}
\]
#+END_EXPORT

** Solución de la Ecuación de Estado
*** Solución
#+BEGIN_EXPORT latex
\[
  \laplace{X} = \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{x}(0^-) + \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{B}\laplace{U}
\]
#+END_EXPORT

*** Respuesta a Entrada Cero
#+BEGIN_EXPORT latex
\[
  \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{x}(0^-)
\]
#+END_EXPORT

*** Respuesta a Estado Inicial Cero
#+BEGIN_EXPORT latex
\[
  \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{B}\laplace{U}
\]
#+END_EXPORT

** Función de Transferencia
*** Función de Transferencia
#+BEGIN_EXPORT latex
Suponiendo condiciones iniciales nulas:
\begin{align*}
  \laplace{X} &= \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{B} \laplace{U}\\
  \laplace{Y} &= \mathbf{C} \laplace{X}\\
  \laplace{H} &= \frac{\laplace{Y}}{\laplace{U}}  = \mathbf{C} \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} \mathbf{B}
\end{align*}
#+END_EXPORT

*** Polos del Sistema
#+BEGIN_EXPORT latex
\[
  \left(\slp \mathbf{I} - \mathbf{A} \right)^{-1} = \frac{\text{adj}(\slp \mathbf{I} - \mathbf{A})^T}{\det(\slp \mathbf{I} - \mathbf{A})}
\]
Los polos del sistema se calculan con:
\[
|\slp \mathbf{I} - \mathbf{A}| = 0
\]
#+END_EXPORT
* Ejercicios Recomendados

** Ejercicios
- FM: Ejemplo de aplicación 4.18
- HKD: Ejemplos 19.1, 19.2, 19.3
- Exámenes
* Footnotes

[fn:2] Frecuentemente la matriz $\mathbf{D}$ es nula, $\mathbf{y} = \mathbf{C}\mathbf{x}$.

[fn:1] Notación: \[\dot{x} = \diff{x(t)}{t}\]



